import assert from 'node:assert/strict';
import {createScenario} from '../dist/scenario-setup.js';
import {build,tick,validateSave,idx,recompute} from '../dist/engine.js';
import {serializeCity} from '../dist/save.js';
import {CUSTOM_METRICS} from '../dist/custom-scenarios.js';
import {STRUCTURE_METRICS} from '../dist/scenario-structures.js';
import {harborPaths} from '../dist/harbor-visuals.js';
import {ignite,stepFire} from '../dist/emergency.js';
const c=createScenario('harbor');for(let n=0;n<6;n++)tick(c);
const members=c.tiles.filter(t=>t.type==='seaport');
assert.equal(members.length,12);assert.ok(members.every(t=>!t.level&&t.facilityAbandoned));
assert.equal(c.stats.abandonedFacilities,1);assert.equal(harborPaths(c).length,0);
assert.equal(STRUCTURE_METRICS.structuresSeaport.read(c),1);
assert.equal(CUSTOM_METRICS.abandonedFacilities.read(c,{x:10,y:20,radius:0}),1);
assert.equal(CUSTOM_METRICS.abandonedFacilities.read(c,{x:11,y:20,radius:0}),0);
const raw=JSON.parse(serializeCity(c)),saved=validateSave(raw);
assert.equal(saved.stats.abandonedFacilities,1);
assert.equal(build(saved,'dezone',[{x:11,y:21}]).ok,false);
assert.ok(build(saved,'pipe',[{x:19,y:20}]).ok);
for(let n=0;n<6;n++)tick(saved);
assert.ok(saved.tiles.filter(t=>t.type==='seaport').every(t=>t.level===1&&!t.facilityAbandoned));
assert.equal(saved.stats.abandonedFacilities,0);assert.equal(harborPaths(saved).length,1);
const cleared=validateSave(JSON.parse(serializeCity(c)));
assert.ok(build(cleared,'bulldoze',[{x:11,y:21}]).ok);
assert.ok(cleared.tiles.filter(t=>t.type==='seaport').every(t=>!t.level&&!t.facilityAbandoned));
assert.equal(STRUCTURE_METRICS.structuresSeaport.read(cleared),0);
const burned=validateSave(JSON.parse(serializeCity(c)));assert.ok(ignite(burned,10,20).ok);
burned.tiles[idx(10,20)].fire=100;burned.tiles[idx(10,20)].fireAge=100;stepFire(burned);recompute(burned);
assert.ok(burned.tiles.filter(t=>t.type==='seaport').every(t=>!t.facilityAbandoned));assert.equal(burned.stats.abandonedFacilities,0);
const bad=JSON.parse(serializeCity(c));bad.tiles[idx(10,20)].facilityAbandoned=false;assert.throws(()=>validateSave(bad));
const legacy=JSON.parse(serializeCity(c));legacy.version=74;for(const t of legacy.tiles)delete t.facilityAbandoned;assert.equal(validateSave(legacy).stats.abandonedFacilities,0);
const vacant=validateSave(legacy);for(let n=0;n<6;n++)tick(vacant);assert.equal(vacant.stats.abandonedFacilities,0);
console.log('PASS: abandoned facility footprints persist, root-only scenario counts, six-month service recovery, complete bulldozing and fire destruction, migration and malformed save rejection.');
