import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {createCity} from '../dist/engine.js';
import {serializeCity} from '../dist/save.js';
import {developmentBriefing,showDevelopmentAdvisor} from '../dist/development-advisors.js';
import {ADVISOR_ROSTER,showAdvisorDesk} from '../dist/advisor-desk.js';
const c=createCity('Departments',false),before=serializeCity(c);assert.equal(ADVISOR_ROSTER.length,7);assert.equal(new Set(ADVISOR_ROSTER.map(r=>r[0])).size,7);
assert.match(developmentBriefing(c,'planning').issues[0].title,/first neighborhood/);for(const kind of ['planning','environment','utilities'])assert.ok(developmentBriefing(c,kind).issues.length);assert.equal(serializeCity(c),before);assert.throws(()=>developmentBriefing(c,'wrong'));
c.stats.powerDemand=10;c.stats.powerServed=0;c.stats.powerNetworks=[{available:1000,demand:0}];let d=developmentBriefing(c,'utilities');assert.ok(d.issues.some(i=>i.title==='Deliver missing electricity'));c.stats.powerServed=10;assert.ok(!developmentBriefing(c,'utilities').issues.some(i=>i.title==='Deliver missing electricity'));c.stats.powerNetworks=[{available:10,demand:10}];assert.ok(developmentBriefing(c,'utilities').issues.some(i=>i.title==='Keep electricity headroom'));
Object.assign(c.stats,{uncollectedWaste:30,landfillCapacity:100,landfillStored:90,averagePollution:30});c.tiles.forEach(t=>t.waterPollution=20);d=developmentBriefing(c,'environment');assert.ok(d.issues.some(i=>i.action==='policies'));assert.ok(d.issues.some(i=>i.tool==='waterTreatment'));assert.ok(d.issues.some(i=>i.title==='Plan disposal before landfills fill'));
const t=c.tiles[20*c.size+20];Object.assign(t,{type:'residential',level:0,abandonedLevel:1,landValue:60,powered:false,access:false,watered:false});d=developmentBriefing(c,'planning');assert.ok(d.issues.some(i=>i.title==='Recover abandoned buildings'));assert.ok(d.issues.some(i=>i.title==='Fix stalled sites'));
let html='',title='',mapped='',tool='',report='',closed=0,back=0;const controls=new Map(),groups=new Map();globalThis.document={querySelector:s=>{if(!controls.has(s))controls.set(s,{});return controls.get(s);},querySelectorAll:s=>{const attr=s.slice(1,-1),key=attr.replace('data-','').replace(/-([a-z])/g,(_,ch)=>ch.toUpperCase()),nodes=Array.from(html.matchAll(new RegExp(attr+'="([^"<>]+)"','g')),m=>({dataset:{[key]:m[1]}}));groups.set(s,nodes);return nodes;}};
const ui={city:()=>c,dialog:(name,body)=>{title=name;html=body;},back:()=>back++,budget:()=>report='budget',transport:()=>report='transport',civic:()=>report='civic',utilities:()=>report='utilities',policies:()=>report='policies',growth:()=>report='growth',ordinances:()=>report='policies',setLayer:l=>mapped=l,setTool:v=>tool=v,close:()=>closed++,locate:()=>{}};
for(const [key,name,,portrait] of ADVISOR_ROSTER){showAdvisorDesk(ui);assert.equal(groups.get('[data-meet-advisor]').length,7);groups.get('[data-meet-advisor]').find(n=>n.dataset.meetAdvisor===key).onclick();assert.equal(title,name);const png=readFileSync(new URL('../dist/assets/'+portrait+'-advisor.png',import.meta.url));assert.equal(png.subarray(1,4).toString(),'PNG');}
showDevelopmentAdvisor(ui,'environment',()=>back++);groups.get('[data-development-report]')[0].onclick();assert.equal(report,'utilities');groups.get('[data-development-map]')[0].onclick();assert.equal(mapped,'waste');groups.get('[data-development-plan]')[0].onclick();assert.equal(tool,'landfill');assert.equal(closed,2);controls.get('#developmentBack').onclick();assert.equal(back,1);
console.log('PASS: all seven advisor routes and portraits, read-only briefings, local utility shortfalls despite remote spare supply, power headroom, environmental capacity/pollution, abandoned growth and report/map/planning actions.');
