import assert from 'node:assert/strict';
import {createCity,recompute,tick,validateSave} from '../dist/engine.js';
import {workforceOutlook,workforceAgeTable} from '../dist/workforce.js';
import {serializeCity} from '../dist/save.js';
const c=createCity(),population=c.stats.population;const setAge=age=>{c.demographics.cohorts=Array(8).fill(0);c.demographics.cohorts[age]=population;c.demographics.flows=null;recompute(c);};
setAge(0);assert.equal(c.stats.commuters,0);assert.equal(c.stats.unemployed,0);setAge(3);const adult=c.stats.commuters;assert.ok(adult>population*.6&&adult<population);assert.equal(c.stats.population,population);setAge(7);assert.ok(c.stats.commuters<adult*.1);setAge(3);const before=c.stats.commuters;for(const t of c.tiles)if(t.type==='road')t.type=null;recompute(c);assert.equal(c.stats.commuters,before);assert.ok(Math.abs(c.stats.unemployed-before)<1e-8,'age supply still needs reachable jobs');
const healthy=createCity();healthy.demographics.cohorts=Array(8).fill(0);healthy.demographics.cohorts[6]=healthy.stats.population;healthy.civic.lifeExpectancy=45;recompute(healthy);const low=healthy.stats.commuters;healthy.civic.lifeExpectancy=90;recompute(healthy);assert.ok(healthy.stats.commuters>low);assert.ok(workforceOutlook(healthy).healthDifference>0);assert.match(workforceAgeTable(healthy),/Children under 15 do not work/);
const live=createCity();for(let i=0;i<24;i++)tick(live);const saved=validateSave(JSON.parse(serializeCity(live)));assert.ok(Math.abs(saved.stats.commuters-live.stats.commuters)<1e-8,'end-of-month routes use the updated age census');for(let i=0;i<12;i++){tick(live);tick(saved);}assert.deepEqual(saved.demographics,live.demographics);assert.equal(saved.stats.commuters,live.stats.commuters);assert.ok(Math.abs(workforceOutlook(live).rows.reduce((s,r)=>s+r.workers,0)-live.stats.commuters)<1e-7);
console.log('PASS: age-specific actual worker supply, no child labor, older participation, route loss unemployment, health within ages and saved monthly continuation.');
