import assert from 'node:assert/strict';
import {createCity,build,selection,idx,tick} from '../dist/engine.js';
import {airportFlights,drawAirportFlight} from '../dist/airport-visuals.js';
const c=createCity('Flights',false);for(const t of c.tiles){t.terrain='land';t.nature=false;}for(let y=0;y<48;y++)c.tiles[idx(18,y)].terrain='water';build(c,'pump',[{x:19,y:21}]);build(c,'pipe',selection('pipe',{x:19,y:21},{x:23,y:21}));build(c,'road',selection('road',{x:24,y:20},{x:24,y:25}));build(c,'coal',[{x:26,y:20}]);build(c,'airport',selection('airport',{x:20,y:20},{x:22,y:24}));assert.equal(airportFlights(c,0).length,0);for(let i=0;i<6;i++)tick(c);assert.equal(c.stats.activeAirports,1);
const before=JSON.stringify(c),a=airportFlights(c,0)[0],b=airportFlights(c,1)[0];assert.equal(a.x,b.x);assert.ok(Math.abs(Math.abs(a.y-b.y)-1.2)<1e-9);assert.deepEqual(airportFlights(c,0),airportFlights(c,0),'held time is stationary');assert.equal(a.altitude,8);
let gaps=0;for(let time=0;time<200;time+=.5){const flights=airportFlights(c,time);if(!flights.length)gaps++;for(const f of flights){assert.ok(f.alpha>=0&&f.alpha<=1);assert.ok(f.x>=-3&&f.x<=50&&f.y>=-3&&f.y<=50);}}assert.ok(gaps>0,'separate flights have an off-map interval');assert.equal(JSON.stringify(c),before,'visual sampling never mutates the simulation');
const horizontal=structuredClone(c);horizontal.stats.facilityPlots[0].width=5;horizontal.stats.facilityPlots[0].height=3;const h0=airportFlights(horizontal,0)[0],h1=airportFlights(horizontal,1)[0];assert.equal(h0.y,h1.y);assert.notEqual(h0.x,h1.x);
// World altitude cancels terrain projection in every camera orientation.
function draw(rotation,elevation,shadow){const points=[];const city={tiles:Array.from({length:2304},()=>({elevation}))},ctx={beginPath(){},closePath(){},fill(){},save(){},restore(){},moveTo(x,y){points.push([x,y]);},lineTo(x,y){points.push([x,y]);}};const r={ctx,unit:10,w:1000,h:1000,getCity:()=>city,project(x,y){let rx=x,ry=y;if(rotation===1){rx=47-y;ry=x;}if(rotation===2){rx=47-x;ry=47-y;}if(rotation===3){rx=y;ry=47-x;}return{x:500+(rx-ry)*10,y:300+(rx+ry-48)*5-elevation*5};}};drawAirportFlight(r,{...a,x:24,y:24},shadow);return points;}
for(let rotation=0;rotation<4;rotation++){assert.deepEqual(draw(rotation,0,false),draw(rotation,8,false));assert.notDeepEqual(draw(rotation,0,true),draw(rotation,8,true));}
build(c,'bulldoze',[{x:19,y:21}]);assert.equal(c.stats.activeAirports,0);assert.equal(airportFlights(c,0).length,0);build(c,'pump',[{x:19,y:21}]);assert.equal(c.stats.activeAirports,1);assert.equal(airportFlights(c,0).length,1);build(c,'bulldoze',[{x:21,y:22}]);assert.equal(airportFlights(c,0).length,0);
console.log('PASS: service-gated airport overflights, real six-month development, orientation, held clock, bounded cadence, immutable sampling, terrain-independent altitude in four views, service recovery and demolition.');
