import assert from 'node:assert/strict';
import {createCity,validateSave} from '../dist/engine.js';
import {serializeCity} from '../dist/save.js';
import {showBuildingSetImport} from '../dist/building-set-ui.js';
import {defaultBuildingDesign} from '../dist/building-designs.js';
const city=createCity(),source=createCity('Set source');source.buildingDesigns={2:{...defaultBuildingDesign(2),name:'<b>Custom</b>'}};
let controls,html,saves=0,backups=0,closed=0;
const dialog=(title,body)=>{html=body;controls=new Map([...body.matchAll(/id="([^"]+)"/g)].map(m=>[m[1],{disabled:m[1]==='buildingSetApply',textContent:'',innerHTML:''}]));};
globalThis.document={getElementById:id=>controls.get(id),contains:el=>[...controls.values()].includes(el)};
const ui={city,dialog,validateCity:validateSave,apply(){saves++;},backup(){backups++;},close(){closed++;controls.clear();}},get=id=>controls.get('buildingSet'+id);
const choose=async text=>{get('File').files=[{size:text.length,text:async()=>text}];await get('File').onchange();};
showBuildingSetImport(ui);assert.match(html,/entire building set/);const before=serializeCity(city);await choose(serializeCity(source));assert.equal(serializeCity(city),before);assert.equal(get('Apply').disabled,false);assert.match(get('Review').innerHTML,/&lt;b&gt;Custom/);assert.doesNotMatch(get('Review').innerHTML,/<b>Custom/);
get('Backup').onclick();assert.equal(backups,1);get('Close').onclick();assert.equal(closed,1);assert.equal(serializeCity(city),before,'cancel unchanged');
showBuildingSetImport(ui);await choose(serializeCity(source));await choose('bad');assert.equal(get('Apply').disabled,true);get('Apply').onclick();assert.equal(saves,0);assert.equal(serializeCity(city),before,'failed import clears earlier draft');
await choose(serializeCity(source));get('Apply').onclick();assert.equal(saves,1);assert.deepEqual(city.buildingDesigns,source.buildingDesigns);get('Apply').onclick();assert.equal(saves,1,'apply once');
let read=false;get('File').files=[{size:67108865,text:async()=>{read=true;}}];await get('File').onchange();assert.equal(read,false);assert.match(get('Status').textContent,/64 MB/);
let resolve;get('File').files=[{size:1,text:()=>new Promise(r=>resolve=r)}];const old=get('File').onchange();await choose(serializeCity(createCity('Empty set')));resolve(serializeCity(source));await old;assert.match(get('Status').textContent,/Empty set/);get('Apply').onclick();assert.deepEqual(city.buildingDesigns,{});
get('File').files=[{size:1,text:()=>new Promise(r=>resolve=r)}];const closedRead=get('File').onchange();get('Close').onclick();resolve(serializeCity(source));await closedRead;assert.equal(saves,2,'closed dialog cannot import');
console.log('PASS: actual building-set dialog handlers preview escaped model names, preserve city until apply, back up, cancel, reject oversized/malformed files, discard stale reads and apply a complete set exactly once.');
