import assert from 'node:assert/strict';
import {createCity} from '../dist/engine.js';
import {deriveBuildingLots,buildingLotCandidate,formBuildingLot,buildingLotMembers,updateBuildingLot,dissolveBuildingLot,isBuildingLotRoot} from '../dist/building-lots.js';
const prepare=(size=48,type='residential')=>{const c=createCity('Lots',false,size);for(const t of c.tiles)Object.assign(t,{terrain:'land',elevation:0,type,density:3,level:0,nature:false,powered:true,watered:true,access:true,lotRoot:null});return c;};
for(const size of [48,96,128,256])for(const type of ['residential','commercial','industrial']){const c=prepare(size,type),root=c.tiles[(size-5)*size+size-5],before=JSON.stringify(c.tiles),candidate=buildingLotCandidate(c,root,3,2);assert.equal(candidate.length,6);assert.equal(JSON.stringify(c.tiles),before,'preview is read-only');const lot=formBuildingLot(c,root,3,2);assert.equal(lot.ids.length,6);assert.deepEqual(deriveBuildingLots(c),c.buildingLots);assert.equal(buildingLotMembers(c,c.tiles[lot.ids.at(-1)]).length,6);assert.equal(lot.ids.filter(i=>isBuildingLotRoot(c,c.tiles[i])).length,1);updateBuildingLot(c,root,{level:2,age:8,historicalLevel:2});assert.ok(lot.ids.every(i=>c.tiles[i].level===2&&c.tiles[i].historicalLevel===2));assert.deepEqual(deriveBuildingLots(c),c.buildingLots);assert.equal(buildingLotCandidate(c,root,2),null);const members=dissolveBuildingLot(c,c.tiles[lot.ids[1]]);assert.equal(members.length,6);assert.equal(deriveBuildingLots(c).size,0);assert.equal(c.buildingLots.size,0);}
for(const change of [{terrain:'water'},{elevation:1},{type:'road'},{density:1},{level:1},{historicalLevel:1},{abandonedLevel:2},{industry:'farm'},{rubble:true},{radiation:true},{fire:1},{rail:true},{highway:true},{powered:false},{watered:false},{access:false},{waste:20}]){const c=prepare(),r=c.tiles[10*48+10];Object.assign(c.tiles[11*48+11],change);assert.equal(formBuildingLot(c,r,2),null);assert.ok(c.tiles.every(t=>t.lotRoot===null),'failed formation has no partial writes');}
for(const dimensions of [[0,2],[5,2],[1,1],[2.5,2]])assert.equal(buildingLotCandidate(prepare(),{x:10,y:10,type:'residential',density:3},...dimensions),null);
const c=prepare(),r=c.tiles[10*48+10];formBuildingLot(c,r,2);const pristine=JSON.stringify(c.tiles);for(const change of [{lotRoot:999999},{lotRoot:null},{level:2},{density:2},{age:1},{stress:1},{elevation:1},{rubble:true},{radiation:true},{rail:true},{type:'commercial'}]){c.tiles=JSON.parse(pristine);Object.assign(c.tiles[11*48+11],change);assert.throws(()=>deriveBuildingLots(c));}c.tiles=JSON.parse(pristine);c.tiles[r.lotRoot].lotRoot=11*48+11;assert.throws(()=>deriveBuildingLots(c));
const edge=prepare();assert.equal(buildingLotCandidate(edge,edge.tiles.at(-1),2),null);
console.log('PASS: read-only lot previews, atomic formation, rectangular grouping across four sizes and RCI sectors, shared lifecycle/root identity, dissolution, obstacle and utility guards, malformed/inconsistent group rejection.');
