import assert from 'node:assert/strict';
import {buildingShapeCells,applyBuildingShape} from '../dist/building-shapes.js';
import {mountBuildingBlockEditor} from '../dist/building-block-editor.js';
import {defaultBuildingDesign,exportBuildingDesign,importBuildingDesign} from '../dist/building-designs.js';
assert.deepEqual(buildingShapeCells('line',11,15),[11,12,13,14,15]);assert.deepEqual(buildingShapeCells('line',11,44),[11,22,33,44]);assert.deepEqual(buildingShapeCells('plane',33,11),[11,12,13,21,22,23,31,32,33]);assert.equal(buildingShapeCells('plane',0,99).length,100);
for(let a=0;a<100;a++)for(let b=0;b<100;b++){const line=buildingShapeCells('line',a,b);assert.equal(line[0],a);assert.equal(line.at(-1),b);assert.equal(new Set(line).size,line.length);assert.ok(line.every(i=>i>=0&&i<100));for(let j=1;j<line.length;j++)assert.ok(Math.abs(line[j]%10-line[j-1]%10)<=1&&Math.abs(Math.floor(line[j]/10)-Math.floor(line[j-1]/10))<=1);}
for(const args of [['other',0,1],['line',-1,1],['plane',0,100]])assert.throws(()=>buildingShapeCells(...args));assert.throws(()=>applyBuildingShape(Array(100).fill(0),'line',0,1,25));
const controls=new Map(),make=()=>({value:'',style:{},disabled:false,setAttribute(){},focus(){},closest(){return this;}});for(const id of ['towerGroundHistory','towerGroundUndo','towerGroundRedo','blockMode','blockWorkspace','blockUndo','blockRedo','blockTool','blockShape','blockSide','blockBrush','blockMaterial','blockStatus','blockFromTower','blockClear'])controls.set(id,make());
const cells=Array.from({length:100},(_,i)=>({...make(),dataset:{blockIndex:String(i)}})),grid={querySelectorAll:()=>cells,setPointerCapture(){},contains:c=>cells.includes(c)};controls.set('blockGrid',grid);controls.set('voxelEditor',{querySelector:s=>{const id=s.slice(1);if(!controls.has(id))controls.set(id,id==='voxelGrid'?{querySelectorAll:()=>[]}:make());return controls.get(id);}});globalThis.document={getElementById:()=>make(),elementFromPoint:x=>cells[x]};
const root={innerHTML:'',querySelector:s=>controls.get(s.slice(1))};let draft={...defaultBuildingDesign(),blocks:Array(100).fill(0),materials:Array(500).fill(1)},writes=0;draft.blocks[99]=4;const editor=mountBuildingBlockEditor(root,{get:()=>draft,set:d=>{draft=d;writes++;}}),$=id=>controls.get(id);
$('blockTool').value='height';$('blockShape').value='line';$('blockBrush').value='8';$('blockSide').value='4';editor.refresh();const before=structuredClone(draft);
const down=i=>grid.onpointerdown({button:0,target:cells[i],pointerId:1,preventDefault(){}}),move=i=>grid.onpointermove({pointerId:1,clientX:i,clientY:0}),up=(shiftKey=false)=>grid.onpointerup({pointerId:1,shiftKey});
down(11);move(15);assert.equal(writes,0,'preview does not change the draft');assert.equal(cells.filter(c=>c.style.boxShadow).length,5);up();assert.equal(writes,1);assert.deepEqual(draft.blocks.slice(11,16),[8,8,8,8,8]);const painted=structuredClone(draft);$('blockUndo').onclick();assert.deepEqual(draft,before,'whole gesture is one undo');$('blockRedo').onclick();assert.deepEqual(draft,painted,'redo includes surface materials');
$('blockShape').value='plane';down(22);move(44);up(true);assert.deepEqual(draft,painted,'Shift release cancels');down(22);move(44);grid.onpointercancel();assert.deepEqual(draft,painted,'pointer cancellation discards preview');
const key=(key,shiftKey=false)=>grid.onkeydown({key,shiftKey,target:cells[11],preventDefault(){}});down(11);up(true);key('Enter',true);key('ArrowDown');key('Enter');assert.equal(draft.blocks[21],8,'keyboard plane commits');$('blockUndo').onclick();assert.deepEqual(draft,painted);$('blockBrush').value='3';down(30);move(32);up();assert.equal($('blockRedo').disabled,true,'new editing discards redo');
$('blockBrush').value='0';down(30);move(32);up();assert.equal(draft.blocks[31],0,'shapes erase with zero height');assert.deepEqual(importBuildingDesign(exportBuildingDesign(draft)),draft,'existing portable format preserves constructed shapes');
console.log('PASS: line/plane geometry across the footprint, nonmutating previews, atomic undo/redo with materials, pointer and Shift cancellation, keyboard placement, redo invalidation, erase and portable design roundtrip.');

const floorPaint='0'.repeat(100)+'4'+'0'.repeat(11899),beforeFloorPaint=JSON.stringify(draft);editor.applyFloorPaint(floorPaint);assert.equal(draft.surfacePaint,floorPaint);$('blockUndo').onclick();assert.equal(JSON.stringify(draft),beforeFloorPaint);$('blockRedo').onclick();assert.equal(draft.surfacePaint,floorPaint);

$('blockMode').value='tower';$('blockMode').onchange();assert.equal(draft.surfacePaint,undefined);$('blockMode').value='blocks';$('blockMode').onchange();assert.equal(draft.surfacePaint,floorPaint,'height draft retains per-floor paint across mode changes');

const detailLayer='3'+'0'.repeat(11999),beforeDetail=JSON.stringify(draft);editor.applyDetails(detailLayer);assert.equal(draft.surfaceDetails,detailLayer);$('blockUndo').onclick();assert.equal(JSON.stringify(draft),beforeDetail);$('blockRedo').onclick();assert.equal(draft.surfaceDetails,detailLayer);editor.applyFloorPaint('1'.repeat(12000));assert.equal(draft.surfaceDetails,detailLayer);$('blockUndo').onclick();assert.equal(draft.surfaceDetails,detailLayer);

const propList=[{kind:'car',x:2,y:3,z:.26,rotation:1}],beforeProp=JSON.stringify(draft);editor.applyProps(propList);assert.deepEqual(draft.props,propList);$('blockUndo').onclick();assert.equal(JSON.stringify(draft),beforeProp);$('blockRedo').onclick();assert.deepEqual(draft.props,propList);$('blockMode').value='tower';$('blockMode').onchange();assert.ok(draft.blocks);assert.equal($('blockMode').value,'blocks');assert.deepEqual(draft.props,propList);editor.applyProps([]);$('blockMode').value='tower';$('blockMode').onchange();assert.equal(draft.props,undefined);assert.equal(draft.blocks,undefined);

// Props belong to the model, not to the remembered construction representation.
$('blockMode').value='blocks';$('blockMode').onchange();editor.applyProps(propList);
$('blockMode').value='voxels';$('blockMode').onchange();assert.deepEqual(draft.props,propList);
const movedProps=[{...propList[0],x:7,rotation:3}];editor.applyProps(movedProps);
$('blockMode').value='blocks';$('blockMode').onchange();assert.deepEqual(draft.props,movedProps,'returning to height layout preserves newly edited props');
$('blockMode').value='voxels';$('blockMode').onchange();editor.applyProps([]);
$('blockMode').value='blocks';$('blockMode').onchange();assert.deepEqual(draft.props,[],'returning to height layout does not resurrect removed props');

const erasedBatch=[{kind:'pickup',x:2,y:2,z:0,rotation:3},{kind:'bench',x:7,y:7,z:0,rotation:1}];editor.applyProps(erasedBatch);editor.applyProps([]);$('blockUndo').onclick();assert.deepEqual(draft.props,erasedBatch,'one Undo restores every prop in the erase stroke');$('blockRedo').onclick();assert.deepEqual(draft.props,[]);
const beforeGround=JSON.stringify(draft),lawn='6'.repeat(100),pavement='7'.repeat(100);editor.applyGroundPaint(lawn);assert.equal(draft.groundPaint,lawn);$('blockUndo').onclick();assert.equal(JSON.stringify(draft),beforeGround);$('blockRedo').onclick();assert.equal(draft.groundPaint,lawn);
$('blockMode').value='voxels';$('blockMode').onchange();assert.equal(draft.groundPaint,lawn);editor.applyGroundPaint(pavement);$('blockMode').value='blocks';$('blockMode').onchange();assert.equal(draft.groundPaint,pavement,'ground follows current model across construction modes');
const anchored=[{kind:5,side:2,plane:5,u:2,z:.4,width:3,height:.12}],beforeDecals=JSON.stringify(draft);editor.applyDecals(anchored);assert.deepEqual(draft.decals,anchored);$('blockUndo').onclick();assert.equal(JSON.stringify(draft),beforeDecals);$('blockRedo').onclick();assert.deepEqual(draft.decals,anchored);$('blockMode').value='voxels';$('blockMode').onchange();editor.applyDecals([]);$('blockMode').value='blocks';$('blockMode').onchange();assert.deepEqual(draft.decals,[],'mode memory cannot resurrect erased anchored details');
// Ground belongs to the current lot, even when construction memories differ.
$('blockMode').value='tower';$('blockMode').onchange();assert.equal(draft.groundPaint,pavement);assert.equal(draft.blocks,undefined);assert.equal(draft.voxels,undefined);
editor.applyGroundPaint(lawn);$('towerGroundUndo').onclick();assert.equal(draft.groundPaint,pavement);$('towerGroundRedo').onclick();assert.equal(draft.groundPaint,lawn);
draft={...draft,floors:17};$('towerGroundUndo').onclick();assert.equal(draft.floors,17,'ground history never rewinds tower parameters');assert.equal(draft.groundPaint,pavement);
const third='1'.repeat(100);editor.applyGroundPaint(third);assert.equal($('towerGroundRedo').disabled,true,'new ground edit invalidates redo');
for(const method of ['blocks','voxels']){$('blockMode').value=method;$('blockMode').onchange();assert.equal(draft.groundPaint,third);editor.applyGroundPaint(lawn);$('blockMode').value='tower';$('blockMode').onchange();assert.equal(draft.groundPaint,lawn);assert.equal($('towerGroundUndo').disabled,true,'switching method clears stale ground history');$('towerGroundUndo').onclick();assert.equal(draft.groundPaint,lawn);editor.applyGroundPaint(third);}
const unpainted=()=>{const next={...draft};delete next.groundPaint;return next;};draft=unpainted();editor.reset();for(let i=0;i<25;i++)editor.applyGroundPaint(String(i%7+1).repeat(100));for(let i=0;i<20;i++)$('towerGroundUndo').onclick();assert.equal(draft.groundPaint,'5'.repeat(100));assert.equal($('towerGroundUndo').disabled,true,'tower history is bounded to twenty edits');assert.equal(draft.floors,17);editor.reset();assert.equal($('towerGroundRedo').disabled,true);
console.log('PASS: tower/block/layer ground continuity, isolated parameter-safe history, stale-history reset, new-edit redo invalidation and twenty-edit limit.');
for(const method of ['tower','blocks','voxels']){
 draft={...defaultBuildingDesign(),...(method==='blocks'?{blocks:Array(100).fill(2)}:method==='voxels'?{voxels:Array(100).fill(3)}:{})};editor.reset();
 editor.applyPaintColors(['#123456']);assert.deepEqual(draft.paintColors,['#123456']);if(method==='tower')editor.applyGroundPaint('8'.repeat(100));else editor.applyFloorPaint('8'.repeat(12000));
 const undo=method==='tower'?'towerGroundUndo':method==='blocks'?'blockUndo':'voxelUndo',redo=method==='tower'?'towerGroundRedo':method==='blocks'?'blockRedo':'voxelRedo';
 $(undo).onclick();assert.equal(method==='tower'?draft.groundPaint:draft.surfacePaint,undefined);assert.deepEqual(draft.paintColors,['#123456']);$(undo).onclick();assert.equal(draft.paintColors,undefined,'second undo restores the palette before color selection');$(redo).onclick();$(redo).onclick();assert.deepEqual(draft.paintColors,['#123456']);assert.equal((method==='tower'?draft.groundPaint:draft.surfacePaint)[0],'8');
 assert.ok(editor.reservedPaintSlots().has(0),'used and remembered colors cannot be reassigned');
 if(method!=='tower'){$('blockMode').value='tower';$('blockMode').onchange();assert.ok(editor.reservedPaintSlots().has(0),'construction memory reserves the painted color');}
}
console.log('PASS: custom palette and paint undo/redo in all construction methods, palette removal and remembered-color reservation.');
draft={...defaultBuildingDesign(),blocks:Array(100).fill(2),paintColors:['#123456']};editor.reset();assert.match($('blockMaterial').innerHTML,/<option value="7">Solid paint #123456<\/option>/);$('blockTool').value='paint';$('blockSide').value='2';$('blockMaterial').value='7';editor.refresh();down(94);up();assert.equal(draft.materials[94*5+2],7);assert.equal(cells[94].textContent,'C');assert.equal(cells[94].style.background,'#123456');$('blockUndo').onclick();assert.equal(draft.materials,undefined);assert.deepEqual(draft.paintColors,['#123456']);
console.log('PASS: imported custom colors are selectable in the block-grid material menu, rendered on cells and retained through paint undo.');
