import assert from 'node:assert/strict';
import {createCity,validateSave,tick,recompute} from '../dist/engine.js';
import {serializeCity} from '../dist/save.js';
import {copyBuildingSet,applyBuildingSet,buildingSetChanges} from '../dist/building-sets.js';
import {defaultBuildingDesign} from '../dist/building-designs.js';
import {baseZonedSprite} from '../dist/building-art.js';
const source=createCity('Source'),target=createCity('Destination');
const tile=target.tiles.find(t=>t.type==='residential');tile.level=3;tile.density=3;recompute(target);const key=baseZonedSprite(tile,target.seed);
source.buildingReplacements={[key]:key===2?74:2,'6@3x3':54};
source.buildingDesigns={'5@2x2':{...defaultBuildingDesign('5@2x2'),name:'Copper offices',blocks:Array(100).fill(3)}};
target.buildingDesigns={0:defaultBuildingDesign(0)};
const savedSource=serializeCity(source),before=JSON.parse(serializeCity(target)),control=validateSave(before),changes=buildingSetChanges(target,source);
assert.ok(changes.some(c=>c.key===String(key)&&c.count>0));assert.ok(changes.some(c=>c.key==='0'&&c.to==='Detached homes'));assert.ok(changes.some(c=>c.key==='5@2x2'&&c.count===0));
applyBuildingSet(target,source);assert.deepEqual(copyBuildingSet(target),copyBuildingSet(source));assert.equal(serializeCity(source),savedSource);
const after=JSON.parse(serializeCity(target));delete before.buildingDesigns;delete before.buildingReplacements;delete after.buildingDesigns;delete after.buildingReplacements;assert.deepEqual(after,before,'only artwork changes');
target.buildingDesigns['5@2x2'].blocks[0]=4;assert.equal(source.buildingDesigns['5@2x2'].blocks[0],3,'no shared arrays');
const restored=validateSave(JSON.parse(serializeCity(target)));assert.deepEqual(copyBuildingSet(restored),copyBuildingSet(target));tick(target);tick(restored);tick(control);assert.deepEqual(target.stats,control.stats);assert.equal(serializeCity(target),serializeCity(restored),'same monthly continuation');
const valid=serializeCity(target);assert.throws(()=>applyBuildingSet(target,{buildingReplacements:{2:74},buildingDesigns:{5:{floors:999}}}));assert.equal(serializeCity(target),valid,'invalid model cannot partly apply replacement');
applyBuildingSet(target,{});assert.deepEqual(copyBuildingSet(target),{buildingDesigns:{},buildingReplacements:{}});assert.equal(buildingSetChanges(target,{}).length,0);
const legacy=JSON.parse(savedSource);legacy.version=57;delete legacy.buildingDesigns;delete legacy.buildingReplacements;applyBuildingSet(target,validateSave(legacy));assert.deepEqual(copyBuildingSet(target),{buildingDesigns:{},buildingReplacements:{}});
console.log('PASS: whole building-set import, footprint-aware change review, current/future styles, complete reset, deep copy, atomic rejection, legacy city import and exact appearance-only save/monthly continuation.');
