import assert from 'node:assert/strict';
import {buildingShapeCells,applyBuildingShape} from '../dist/building-shapes.js';
import {mountBuildingBlockEditor} from '../dist/building-block-editor.js';
import {defaultBuildingDesign,exportBuildingDesign,importBuildingDesign} from '../dist/building-designs.js';
assert.deepEqual(buildingShapeCells('line',11,15),[11,12,13,14,15]);assert.deepEqual(buildingShapeCells('line',11,44),[11,22,33,44]);assert.deepEqual(buildingShapeCells('plane',33,11),[11,12,13,21,22,23,31,32,33]);assert.equal(buildingShapeCells('plane',0,99).length,100);
for(let a=0;a<100;a++)for(let b=0;b<100;b++){const line=buildingShapeCells('line',a,b);assert.equal(line[0],a);assert.equal(line.at(-1),b);assert.equal(new Set(line).size,line.length);assert.ok(line.every(i=>i>=0&&i<100));for(let j=1;j<line.length;j++)assert.ok(Math.abs(line[j]%10-line[j-1]%10)<=1&&Math.abs(Math.floor(line[j]/10)-Math.floor(line[j-1]/10))<=1);}
for(const args of [['other',0,1],['line',-1,1],['plane',0,100]])assert.throws(()=>buildingShapeCells(...args));assert.throws(()=>applyBuildingShape(Array(100).fill(0),'line',0,1,25));
const controls=new Map(),make=()=>({value:'',style:{},disabled:false,setAttribute(){},focus(){},closest(){return this;}});for(const id of ['blockMode','blockWorkspace','blockUndo','blockRedo','blockTool','blockShape','blockSide','blockBrush','blockMaterial','blockStatus','blockFromTower','blockClear'])controls.set(id,make());
const cells=Array.from({length:100},(_,i)=>({...make(),dataset:{blockIndex:String(i)}})),grid={querySelectorAll:()=>cells,setPointerCapture(){},contains:c=>cells.includes(c)};controls.set('blockGrid',grid);controls.set('voxelEditor',{querySelector:s=>{const id=s.slice(1);if(!controls.has(id))controls.set(id,id==='voxelGrid'?{querySelectorAll:()=>[]}:make());return controls.get(id);}});globalThis.document={getElementById:()=>make(),elementFromPoint:x=>cells[x]};
const root={innerHTML:'',querySelector:s=>controls.get(s.slice(1))};let draft={...defaultBuildingDesign(),blocks:Array(100).fill(0),materials:Array(500).fill(1)},writes=0;draft.blocks[99]=4;const editor=mountBuildingBlockEditor(root,{get:()=>draft,set:d=>{draft=d;writes++;}}),$=id=>controls.get(id);
$('blockTool').value='height';$('blockShape').value='line';$('blockBrush').value='8';$('blockSide').value='4';editor.refresh();const before=structuredClone(draft);
const down=i=>grid.onpointerdown({button:0,target:cells[i],pointerId:1,preventDefault(){}}),move=i=>grid.onpointermove({pointerId:1,clientX:i,clientY:0}),up=(shiftKey=false)=>grid.onpointerup({pointerId:1,shiftKey});
down(11);move(15);assert.equal(writes,0,'preview does not change the draft');assert.equal(cells.filter(c=>c.style.boxShadow).length,5);up();assert.equal(writes,1);assert.deepEqual(draft.blocks.slice(11,16),[8,8,8,8,8]);const painted=structuredClone(draft);$('blockUndo').onclick();assert.deepEqual(draft,before,'whole gesture is one undo');$('blockRedo').onclick();assert.deepEqual(draft,painted,'redo includes surface materials');
$('blockShape').value='plane';down(22);move(44);up(true);assert.deepEqual(draft,painted,'Shift release cancels');down(22);move(44);grid.onpointercancel();assert.deepEqual(draft,painted,'pointer cancellation discards preview');
const key=(key,shiftKey=false)=>grid.onkeydown({key,shiftKey,target:cells[11],preventDefault(){}});down(11);up(true);key('Enter',true);key('ArrowDown');key('Enter');assert.equal(draft.blocks[21],8,'keyboard plane commits');$('blockUndo').onclick();assert.deepEqual(draft,painted);$('blockBrush').value='3';down(30);move(32);up();assert.equal($('blockRedo').disabled,true,'new editing discards redo');
$('blockBrush').value='0';down(30);move(32);up();assert.equal(draft.blocks[31],0,'shapes erase with zero height');assert.deepEqual(importBuildingDesign(exportBuildingDesign(draft)),draft,'existing portable format preserves constructed shapes');
console.log('PASS: line/plane geometry across the footprint, nonmutating previews, atomic undo/redo with materials, pointer and Shift cancellation, keyboard placement, redo invalidation, erase and portable design roundtrip.');
