import assert from 'node:assert/strict';
import {createCity,build,planBuild,selection,tick,recompute,validateSave,VERSION} from '../dist/engine.js';
import {serializeCity,TILE_FIELDS} from '../dist/save.js';
import {deriveBuildingLots} from '../dist/building-lots.js';
import {designateHistorical} from '../dist/historical.js';
import {ignite,stepFire,contaminate} from '../dist/emergency.js';
import {startToxicCloud,stepToxicCloud} from '../dist/toxic-cloud.js';
import {attachCustomScenario} from '../dist/custom-scenarios.js';
import {restartCustomScenario,decodeScenarioStart,captureScenarioStart} from '../dist/scenario-replay.js';
const point=t=>({x:t.x,y:t.y}),restore=c=>validateSave(JSON.parse(serializeCity(c)));
function cityWithLot(size=48){const c=createCity('Larger homes',false,size);c.seed=3;c.startYear=2050;c.funds=500000;for(const t of c.tiles){t.terrain='land';t.elevation=0;t.nature=false;}const put=(tool,x,y,xx=x,yy=y,density=1)=>assert.ok(build(c,tool,selection(tool,{x,y},{x:xx,y:yy}),density).ok);put('fusion',8,8);put('powerline',12,12,20,12);put('waterTower',14,13);put('waterTower',15,13);put('pipe',14,13,20,13);put('road',16,17,22,17);put('commercial',18,18,20,18);put('residential',18,14,20,16,3);tick(c);assert.equal(c.buildingLots.size,1);return c;}
const c=cityWithLot(),lot=[...c.buildingLots.values()][0],root=c.tiles[lot.root],corner=c.tiles[lot.ids.at(-1)];assert.equal(lot.width,3);assert.equal(lot.height,3);assert.equal(c.stats.population,72,'capacity is counted across nine members, never multiplied at the root');assert.ok(lot.ids.every(i=>c.tiles[i].level===1&&c.tiles[i].age===0));assert.deepEqual(deriveBuildingLots(c),c.buildingLots);
const loaded=restore(c);assert.deepEqual(loaded.buildingLots,c.buildingLots);for(let i=0;i<12;i++){tick(c);tick(loaded);assert.deepEqual(deriveBuildingLots(c),c.buildingLots);assert.equal(serializeCity(c),serializeCity(loaded));}
const outage=cityWithLot(),outageLot=[...outage.buildingLots.values()][0];assert.ok(build(outage,'bulldoze',[{x:8,y:8}]).ok);for(let i=0;i<4;i++)tick(outage);assert.ok(outageLot.ids.every(i=>outage.tiles[i].level===0&&outage.tiles[i].abandonedLevel===1),'four months without power abandon the entire building');restore(outage);assert.ok(build(outage,'fusion',[{x:8,y:8}]).ok);for(let i=0;i<36&&!outage.tiles[outageLot.root].level;i++)tick(outage);assert.ok(outageLot.ids.every(i=>outage.tiles[i].level>0&&outage.tiles[i].abandonedLevel===0),'restored supply permits coherent recovery');restore(outage);
const waterOutage=cityWithLot(),waterLot=[...waterOutage.buildingLots.values()][0];assert.ok(waterLot.ids.every(i=>waterOutage.tiles[i].waterEstablished));assert.ok(build(waterOutage,'removePipe',selection('removePipe',{x:14,y:13},{x:20,y:13})).ok);for(let i=0;i<4;i++)tick(waterOutage);assert.ok(waterLot.ids.every(i=>waterOutage.tiles[i].level===0&&waterOutage.tiles[i].abandonedLevel===1&&waterOutage.tiles[i].waterEstablished),'water loss abandons the whole previously supplied low-level lot');restore(waterOutage);
const demolish=cityWithLot(),whole=[...demolish.buildingLots.values()][0],member=demolish.tiles[whole.ids.at(-1)];assert.ok(designateHistorical(demolish,whole.ids.at(-1),true).ok);assert.ok(whole.ids.every(i=>demolish.tiles[i].historicalLevel===1));assert.equal(planBuild(demolish,'bulldoze',[point(demolish.tiles[whole.root])]).ok,false);assert.ok(designateHistorical(demolish,whole.root,false).ok);assert.equal(planBuild(demolish,'residential',[point(member)],2).ok,false);assert.ok(build(demolish,'pipe',[point(member)]).ok);const funds=demolish.funds,preview=planBuild(demolish,'bulldoze',whole.ids.map(i=>point(demolish.tiles[i])));assert.equal(preview.cost,1);assert.equal(preview.points.length,1);assert.equal(demolish.buildingLots.size,1);assert.ok(build(demolish,'bulldoze',whole.ids.map(i=>point(demolish.tiles[i]))).ok);assert.equal(demolish.funds,funds-1);assert.equal(demolish.buildingLots.size,0);assert.ok(whole.ids.every(i=>demolish.tiles[i].type==='residential'&&demolish.tiles[i].level===0&&demolish.tiles[i].lotRoot===null));assert.equal(member.pipe,true);
const fire=cityWithLot(),burn=[...fire.buildingLots.values()][0],target=fire.tiles[burn.ids.at(-1)];assert.ok(ignite(fire,target.x,target.y).ok);assert.equal(planBuild(fire,'bulldoze',[point(fire.tiles[burn.root])]).ok,false);assert.equal(designateHistorical(fire,burn.root,true).ok,false);target.fire=99;target.fireAge=100;stepFire(fire);recompute(fire);assert.equal(fire.buildingLots.size,0);assert.equal(fire.emergency.destroyed,1);assert.equal(fire.emergency.displaced,72);assert.ok(burn.ids.every(i=>fire.tiles[i].rubble));restore(fire);
const toxic=cityWithLot(),evacuated=[...toxic.buildingLots.values()][0];startToxicCloud(toxic,20,16);stepToxicCloud(toxic);recompute(toxic);assert.equal(toxic.buildingLots.size,1);assert.ok(evacuated.ids.every(i=>toxic.tiles[i].level===0&&toxic.tiles[i].abandonedLevel===1));assert.equal(toxic.emergency.displaced,72);restore(toxic);
const radiation=cityWithLot();contaminate(radiation,24,16);recompute(radiation);assert.equal(radiation.buildingLots.size,0);assert.equal(radiation.emergency.destroyed,1);assert.equal(radiation.emergency.displaced,72);restore(radiation);
const challenge=cityWithLot();attachCustomScenario(challenge,{title:'Preserve the new block',months:24,objectives:[{metric:'population',target:999999}]});const start=serializeCity({...challenge,scenario:null});tick(challenge);const replay=restartCustomScenario(restore(challenge));assert.equal(serializeCity({...replay,scenario:null}),start);assert.equal(replay.buildingLots.size,1);
const legacy=createCity(),old=JSON.parse(serializeCity(legacy));old.version=108;for(const t of old.tiles)delete t.lotRoot;assert.equal(validateSave(old).version,VERSION);const snapshot=captureScenarioStart(legacy);snapshot.city.version=108;const k=snapshot.keys.indexOf('lotRoot');snapshot.keys.splice(k,1);for(const row of snapshot.tiles)row.splice(k,1);assert.equal(decodeScenarioStart(snapshot,legacy.month).buildingLots.size,0);assert.ok(TILE_FIELDS.includes('lotRoot'));
for(const change of [{lotRoot:null},{level:2},{age:3},{density:2}]){const bad=JSON.parse(serializeCity(cityWithLot()));Object.assign(bad.tiles[lot.ids.at(-1)],change);assert.throws(()=>validateSave(bad));}
// Run the actual worker handler with structured-cloned input and output.
const workerCity=cityWithLot(96),workerBefore=serializeCity(workerCity),direct=structuredClone(workerCity);let response;globalThis.self={postMessage:value=>{response=structuredClone(value);}};await import('../dist/simulation-worker.js');self.onmessage({data:{id:19,city:structuredClone(workerCity)}});assert.equal(response.id,19);assert.equal(response.error,undefined);tick(direct);assert.equal(serializeCity(response.city),serializeCity(direct));assert.ok(response.city.buildingLots instanceof Map);assert.equal(serializeCity(workerCity),workerBefore);
console.log('PASS: real 3×3 growth, distributed population, synchronized monthly lifecycle, strict save/legacy/replay, whole historical designation/demolition and exact fire/toxic/radiation displacement.');
