import assert from 'node:assert/strict';
import {mountBuildingVoxelEditor} from '../dist/building-voxel-editor.js';
import {defaultBuildingDesign} from '../dist/building-designs.js';
const controls=new Map(),make=()=>({value:'',style:{},attrs:{},setAttribute(k,v){this.attrs[k]=v;},focus(){},closest(){return this;}}),cells=Array.from({length:100},(_,i)=>({...make(),dataset:{voxelIndex:String(i)}})),grid={dataset:{},setAttribute(){},querySelectorAll:()=>cells,setPointerCapture(){},contains:c=>cells.includes(c)};Object.defineProperty(grid,'innerHTML',{set(value){const count=(value.match(/data-voxel-index/g)||[]).length;cells.splice(0,cells.length,...Array.from({length:count},(_,i)=>({...make(),dataset:{voxelIndex:String(i)}})));}});controls.set('voxelGrid',grid);const root={innerHTML:'',querySelector:s=>{const id=s.slice(1);if(!controls.has(id))controls.set(id,make());return controls.get(id);}},$=id=>controls.get(id);globalThis.document={elementFromPoint:x=>cells[x]};let draft={...defaultBuildingDesign(),voxels:Array(100).fill(0)},writes=0,views=0;draft.voxels[99]=1;const editor=mountBuildingVoxelEditor(root,{get:()=>draft,view:()=>{views++;},set:d=>{draft=d;writes++;}});$('voxelLevel').value='3';$('voxelAction').value='place';$('voxelShape').value='plane';editor.refresh();
const down=i=>grid.onpointerdown({button:0,target:cells[i],pointerId:7,preventDefault(){}}),move=i=>grid.onpointermove({pointerId:7,clientX:i,clientY:0}),up=(shiftKey=false)=>grid.onpointerup({pointerId:7,shiftKey});
down(11);move(23);assert.equal(writes,0);assert.ok(views>0);assert.deepEqual(editor.selection(),{plane:'horizontal',slice:2,pending:{kind:'plane',start:11,end:23}});assert.equal(cells.filter(c=>c.style.boxShadow).length,6);up();assert.equal(editor.selection().pending,null);assert.equal(writes,1);assert.equal(draft.voxels[12],4);assert.match(cells[12].attrs['aria-label'],/layer 3: occupied/);$('voxelUndo').onclick();assert.equal(draft.voxels[12],0);$('voxelRedo').onclick();assert.equal(draft.voxels[12],4);
$('voxelLevel').value='2';$('voxelLevel').oninput();assert.match(cells[12].attrs['aria-label'],/layer 2: empty/,'typing updates the layer immediately');down(11);move(23);grid.onpointercancel();assert.equal(draft.voxels[12],4);down(11);move(23);up(true);assert.equal(draft.voxels[12],4);down(11);move(23);up();assert.equal(draft.voxels[12],6);
$('voxelAction').value='erase';$('voxelAction').onchange();down(11);move(23);up();assert.equal(draft.voxels[12],4,'erasing lower layer retains overhang');$('voxelUndo').onclick();assert.equal(draft.voxels[12],6);$('voxelLevel').value='4';$('voxelLevel').oninput();$('voxelAction').value='place';down(30);up();assert.equal($('voxelRedo').disabled,true,'new edit invalidates redo');
const before=JSON.stringify(draft);$('voxelLevel').value='25';$('voxelLevel').oninput();down(11);up();assert.equal(JSON.stringify(draft),before);assert.match($('voxelStatus').textContent,/1 to 24/);
$('voxelPlane').value='xz';$('voxelPlane').onchange();assert.equal($('voxelLevel').value,'10','orientation change clamps the slice');$('voxelLevel').value='2';$('voxelLevel').oninput();assert.equal(cells.length,240);assert.match(cells[0].attrs['aria-label'],/row 2, layer 24/);assert.match(cells[239].attrs['aria-label'],/row 2, layer 1/);down(230);move(5);up();assert.equal(draft.voxels[10],0xffffff,'vertical drag spans all heights');$('voxelUndo').onclick();assert.equal(draft.voxels[10],0);$('voxelPlane').value='horizontal';$('voxelPlane').onchange();assert.equal(cells.length,100);
const geometryBefore=[...draft.voxels],paint=Array(500).fill(0);paint[12]=2;editor.applyMaterials(paint);assert.equal(draft.materials[12],2);assert.deepEqual(draft.voxels,geometryBefore);$('voxelUndo').onclick();assert.equal(draft.materials,undefined);assert.deepEqual(draft.voxels,geometryBefore);$('voxelRedo').onclick();assert.equal(draft.materials[12],2);
console.log('PASS: layered editor previews, independent-plane placement/erasure, undo/redo, immediate layer refresh, pointer and Shift cancellation, invalid input and redo invalidation.');

const floorPaint='0'.repeat(100)+'4'+'0'.repeat(11899),beforeFloorPaint=JSON.stringify(draft);editor.applyFloorPaint(floorPaint);assert.equal(draft.surfacePaint,floorPaint);$('voxelUndo').onclick();assert.equal(JSON.stringify(draft),beforeFloorPaint);$('voxelRedo').onclick();assert.equal(draft.surfacePaint,floorPaint);
