import {connectedBuildingSurfaces} from '../dist/building-surface-fill.js';
import assert from 'node:assert/strict';
import {setBlockGeometry,validateBlockGeometry,blockCornerHeights} from '../dist/building-block-geometry.js';
import {buildingVoxelFaces} from '../dist/building-voxels.js';
import {defaultBuildingDesign,validateBuildingDesign,exportBuildingDesign,importBuildingDesign} from '../dist/building-designs.js';
import {projectedBuildingSurfaces,pickBuildingSurface} from '../dist/building-surface-picking.js';
import {createCity,validateSave} from '../dist/engine.js';
import {serializeCity} from '../dist/save.js';
const voxels=Array(100).fill(0);voxels[44]=1;let geometry=setBlockGeometry(undefined,[{x:4,y:4,z:0}],1,voxels);assert.equal(validateBlockGeometry(geometry,voxels),geometry);assert.equal(geometry.length,2400);
const design={...defaultBuildingDesign(2),voxels,blockGeometry:geometry};assert.deepEqual(importBuildingDesign(exportBuildingDesign(design)),validateBuildingDesign(design));assert.equal(JSON.parse(exportBuildingDesign(design)).version,8);
for(let shape=1;shape<=4;shape++){geometry=setBlockGeometry(undefined,[{x:4,y:4,z:0}],shape,voxels);assert.equal(blockCornerHeights(shape).reduce((a,b)=>a+b),2);for(let rot=0;rot<4;rot++){const faces=buildingVoxelFaces(voxels,rot,undefined,geometry),roof=faces.find(f=>f.side===4);if(roof)assert.equal(new Set(roof.points.map(p=>p[2])).size,2);assert.ok(faces.every(f=>f.points.every(p=>p.every(Number.isFinite))));assert.ok(faces.length>=2);const surfaces=projectedBuildingSurfaces({...design,blockGeometry:geometry},rot);assert.ok(surfaces.some(f=>f.shape===shape));if(roof){const roofSurface=surfaces.find(f=>f.side===4),area=roofSurface.polygon.reduce((sum,p,k)=>{const q=roofSurface.polygon[(k+1)%4];return sum+p[0]*q[1]-q[0]*p[1];},0);assert.ok(area>0);}}}
const adjacent=[...voxels];adjacent[45]=1;const faces=buildingVoxelFaces(adjacent,2,undefined,geometry);assert.ok(faces.some(f=>f.x===5&&f.y===4&&f.side===3),'cube wall beside a partial wedge is not fully culled');
const city=createCity();city.buildingDesigns[2]=design;const loaded=validateSave(JSON.parse(serializeCity(city)));assert.equal(loaded.buildingDesigns[2].blockGeometry,design.blockGeometry);const old=JSON.parse(serializeCity(city));old.version=124;assert.throws(()=>validateSave(old),/Shaped blocks/);delete old.buildingDesigns[2].blockGeometry;assert.equal(validateSave(old).version,153);
assert.throws(()=>validateBlockGeometry('0'.repeat(2399),voxels));assert.throws(()=>validateBlockGeometry('5'+'0'.repeat(2399),voxels));assert.throws(()=>validateBlockGeometry('1'+'0'.repeat(2399),voxels));assert.equal(setBlockGeometry(design.blockGeometry,[{x:4,y:4,z:0}],0,voxels),undefined);assert.equal(setBlockGeometry(design.blockGeometry,[],0,Array(100).fill(0)),undefined);
const roofVoxels=[...voxels];roofVoxels[45]=roofVoxels[54]=1;const roofGeometry=setBlockGeometry(undefined,[{x:4,y:4,z:0},{x:5,y:4,z:0},{x:4,y:5,z:0}],1,roofVoxels),roofDesign={...design,voxels:roofVoxels,blockGeometry:roofGeometry},surfaces=projectedBuildingSurfaces(roofDesign),roof=surfaces.find(f=>f.x===4&&f.y===4&&f.side===4);assert.equal(connectedBuildingSurfaces(roofDesign,surfaces,roof).length,2,'fill stops at non-coplanar wedge step');const center={x:roof.polygon.reduce((s,p)=>s+p[0],0)/4,y:roof.polygon.reduce((s,p)=>s+p[1],0)/4};assert.equal(pickBuildingSurface(surfaces,center)?.shape,1);
const maximal={...design,voxels:Array(100).fill(0xffffff),blockGeometry:'1'.repeat(2400),materials:Array(500).fill(4),surfacePaint:'5'.repeat(12000),surfaceDetails:'3'.repeat(12000)};const file=exportBuildingDesign(maximal);assert.ok(file.length<32768);assert.deepEqual(importBuildingDesign(file),validateBuildingDesign(maximal));
console.log('PASS: wedge geometry in four orientations/views, sloped surface projection, adjacent cube visibility, bounded validation, format-eight roundtrip and city schema migration.');
