import assert from 'node:assert/strict';
import {createCity} from '../dist/engine.js';
import {CityRenderer} from '../dist/renderer.js';
import {localSoundscape,createCityAmbience,showAmbienceSettings} from '../dist/city-ambience.js';
const c=createCity('Local audio',false);for(const t of c.tiles){t.terrain='land';t.nature=false;t.elevation=0;}
const at=(x,y)=>c.tiles[y*48+x];Object.assign(at(22,20),{type:'road',traffic:40});Object.assign(at(22,21),{type:'industrial',level:1,powered:true});at(19,21).nature=true;at(19,22).terrain='water';Object.assign(at(40,40),{type:'road',traffic:1000});
const r=Object.create(CityRenderer.prototype);Object.assign(r,{getCity:()=>c,w:800,h:600,zoom:2.25,rotation:0,layer:'city',pan:{x:0,y:0}});
function center(x,y){const p=r.project(x,y);r.pan.x+=r.w/2-p.x;r.pan.y+=r.h/2-p.y-r.unit/2;}
center(20,20);const before=JSON.stringify(c),mix=localSoundscape(c,r);for(const v of Object.values(mix)){assert.ok(v.gain>0&&v.gain<=1);assert.ok(v.pan>=-1&&v.pan<=1);}assert.ok(mix.traffic.pan>0);r.rotation=2;center(20,20);assert.ok(localSoundscape(c,r).traffic.pan<0,'camera rotation reverses projected stereo placement');
center(5,5);assert.ok(Object.values(localSoundscape(c,r)).every(v=>v.gain===0),'distant traffic cannot fill an empty neighborhood');center(20,20);r.zoom=1;assert.ok(Object.values(localSoundscape(c,r)).every(v=>v.gain===0));r.zoom=2.25;center(20,20);
for(const change of ['paused','emergency','data']){c.emergency.active=change==='emergency';r.layer=change==='data'?'power':'city';assert.ok(Object.values(localSoundscape(c,r,change!=='paused')).every(v=>v.gain===0));}c.emergency.active=false;r.layer='city';assert.equal(JSON.stringify(c),before,'soundscape sampling does not mutate the city');
const stored=new Map(),events={},timers=new Map(),contexts=[];let timerId=0;
globalThis.localStorage={getItem:k=>stored.get(k)||null,setItem:(k,v)=>stored.set(k,v)};globalThis.document={hidden:false,addEventListener:(k,fn)=>(events[k]??=[]).push(fn)};globalThis.setInterval=fn=>{timers.set(++timerId,fn);return timerId;};globalThis.clearInterval=id=>timers.delete(id);
const param=()=>({value:0,cancelScheduledValues(){},setTargetAtTime(v){assert.ok(Number.isFinite(v));this.value=v;}});
class Context{constructor(){contexts.push(this);this.state='suspended';this.currentTime=0;this.sampleRate=8000;this.destination={};this.sources=[];this.gains=[];}createGain(){const g={gain:param(),connect(){},disconnect(){}};this.gains.push(g);return g;}createStereoPanner(){return{pan:param(),connect(){},disconnect(){}};}createBiquadFilter(){return{frequency:param(),Q:param(),connect(){},disconnect(){}};}createBuffer(ch,length){return{getChannelData:()=>new Float32Array(length)};}createBufferSource(){const s={playbackRate:param(),connect(){},disconnect(){this.disconnected=true;},start(){this.started=true;},stop(){this.stopped=true;}};this.sources.push(s);return s;}async resume(){this.state='running';}}
globalThis.window={AudioContext:Context};let running=true;const ambience=createCityAmbience();ambience.setSceneReader(()=>({city:c,renderer:r,running}));assert.equal(contexts.length,0);await ambience.enable(true);assert.equal(contexts.length,1);assert.equal(contexts[0].sources.length,4);assert.equal(timers.size,1);assert.ok(contexts[0].sources.every(s=>s.loop&&s.started));
ambience.volume(60);assert.equal(contexts[0].gains[0].gain.value,.6*.18);assert.equal(JSON.parse(stored.get('sims3000-ambience')).volume,60);
running=false;for(const fn of timers.values())fn();assert.ok(contexts[0].gains.slice(1).every(g=>g.gain.value===0));running=true;
document.hidden=true;for(const fn of events.visibilitychange)fn();assert.equal(timers.size,0);assert.ok(contexts[0].sources.every(s=>s.stopped&&s.disconnected));document.hidden=false;for(const fn of events.visibilitychange)fn();await Promise.resolve();assert.equal(timers.size,1);assert.equal(contexts[0].sources.length,8);
await ambience.enable(false);assert.equal(timers.size,0);const pending=[];contexts[0].state='suspended';contexts[0].resume=()=>new Promise(resolve=>pending.push(resolve));const enabling=ambience.enable(true);await ambience.enable(false);pending[0]();await enabling;assert.equal(timers.size,0,'mute during asynchronous unlock cannot restart ambience');
contexts[0].state='running';const controls={ambientEnabled:{},ambientVolume:{},ambientLevel:{}},container={innerHTML:'',querySelector:s=>controls[s.slice(1)]},notifications=[];showAmbienceSettings(ambience,container,m=>notifications.push(m));assert.match(container.innerHTML,/zoom above 100%/);await controls.ambientEnabled.onchange({target:{checked:true}});assert.equal(timers.size,1);controls.ambientVolume.oninput({target:{value:'44'}});assert.equal(controls.ambientLevel.textContent,'44%');await controls.ambientEnabled.onchange({target:{checked:false}});assert.equal(timers.size,0);assert.deepEqual(notifications,[]);
const restored=createCityAmbience();assert.deepEqual(restored.settings,{enabled:false,volume:44});assert.equal(contexts.length,1);console.log('PASS: actual camera-local mix and stereo rotation, zoom/distance/operating gates, immutable city, lazy audio allocation, bounded loop beds, hidden-tab cleanup, async mute, persistence and settings handlers.');
