import assert from 'node:assert/strict';
import {createCity,tick,validateSave,build} from '../dist/engine.js';
import {serializeCity} from '../dist/save.js';
import {freshDemographics,advanceDemographics,populationCensus,censusReport,validateDemographics} from '../dist/demographics.js';
const sum=a=>a.reduce((s,n)=>s+n,0),fixture=health=>({month:0,stats:{population:10000,lifeExpectancy:health},demographics:freshDemographics(10000,0)});
const c=fixture(59),initial=[...c.demographics.cohorts];for(let i=1;i<=120;i++){c.month=i;advanceDemographics(c);const f=c.demographics.flows;assert.ok(Math.abs(f.startPopulation+f.births-f.deaths+f.arrivals-f.departures-f.endPopulation)<1e-6);assert.ok(Math.abs(sum(c.demographics.cohorts)-10000)<1e-6);assert.equal(sum(populationCensus(c).rows.map(r=>r.people)),10000);}
assert.notDeepEqual(c.demographics.cohorts,initial,'age distribution evolves');assert.ok(c.demographics.flows.births>0&&c.demographics.flows.deaths>0);assert.deepEqual(validateDemographics(c.demographics,c.month),c.demographics);
const low=fixture(45),high=fixture(90);low.month=high.month=1;advanceDemographics(low);advanceDemographics(high);assert.ok(high.demographics.flows.deaths<low.demographics.flows.deaths);
const frozen=JSON.stringify(c.demographics);c.stats.population=2500;const projected=populationCensus(c);assert.equal(sum(projected.rows.map(r=>r.people)),2500);assert.equal(JSON.stringify(c.demographics),frozen,'viewing a housing change does not mutate history');c.month++;advanceDemographics(c);assert.ok(c.demographics.flows.departures>7000);c.stats.population=0;c.month++;advanceDemographics(c);assert.deepEqual(populationCensus(c).rows.map(r=>r.people),Array(8).fill(0));
let live=createCity();for(let i=0;i<8;i++)tick(live);const saved=validateSave(JSON.parse(serializeCity(live)));assert.deepEqual(saved.demographics,live.demographics);for(let i=0;i<12;i++){tick(live);tick(saved);}assert.deepEqual(saved.demographics,live.demographics);assert.match(censusReport(live),/75\+/);assert.equal((censusReport(live).match(/<meter /g)||[]).length,8);
const legacy=JSON.parse(serializeCity(live));legacy.version=71;delete legacy.demographics;const migrated=validateSave(legacy);assert.equal(migrated.demographics.flows,null);assert.ok(Math.abs(sum(migrated.demographics.cohorts)-migrated.stats.population)<1e-6);
for(const edit of [d=>d.cohorts.pop(),d=>d.cohorts[0]=-1,d=>d.month=999,d=>d.flows.deaths=-1,d=>d.flows.endPopulation++]){const bad=JSON.parse(serializeCity(live));edit(bad.demographics);assert.throws(()=>validateSave(bad));}
console.log('PASS: persistent age distribution, balanced monthly births/deaths/migration, health mortality effect, housing reconciliation, read-only census, saved continuation and legacy/invalid data handling.');
