import assert from 'node:assert/strict';
import {createCity,recompute,tick,validateSave,VERSION} from '../dist/engine.js';
import {startEarthquake,stepFire} from '../dist/emergency.js';
import {validateQuakeMagnitude,quakeBands,quakeDamageChance} from '../dist/earthquake-settings.js';
import {attachCustomScenario} from '../dist/custom-scenarios.js';
import {scenarioEventReport} from '../dist/scenario-events.js';
import {serializeCity} from '../dist/save.js';
const base=()=>{const c=createCity('Quake strength',false);for(const t of c.tiles)Object.assign(t,{terrain:'land',nature:false,elevation:0,type:'road',pipe:true});recompute(c);return c;};
for(const v of [0,101,1.2,NaN,null,'50']){assert.throws(()=>validateQuakeMagnitude(v));const c=base(),before=serializeCity(c);assert.equal(startEarthquake(c,24,24,v).ok,false);assert.equal(serializeCity(c),before);}
assert.equal(validateQuakeMagnitude(),50);for(let d=0;d<=8;d+=.125)assert.equal(quakeDamageChance(d,50),1-d*.1);
const losses=[];for(const magnitude of [1,25,50,100]){const c=base();assert.ok(startEarthquake(c,24,24,magnitude).ok);let steps=0;while(c.emergency.active){stepFire(c);recompute(c);steps++;assert.ok(steps<=16);}assert.equal(steps,quakeBands(magnitude));assert.equal(c.month,0);for(const t of c.tiles)if(Math.hypot(t.x-24,t.y-24)>quakeBands(magnitude))assert.equal(t.type,'road');losses.push(c.emergency.infrastructureLost);assert.doesNotThrow(()=>validateSave(JSON.parse(serializeCity(c))));}for(let i=1;i<losses.length;i++)assert.ok(losses[i]>losses[i-1],JSON.stringify(losses));
const c=base();startEarthquake(c,24,24,100);for(let i=0;i<12;i++){stepFire(c);recompute(c);}assert.equal(c.emergency.earthquake.ring,12);const loaded=validateSave(JSON.parse(serializeCity(c)));assert.equal(loaded.emergency.earthquake.magnitude,100);while(c.emergency.active){stepFire(c);recompute(c);stepFire(loaded);recompute(loaded);}assert.deepEqual(JSON.parse(serializeCity(c)),JSON.parse(serializeCity(loaded)));
const old=base();startEarthquake(old,24,24);stepFire(old);recompute(old);const legacy=JSON.parse(serializeCity(old));legacy.version=114;delete legacy.emergency.earthquake.magnitude;const migrated=validateSave(legacy);assert.equal(migrated.version,VERSION);assert.equal(migrated.emergency.earthquake.magnitude,50);assert.deepEqual(migrated.emergency,old.emergency);
for(const magnitude of [undefined,0,101,2.5]){const bad=JSON.parse(serializeCity(old));bad.emergency.earthquake.magnitude=magnitude;assert.throws(()=>validateSave(bad));}
const scheduled=base();attachCustomScenario(scheduled,{title:'Light quake drill',months:12,objectives:[{metric:'funds',target:0}],events:[{type:'earthquake',month:1,x:24,y:24,magnitude:1}]});tick(scheduled);assert.equal(scheduled.emergency.earthquake.magnitude,1);assert.equal(scheduled.scenario.status,'playing');assert.match(scenarioEventReport(scheduled),/Magnitude 1/);stepFire(scheduled);recompute(scheduled);tick(scheduled);assert.equal(scheduled.scenario.status,'won');
const routine=base();attachCustomScenario(routine,{title:'Major quake drill',months:12,objectives:[{metric:'variable1',target:1}],programs:[{name:'Quake then inspect',steps:[{kind:'action',action:{type:'earthquake',x:24,y:24,magnitude:100}},{kind:'action',action:{type:'variable',variable:0,operation:'set',value:1}}]}],events:[{type:'program',routine:0,month:1}]});tick(routine);assert.equal(routine.scenario.variables[0],0);assert.equal(routine.emergency.earthquake.magnitude,100);let restored=validateSave(JSON.parse(serializeCity(routine)));while(restored.emergency.active){stepFire(restored);recompute(restored);}tick(restored);assert.equal(restored.scenario.variables[0],1);assert.equal(restored.scenario.status,'won');assert.doesNotThrow(()=>validateSave(JSON.parse(serializeCity(restored))));
console.log('PASS: 1–100 earthquake magnitude, strictly increasing seeded damage and radius, unchanged default formula, 16-step saved continuation, strict schema115 and schema114 migration, scheduled victory holds and resumed routine actions.');
