import assert from 'node:assert/strict';
import {createCity,build,idx,recompute,selection,validateSave} from '../dist/engine.js';
import {startEarthquake,stepFire,dispatchFire,setRandomEarthquakes,maybeEarthquake} from '../dist/emergency.js';
import {serializeCity} from '../dist/save.js';
function base(){const c=createCity('Quake recovery',false);for(const t of c.tiles){t.terrain='land';t.nature=false;t.treeLevel=0;}recompute(c);return c;}
const c=base(),center=c.tiles[idx(20,20)];Object.assign(center,{type:'road',pipe:true,rail:true,subway:true,highway:true});recompute(c);
assert.equal(startEarthquake(c,-1,20).ok,false);assert.equal(startEarthquake(c,20,20).ok,true);assert.equal(startEarthquake(c,21,20).ok,false);assert.equal(setRandomEarthquakes(c,true).ok,false);
const month=c.month,funds=c.funds;stepFire(c);recompute(c);assert.equal(center.type,null);assert.equal(center.rubble,true);for(const k of ['pipe','rail','subway','highway'])assert.equal(center[k],false);assert.equal(c.emergency.infrastructureLost,5);assert.equal(c.month,month);assert.equal(c.funds,funds);assert.ok(c.emergency.active,'empty quake continues through all damage bands');
const saved=validateSave(JSON.parse(serializeCity(c)));assert.deepEqual(saved.emergency,c.emergency);for(let k=0;k<7;k++){stepFire(c);recompute(c);stepFire(saved);recompute(saved);}assert.equal(c.emergency.active,false);assert.equal(c.emergency.contained,1);assert.deepEqual(JSON.parse(serializeCity(c)),JSON.parse(serializeCity(saved)),'reloading continues identically without replaying processed rings');assert.ok(build(c,'bulldoze',[center]).ok);assert.ok(build(c,'road',[center]).ok);assert.ok(build(c,'pipe',[center]).ok);
const plant=base();assert.ok(build(plant,'coal',[{x:20,y:20}]).ok);startEarthquake(plant,20,20);stepFire(plant);recompute(plant);assert.equal(plant.tiles.filter(t=>t.type==='coal').length,0);assert.equal(plant.emergency.destroyed,1);assert.equal(plant.tiles.filter(t=>t.rubble).length,16);assert.ok(validateSave(JSON.parse(serializeCity(plant))));
const homes=base();for(let y=12;y<=28;y++)for(let x=12;x<=28;x++)Object.assign(homes.tiles[idx(x,y)],{type:'residential',level:1});recompute(homes);startEarthquake(homes,20,20);let fires=0;for(let k=0;k<8;k++){stepFire(homes);recompute(homes);fires+=homes.stats.burningTiles;}assert.ok(fires>0,'quake ignites secondary fires');assert.ok(homes.emergency.displaced>0);assert.equal(homes.tiles[idx(12,12)].level,1,'buildings outside quake radius survive');assert.ok(dispatchFire(homes,20,21).ok);for(let k=0;k<300&&homes.emergency.active;k++){stepFire(homes);recompute(homes);}assert.equal(homes.emergency.active,false);assert.equal(homes.emergency.contained,1,'quake and fires form one emergency');assert.ok(validateSave(JSON.parse(serializeCity(homes))));
for(const mode of ['road','rail','highway']){const tunnel=base();for(let x=20;x<=27;x++)tunnel.tiles[idx(x,20)].elevation=Math.min(x-19,28-x,3);assert.ok(build(tunnel,mode,selection(mode,{x:19,y:20},{x:28,y:20})).ok);startEarthquake(tunnel,23,20);stepFire(tunnel);recompute(tunnel);assert.equal(tunnel.tunnels.length,0,'interior damage closes tunnel');assert.ok(validateSave(JSON.parse(serializeCity(tunnel))));}
const legacy=JSON.parse(serializeCity(base()));legacy.version=21;for(const key of ['earthquake','randomEarthquakes','quakes','infrastructureLost'])delete legacy.emergency[key];assert.equal(validateSave(legacy).emergency.earthquake,null);assert.equal(validateSave(legacy).emergency.randomEarthquakes,false);
const invalid=JSON.parse(serializeCity(saved));invalid.emergency.earthquake={x:20,y:20,ring:8};invalid.emergency.active=true;assert.throws(()=>validateSave(invalid),/earthquake/);
const random=base();for(let i=0;i<1000;i++){random.month=i;assert.equal(maybeEarthquake(random),false);}assert.ok(setRandomEarthquakes(random,true).ok);let fired=false;for(let i=0;i<5000&&!fired;i++){random.month=i;fired=maybeEarthquake(random);}assert.ok(fired);
console.log('PASS: staged earthquakes, interrupted-save continuity, infrastructure damage and repair, whole-building destruction, displacement, secondary fires, tunnel collapse, radius bounds, legacy saves and optional random events.');
