import assert from 'node:assert/strict';
import {VERSION,createCity,recompute,tick,borrow,applyBudget,validateSave,build,idx} from '../dist/engine.js';
import {freshFinance,settleLoans,loanPaymentsBetween,budgetForecast,recomputeEnvironment,taxRevenue,landDensityLimit} from '../dist/economy.js';
import {recomputeWater} from '../dist/utilities.js';
const c=createCity();const initial={income:c.stats.income,demand:c.stats.demand.residential};assert.ok(applyBudget(c,{residential:14,commercial:7,industrial:7},100).ok);assert.ok(c.stats.income>initial.income,'higher residential taxes yield more revenue at fixed population');assert.ok(c.stats.demand.residential<initial.demand,'higher residential taxes reduce demand');assert.ok(applyBudget(c,{residential:0,commercial:0,industrial:0},100).ok);assert.equal(c.stats.income,0);assert.ok(c.stats.balance<0,'zero taxes still incur upkeep');const state=JSON.stringify(c);assert.equal(applyBudget(c,{residential:-1,commercial:7,industrial:7},100).ok,false);assert.equal(JSON.stringify(c),state,'invalid changes are atomic');
const loanCity=createCity('Loans',false),before=loanCity.funds;assert.equal(borrow(loanCity,7000).ok,false);assert.equal(loanCity.funds,before);assert.ok(borrow(loanCity,5000).ok);assert.equal(loanCity.funds,before+5000);assert.equal(loanPaymentsBetween(loanCity,0,11),0);assert.equal(loanPaymentsBetween(loanCity,0,12),750);for(let month=1;month<=120;month++){loanCity.month=month;const paid=settleLoans(loanCity);assert.equal(paid,month%12===0?750:0,'payments occur exactly annually');}assert.equal(loanCity.finance.totalLoanPaid,7500);assert.equal(loanCity.funds,before-2500);assert.equal(loanCity.finance.loans.length,0,'loan matures after tenth payment');
for(let i=0;i<10;i++)assert.ok(borrow(loanCity,25000).ok);const cash=loanCity.funds;assert.equal(borrow(loanCity,5000).ok,false);assert.equal(loanCity.funds,cash);assert.equal(loanCity.finance.loans.length,10);assert.equal(loanPaymentsBetween(loanCity,120,132),37500);assert.equal(loanPaymentsBetween(loanCity,120,240),375000);
const dates=createCity('Dates',false);dates.month=5;borrow(dates,10000);const b=budgetForecast(dates);assert.equal(b.monthsLeft,7);assert.equal(b.yearDebtDue,0,'next anniversary after current year is excluded');assert.equal(b.nextYearDebtDue,1500);dates.month=16;assert.equal(loanPaymentsBetween(dates,16,17),1500);dates.month=17;settleLoans(dates);recompute(dates);assert.equal(dates.finance.loans[0].paymentsMade,1);
const roads=createCity();applyBudget(roads,{residential:7,commercial:7,industrial:7},0);const noFunding=roads.stats.spending.roads;assert.equal(noFunding,0);for(let i=0;i<17;i++)tick(roads);assert.ok(roads.finance.roadCondition<=20);assert.equal(roads.tiles.some(t=>t.type==='residential'&&t.access),false);applyBudget(roads,{residential:7,commercial:7,industrial:7},100);for(let i=0;i<25;i++)tick(roads);assert.equal(roads.finance.roadCondition,100);assert.ok(roads.tiles.some(t=>t.type==='residential'&&t.access));
const env=createCity('Environment',false);for(const t of env.tiles){t.terrain='land';t.nature=false;}const home=env.tiles[idx(24,24)];home.type='residential';home.level=3;home.density=3;recompute(env);const cleanValue=home.landValue,cleanTax=taxRevenue(env).residential;assert.ok(build(env,'park',[{x:25,y:24}]).ok);assert.ok(home.landValue>cleanValue);assert.ok(taxRevenue(env).residential>cleanTax,'higher land values raise the tax base');const parkValue=home.landValue;assert.ok(build(env,'coal',[{x:26,y:26}]).ok);assert.ok(home.landValue<parkValue);assert.ok(home.airPollution>0);assert.ok(home.waterPollution>0);assert.equal(landDensityLimit({type:'residential',landValue:30}),1);assert.equal(landDensityLimit({type:'residential',landValue:60}),2);assert.equal(landDensityLimit({type:'residential',landValue:85}),3);
const pump=env.tiles[idx(25,25)];pump.type='pump';pump.powered=true;env.tiles[idx(24,25)].terrain='water';recomputeEnvironment(env);recomputeWater(env);assert.ok(pump.pumpCapacity>0&&pump.pumpCapacity<500,'water pollution reduces pump output');pump.waterPollution=0;recomputeWater(env);assert.equal(pump.pumpCapacity,500,'clean pump supplies full output');
const accounting=createCity();borrow(accounting,5000);for(let month=0;month<13;month++){const funds=accounting.funds,income=accounting.stats.income,expenses=accounting.stats.expenses;const result=tick(accounting);assert.equal(accounting.funds,funds+income-expenses-result.loanPayment);const h=accounting.history.at(-1);assert.equal(h.income,income);assert.equal(h.expenses,expenses);assert.equal(h.loanPayment,result.loanPayment);}assert.equal(accounting.finance.totalLoanPaid,750);
const loaded=validateSave(JSON.parse(JSON.stringify(accounting)));assert.deepEqual(loaded.finance,accounting.finance);assert.deepEqual(loaded.stats,accounting.stats);const malformed=JSON.parse(JSON.stringify(accounting));malformed.finance.loans[0].paymentsMade=9;assert.throws(()=>validateSave(malformed),'malformed payment schedule cannot enter the simulation');
for(const version of [1,2]){const old=createCity();old.version=version;delete old.finance;const migrated=validateSave(old);assert.deepEqual(migrated.finance,freshFinance());assert.equal(migrated.version,VERSION);}
console.log('PASS: sector tax tradeoff and validation, exact ten-year loans/limits/schedules, forecasts, funding deterioration/recovery, park/pollution land values and taxes, pump pollution, monthly ledger conservation, finance saves and migration.');
