import assert from 'node:assert/strict';
import {createCity,build,idx,recompute,tick,validateSave} from '../dist/engine.js';
import {ignite,dispatchFire,stepFire,setRandomFires,maybeIgnite} from '../dist/emergency.js';
function base(){const c=createCity('Fire test',false);for(const t of c.tiles){t.terrain='land';t.nature=false;}const h=c.tiles[idx(20,20)];h.type='residential';h.level=1;recompute(c);return c;}
const c=base(),h=c.tiles[idx(20,20)];assert.equal(ignite(c,0,0).ok,false);assert.equal(build(c,'dezone',[h]).ok,false,'occupied neighborhoods require demolition');assert.ok(ignite(c,20,20).ok);assert.equal(build(c,'dezone',[h]).ok,false,'de-zoning cannot remove a burning building');assert.equal(setRandomFires(c,false).ok,false);assert.equal(build(c,'bulldoze',[h]).ok,false);assert.ok(dispatchFire(c,20,21).ok);dispatchFire(c,21,20);assert.deepEqual(c.emergency.units,[{x:21,y:20}]);const loaded=validateSave(JSON.parse(JSON.stringify(c)));assert.deepEqual(loaded.emergency,c.emergency);for(let i=0;i<20&&c.emergency.active;i++)stepFire(c);assert.equal(c.emergency.active,false);assert.equal(h.rubble,false);assert.equal(c.emergency.destroyed,0);
const lost=base(),lh=lost.tiles[idx(20,20)];ignite(lost,20,20);for(let i=0;i<100&&lost.emergency.active;i++)stepFire(lost);assert.equal(lh.rubble,true);assert.equal(lh.level,0);assert.ok(lost.emergency.displaced>0);assert.equal(build(lost,'residential',[lh]).ok,false);assert.ok(build(lost,'bulldoze',[lh]).ok);assert.equal(lh.rubble,false);assert.equal(lh.type,'residential','clearing rubble preserves zoning for recovery');assert.ok(build(lost,'dezone',[lh]).ok);assert.equal(lh.type,null);
const covered=base();covered.tiles[idx(20,20)].fireCoverage=100;ignite(covered,20,20);for(let i=0;i<30&&covered.emergency.active;i++)stepFire(covered);assert.equal(covered.emergency.destroyed,0);assert.equal(covered.emergency.active,false);
const wet=base(),dry=base();wet.tiles[idx(20,20)].flammability=15;dry.tiles[idx(20,20)].flammability=80;ignite(wet,20,20);ignite(dry,20,20);for(let i=0;i<10;i++){stepFire(wet);stepFire(dry);}assert.equal(dry.tiles[idx(20,20)].rubble,true);assert.equal(wet.tiles[idx(20,20)].rubble,false);
const units=base();build(units,'fire',[{x:30,y:30}]);ignite(units,20,20);dispatchFire(units,19,20);dispatchFire(units,20,21);assert.equal(units.emergency.units.length,2);dispatchFire(units,21,20);assert.deepEqual(units.emergency.units,[{x:21,y:20},{x:20,y:21}]);
const coal=base();assert.ok(build(coal,'coal',[{x:30,y:30}]).ok);ignite(coal,31,31);assert.equal(build(coal,'bulldoze',[{x:30,y:30}]).ok,false);for(let i=0;i<120&&coal.emergency.active;i++)stepFire(coal);recompute(coal);assert.equal(coal.tiles.filter(t=>t.type==='coal').length,0);assert.equal(coal.tiles.filter(t=>t.rubble).length,16);assert.ok(validateSave(JSON.parse(JSON.stringify(coal))));
const peaceful=base();for(let i=0;i<1000;i++){peaceful.month=i;assert.equal(maybeIgnite(peaceful),false);}assert.equal(setRandomFires(peaceful,true).ok,true);let started=false;for(let i=0;i<1000&&!started;i++){peaceful.month=i;started=maybeIgnite(peaceful);}assert.equal(started,true);
console.log('PASS: fire ignition, volunteer/station dispatch limits and cycling, containment, coverage, flammability, destruction/displacement, rubble clearing, active saves, whole-plant damage, protected bulldozing and optional random fires.');

const recovery=base(),rh=recovery.tiles[idx(20,20)];rh.density=3;rh.pipe=true;rh.subway=true;assert.ok(build(recovery,'bulldoze',[rh]).ok);assert.equal(rh.type,'residential');assert.equal(rh.density,3);assert.equal(rh.level,0);assert.equal(rh.pipe,true);assert.equal(rh.subway,true);assert.ok(build(recovery,'dezone',[rh]).ok);assert.equal(rh.type,null);
const town=createCity(),home=town.tiles.find(t=>t.type==='residential'&&t.level&&t.powered&&t.access);assert.ok(home);for(const t of town.tiles)t.nature=false;ignite(town,home.x,home.y);home.fire=100;home.fireAge=100;home.fireCoverage=0;stepFire(town);assert.equal(home.rubble,true);assert.ok(build(town,'bulldoze',[home]).ok);assert.equal(home.type,'residential');for(let i=0;i<36&&!home.level;i++)tick(town);assert.ok(home.level>0,'serviced cleared residential zoning redevelops without re-zoning');
