import assert from 'node:assert/strict';
import {generateCity} from '../dist/terrain-generator.js';
import {VERSION,build,selection,idx,recompute,tick,validateSave} from '../dist/engine.js';
import {farmCandidate,normalizeIndustry,expandFarms,industrialJobs,advanceIndustry} from '../dist/industry.js';
import {serializeCity} from '../dist/save.js';
import {ignite,stepFire} from '../dist/emergency.js';
function base(){const c=generateCity({startYear:2000,water:0,mountains:0,trees:0});build(c,'solar',[{x:10,y:15}]);build(c,'road',selection('road',{x:15,y:20},{x:20,y:20}));build(c,'residential',[{x:16,y:19}]);return c;}
const zone=(c,x,y,xx,yy)=>assert.ok(build(c,'industrial',selection('industrial',{x,y},{x:xx,y:yy})).ok);
function establish(c,members){const root=idx(members[0].x,members[0].y);for(const t of members)Object.assign(t,{industry:'farm',farmRoot:root,level:1,age:6});recompute(c);return c.tiles[root];}
const large=base();zone(large,19,23,28,32);const root=large.tiles[idx(19,23)],candidate=farmCandidate(large,root);assert.equal(candidate.length,64,'farm formation consumes up to 8 by 8 rural tiles');establish(large,candidate);assert.equal(large.stats.farmFields,64);assert.equal(large.stats.farms,1);assert.equal(industrialJobs(root),30);assert.equal(candidate.reduce((sum,t)=>sum+industrialJobs(t),0),30,'all jobs stay at barn');assert.equal(large.tiles[idx(26,30)].access,false);assert.equal(large.tiles[idx(26,30)].farmSize,64);const saved=validateSave(JSON.parse(serializeCity(large)));assert.deepEqual(saved.stats,large.stats);assert.ok(!serializeCity(large).includes('farmSize'),'extent is rebuilt rather than trusted from saves');
const small=base();zone(small,19,23,21,25);const barn=establish(small,farmCandidate(small,small.tiles[idx(19,23)]));zone(small,19,26,21,28);small.month=3;assert.equal(expandFarms(small),3,'one whole row added');recompute(small);assert.equal(small.stats.farmFields,12);assert.equal(industrialJobs(barn),13);small.month=4;assert.equal(expandFarms(small),0,'only quarterly checks');small.month=6;barn.age=5;assert.equal(expandFarms(small),0,'young farm holds its footprint');barn.age=6;small.tiles[idx(20,27)].airPollution=16;assert.equal(expandFarms(small),0,'polluted row is unavailable');small.tiles[idx(20,27)].airPollution=0;assert.equal(expandFarms(small),3);recompute(small);assert.equal(small.stats.farmFields,15);
const continued=validateSave(JSON.parse(serializeCity(small)));for(let i=0;i<6;i++){tick(small);tick(continued);}assert.deepEqual(continued.stats,small.stats);assert.deepEqual(continued.tiles.map(t=>t.farmRoot),small.tiles.map(t=>t.farmRoot));
const bad=validateSave(JSON.parse(serializeCity(large)));bad.tiles[idx(22,26)].level=0;normalizeIndustry(bad);assert.equal(bad.tiles.filter(t=>t.industry==='farm').length,0,'holes dissolve the estate');
const redevelopment=validateSave(JSON.parse(serializeCity(large)));redevelopment.tiles[idx(26,30)].landValue=69;advanceIndustry(redevelopment);assert.equal(redevelopment.tiles.some(t=>t.industry==='farm'),false,'outer-field land value can convert whole estate');
const disaster=validateSave(JSON.parse(serializeCity(large)));assert.ok(ignite(disaster,26,30).ok);Object.assign(disaster.tiles[idx(26,30)],{fire:100,fireAge:100});stepFire(disaster);recompute(disaster);assert.equal(disaster.stats.farms,0);assert.equal(disaster.tiles.filter(t=>t.rubble).length,64,'outer field destruction affects the full estate');assert.equal(disaster.emergency.destroyed,1);

const natural=base();for(const x of [15,16])Object.assign(natural.tiles[idx(x,19)],{type:'residential',level:3,density:3});recompute(natural);zone(natural,19,23,26,30);for(let m=0;m<100&&!natural.stats.farms;m++){natural.month++;advanceIndustry(natural);recompute(natural);}assert.ok(natural.stats.farmFields>9,'real monthly industrial development forms a larger estate');
const old=JSON.parse(serializeCity(base()));old.version=89;assert.equal(validateSave(old).version,VERSION);
console.log('PASS: bounded large farm formation, quarterly field expansion, barn-only scaled jobs, age/pollution gates, remote fields, deterministic saves, malformed estate normalization and whole-farm redevelopment/disaster recovery.');
