import assert from 'node:assert/strict';
import {createCity,build,selection,idx,recompute,tick,validateSave} from '../dist/engine.js';
import {recomputeFacilities,advanceFacilities} from '../dist/facilities.js';
function base(){const c=createCity('Ports',false);for(const t of c.tiles){t.terrain='land';t.nature=false;}return c;}
const zone=(c,type,a,b)=>assert.ok(build(c,type,selection(type,a,b)).ok);
const c=base();zone(c,'airport',{x:20,y:20},{x:22,y:24});assert.equal(c.stats.facilityPlots.length,1);assert.equal(c.stats.activeAirports,0);for(let i=0;i<8;i++)tick(c);assert.equal(c.tiles[idx(20,20)].level,0,'unserviced airport cannot develop');for(const t of c.tiles.filter(t=>t.type==='airport')){t.powered=true;t.watered=true;t.roadIds=[0];}c.stats={...c.stats,...recomputeFacilities(c)};for(let i=0;i<5;i++){advanceFacilities(c);c.stats={...c.stats,...recomputeFacilities(c)};}assert.equal(c.stats.activeAirports,0,'requires six supplied months');advanceFacilities(c);c.stats={...c.stats,...recomputeFacilities(c)};assert.equal(c.stats.activeAirports,1);assert.equal(c.stats.facilityUpkeep,30);assert.equal(build(c,'dezone',[{x:20,y:20}]).ok,false,'developed facility must be demolished');assert.ok(build(c,'bulldoze',[{x:21,y:22}]).ok);assert.equal(c.tiles.filter(t=>t.type==='airport'&&t.level===0).length,15,'demolition clears the whole building while retaining zoning');assert.ok(build(c,'dezone',[{x:21,y:22}]).ok);
const small=base();zone(small,'airport',{x:20,y:20},{x:21,y:24});assert.equal(small.stats.facilityPlots.length,0);assert.match(small.tiles[idx(20,20)].facilityReason,/3 × 5/);
const port=base();zone(port,'seaport',{x:20,y:20},{x:21,y:25});for(const t of port.tiles.filter(t=>t.type==='seaport')){t.powered=true;t.watered=true;t.roadIds=[1];}for(let y=20;y<26;y++)port.tiles[idx(19,y)].terrain='water';let f=recomputeFacilities(port);assert.equal(f.facilityPlots[0].ready,false,'landlocked lake is insufficient');for(let x=0;x<20;x++)port.tiles[idx(x,20)].terrain='water';f=recomputeFacilities(port);assert.equal(f.facilityPlots[0].ready,true,'shoreline has a water path to edge');port.stats={...port.stats,...f};for(let i=0;i<6;i++)advanceFacilities(port);assert.equal(recomputeFacilities(port).activeSeaports,1);for(const t of port.tiles.filter(t=>t.type==='seaport'))t.watered=false;port.stats={...port.stats,...recomputeFacilities(port)};assert.equal(port.stats.activeSeaports,0);for(let i=0;i<6;i++)advanceFacilities(port);assert.equal(port.tiles[idx(20,20)].level,0,'sustained supply failure abandons facility');
// Full utility integration and demand effect.
const live=base();for(let y=0;y<48;y++)live.tiles[idx(18,y)].terrain='water';build(live,'pump',[{x:19,y:21}]);build(live,'pipe',selection('pipe',{x:19,y:21},{x:23,y:21}));build(live,'road',selection('road',{x:24,y:20},{x:24,y:25}));build(live,'coal',[{x:26,y:20}]);zone(live,'airport',{x:20,y:20},{x:22,y:24});const demand=live.stats.demand.commercial;assert.equal(live.stats.facilityPlots[0].ready,true);for(let i=0;i<6;i++)tick(live);assert.equal(live.stats.activeAirports,1);assert.ok(live.stats.demand.commercial>demand);assert.equal(live.stats.spending.facilities,30);const saved=validateSave(JSON.parse(JSON.stringify(live)));assert.deepEqual(saved.stats,live.stats);
console.log('PASS: minimum footprints, service-gated timed development, navigable shoreline, abandonment, whole-facility demolition, utility integration, demand benefit, upkeep and save roundtrip.');
