import {readFileSync} from 'node:fs';
import assert from 'node:assert/strict';
import {createCity} from '../dist/engine.js';
import {takeLoan,settleLoans,budgetForecast} from '../dist/economy.js';
import {treasuryOutlook,financialAdvice,showFinancialAdvisor} from '../dist/financial-advisor.js';
const portrait=readFileSync(new URL('../dist/assets/mortimer-advisor.png',import.meta.url));assert.equal(portrait.subarray(1,4).toString(),'PNG');assert.ok(portrait.readUInt32BE(16)>=512);
const city=createCity('Treasury test',false);city.stats.businessIncome=100;takeLoan(city,25000);city.month=10;takeLoan(city,5000);city.funds=100;
const unchanged=JSON.stringify(city),outlook=treasuryOutlook(city,120);
assert.equal(outlook.budget.balance,100);assert.equal(outlook.rows[0].funds,200);assert.equal(outlook.rows[1].loanPayment,3750);assert.equal(outlook.firstShortfall.month,12);assert.equal(outlook.debtDue,45000);assert.equal(outlook.rows.length,120);assert.equal(JSON.stringify(city),unchanged);
const actual=structuredClone(city);for(const row of outlook.rows){actual.month++;actual.funds+=outlook.budget.balance;const paid=settleLoans(actual);assert.equal(paid,row.loanPayment);assert.equal(actual.funds,row.funds,'projection matches actual installment settlement');}assert.equal(actual.finance.loans.length,0);
assert.equal(treasuryOutlook(city,budgetForecast(city).monthsLeft).ending,budgetForecast(city).projectedYearEnd);
assert.match(financialAdvice(city,outlook)[0].title,/shortage/);assert.ok(financialAdvice(city,outlook).some(i=>i.title==='Reserve cash for loan payments'));
const safe=createCity('Stable',false);safe.funds=500;assert.equal(treasuryOutlook(safe).firstShortfall,null);assert.equal(financialAdvice(safe)[0].title,'Protect the treasury');safe.funds=-1;assert.equal(treasuryOutlook(safe).firstShortfall.month,safe.month);assert.match(financialAdvice(safe)[0].title,/already negative/);
safe.funds=500;safe.civic.ordinances.watch=true;assert.ok(financialAdvice(safe).some(i=>i.action==='ordinances'));assert.ok(financialAdvice(safe).some(i=>i.title==='Recurring expenses exceed income'));
for(const months of [0,121,1.5,NaN])assert.throws(()=>treasuryOutlook(city,months));
let html='',returned=0,policies=0,buttons=[];const nodes=new Map();globalThis.document={querySelector:s=>{if(!nodes.has(s))nodes.set(s,{});return nodes.get(s);},querySelectorAll:()=>buttons=Array.from(html.matchAll(/data-financial-action="([^"]+)"/g),m=>({dataset:{financialAction:m[1]}}))};
const ui={city:()=>safe,dialog:(title,body)=>{assert.equal(title,'Mortimer Green');html=body;},ordinances:()=>policies++};
showFinancialAdvisor(ui,()=>returned++);assert.match(html,/mortimer-advisor.png/);assert.match(html,/Inspect 12 monthly balances/);buttons.find(b=>b.dataset.financialAction==='ordinances').onclick();assert.equal(policies,1);buttons.find(b=>b.dataset.financialAction==='budget').onclick();assert.equal(returned,1);nodes.get('#treasuryHorizon').onchange({target:{value:'120'}});assert.match(html,/Inspect 120 monthly balances/);nodes.get('#backFinancialAdvisor').onclick();assert.equal(returned,2);
console.log('PASS: treasury projection matches staggered ten-year loan settlement, year-end forecast, shortage and policy advice, state preservation, horizon controls and advisor navigation.');
