import {freshDemographics} from '../dist/demographics.js';
import assert from 'node:assert/strict';
import {createCity,build,selection,recompute,idx,validateSave,applyBudget} from '../dist/engine.js';
import {streetGraph,MinQueue} from '../dist/highway.js';
function base(){const c=createCity('Highways',false);for(const t of c.tiles){t.terrain='land';t.nature=false;}const h=c.tiles[idx(12,16)],w=c.tiles[idx(36,16)];h.type='residential';h.level=3;h.density=3;w.type='industrial';w.level=3;w.density=3;c.demographics=freshDemographics(64,0);return c;}
const place=(c,tool,x,y)=>assert.ok(build(c,tool,[{x,y}]).ok,tool);
const line=(c,tool,a,b)=>assert.ok(build(c,tool,selection(tool,a,b)).ok,tool);
const c=base();line(c,'road',{x:12,y:17},{x:12,y:22});line(c,'road',{x:36,y:17},{x:36,y:22});line(c,'highway',{x:12,y:20},{x:36,y:20});assert.equal(c.stats.unemployed,32,'crossing alone is not a connection');place(c,'ramp',13,21);assert.equal(c.stats.unemployed,32,'one ramp is insufficient');place(c,'ramp',35,21);assert.equal(c.stats.unemployed,0,'two ramps join access roads');assert.ok(c.stats.highwayVehicles>0);assert.equal(c.stats.activeRamps,2);assert.equal(c.tiles[idx(24,20)].highwayTraffic,32);const g=streetGraph(c),N=c.tiles.length;assert.ok(g.edges[idx(12,20)].includes(idx(12,20)+N));
place(c,'bulldoze',13,21);assert.equal(c.stats.unemployed,32);place(c,'ramp',13,21);place(c,'removeHighway',12,20);assert.equal(c.tiles[idx(12,20)].type,'road','dedicated highway removal preserves underlying road');assert.equal(c.stats.unemployed,32);place(c,'highway',12,20);assert.equal(c.stats.unemployed,0);assert.equal(build(c,'ramp',[{x:25,y:25}]).ok,false,'ramp requires a crossing');
// A longer highway is preferred to a slow ordinary road route.
line(c,'road',{x:12,y:22},{x:36,y:22});recompute(c);assert.ok(c.tiles[idx(24,20)].highwayTraffic>0);assert.equal(c.tiles[idx(24,22)].traffic,0);assert.ok(c.stats.spending.roads>c.stats.roads*.4,'highway maintenance is included');applyBudget(c,c.finance.taxes,0);assert.equal(c.stats.spending.roads,0);
const b=base();for(let x=23;x<=26;x++)b.tiles[idx(x,20)].terrain='water';const funds=b.funds;line(b,'highway',{x:22,y:20},{x:27,y:20});assert.equal(b.funds,funds-1120);assert.equal(b.stats.highwayBridgeTiles,4);assert.equal(b.tiles[idx(24,20)].highwayAxis,'x');assert.equal(build(b,'highway',selection('highway',{x:22,y:21},{x:24,y:20})).ok,true); // This selection stays entirely on dry land.
const loaded=validateSave(JSON.parse(JSON.stringify(c)));assert.deepEqual(loaded.stats,c.stats);const bad=JSON.parse(JSON.stringify(b));bad.tiles[idx(24,20)].highwayAxis='bad';assert.throws(()=>validateSave(bad));const old=createCity();old.version=6;for(const t of old.tiles)delete t.highway;assert.equal(validateSave(old).tiles.some(t=>t.highway),false);
const queue=new MinQueue();for(const cost of [10,3,9,1,2])queue.push(cost,cost);assert.deepEqual(Array.from({length:5},()=>queue.pop().cost),[1,2,3,9,10]);
console.log('PASS: overpass isolation, two-ramp highway access, ramp removal, preserved lower road, fast-route preference, highway upkeep, bridge costs/direction, saves/migration and routing priority queue.');
