import assert from 'node:assert/strict';
import {createCity,build,recompute,validateSave} from '../dist/engine.js';
import {recomputeCivic,civicSpending} from '../dist/civic.js';
import {jailStatus,jailCapacity,jailReport} from '../dist/jail.js';
import {civicFacilityDetails,civicFacilityReport} from '../dist/civic-service-report.js';
import {serializeCity} from '../dist/save.js';
assert.deepEqual(jailCapacity(150),{cells:300,capacity:300,maximum:360});
assert.equal(jailStatus(300,300,360).policeEffectiveness,1);
assert.ok(Math.abs(jailStatus(330,300,360).policeEffectiveness-.75)<1e-12);
assert.ok(jailStatus(360,300,360).policeEffectiveness<.75);
assert.equal(jailStatus(361,300,360).released,1);
assert.equal(jailStatus(0,0,0).policeEffectiveness,.75);
const c=createCity('Jail load',false);for(const t of c.tiles)Object.assign(t,{terrain:'land',nature:false});
const police=c.tiles[0];Object.assign(police,{type:'police',powered:true,roadIds:[1]});
for(let i=1;i<=500;i++)Object.assign(c.tiles[i],{type:'residential',level:3,roadIds:[1]});
const update=()=>Object.assign(c.stats,recomputeCivic(c));update();const unserved=c.tiles[1].policeCoverage;
const jail=c.tiles[501];Object.assign(jail,{type:'jail',powered:true,roadIds:[1]});update();
assert.equal(c.stats.jails.need,320);assert.equal(c.stats.jails.capacity,300);assert.equal(c.stats.jails.overcrowded,true);assert.ok(c.tiles[1].policeCoverage>unserved);const crowded=c.tiles[1].policeCoverage;
assert.equal(civicFacilityDetails(c,jail).capacity,300);assert.match(civicFacilityReport(c,jail),/overcrowded/);assert.match(jailReport(c),/not individually tracked arrests/);
c.civic.funding.police=150;update();assert.equal(c.stats.jails.capacity,300);assert.equal(civicFacilityDetails(c,jail).capacity,300);assert.equal(civicSpending(c).police,150);
c.civic.funding.police=100;const second=c.tiles[502];Object.assign(second,{type:'jail',powered:true,roadIds:[1]});update();assert.equal(c.stats.jails.overcrowded,false);assert.equal(c.stats.jails.capacity,600);assert.equal(c.stats.jails.policeEffectiveness,1);assert.ok(c.tiles[1].policeCoverage>crowded);
second.fire=5;update();assert.equal(c.stats.jails.capacity,300);jail.powered=false;update();assert.equal(c.stats.jails.capacity,0);assert.equal(c.stats.jails.released,320);
jail.powered=true;second.fire=0;c.civic.funding.police=50;update();assert.equal(c.stats.jails.capacity,300);c.civic.underfunded.police=6;update();assert.equal(c.stats.jails.capacity,0);
const saved=createCity();const funds=saved.funds;assert.ok(build(saved,'jail',[{x:27,y:14}]).ok);assert.equal(funds-saved.funds,2500);saved.civic.funding.police=150;recompute(saved);const restored=validateSave(JSON.parse(serializeCity(saved)));assert.deepEqual(restored.stats.jails,saved.stats.jails);assert.equal(restored.stats.serviceCapacities.jail,300);
console.log('PASS: finite jail cells, overcrowding thresholds, police recovery through expansion, funding limits, damage/strike loss, construction cost, query consistency and save continuity.');
