import assert from 'node:assert/strict';
import {createCity,build,selection,idx,planBuild,recompute,validateSave} from '../dist/engine.js';
import {serializeCity} from '../dist/save.js';
import {CityRenderer} from '../dist/renderer.js';
function base(){const c=createCity('Landscape',false);for(const t of c.tiles){t.terrain='land';t.nature=false;t.treeLevel=0;}return c;}
const c=base(),p={x:20,y:20};assert.ok(build(c,'raise',[p]).ok);assert.equal(c.tiles[idx(20,20)].elevation,1);const funds=c.funds,plan=planBuild(c,'raise',[p]);assert.equal(plan.points.length,5);assert.ok(build(c,'raise',[p]).ok);assert.equal(c.funds,funds-plan.cost);assert.equal(c.tiles[idx(19,20)].elevation,1);build(c,'road',[{x:18,y:20}]);const before=serializeCity(c);assert.equal(build(c,'raise',[p]).ok,false,'propagation cannot disturb existing roads');assert.equal(serializeCity(c),before,'rejected edits are atomic');assert.equal(build(c,'coal',[{x:20,y:20}]).ok,false,'large plants require level footprint');assert.ok(build(c,'levelTerrain',selection('levelTerrain',{x:21,y:21},{x:19,y:19})).ok);assert.equal(c.tiles[idx(20,20)].elevation,0,'reverse drag preserves starting elevation');
const pond=base();build(pond,'coal',[{x:25,y:20}]);assert.ok(build(pond,'surfaceWater',[{x:23,y:20}]).ok);assert.equal(pond.tiles[idx(23,20)].waterKind,'fresh');assert.ok(build(pond,'pump',[{x:24,y:20}]).ok);assert.ok(pond.tiles[idx(24,20)].pumpCapacity>0,'created freshwater supplies pumps');assert.equal(build(pond,'raise',[{x:23,y:20}]).ok,false,'ponds are protected');build(pond,'pipe',[{x:15,y:15}]);assert.equal(build(pond,'surfaceWater',[{x:15,y:15}]).ok,false,'pond creation protects underground utilities');
const trees=base();const spot=trees.tiles[idx(20,20)];const initial=spot.landValue;for(let i=1;i<=3;i++){assert.ok(build(trees,'plantTrees',[{x:20,y:20}]).ok);assert.equal(spot.treeLevel,i);}assert.equal(build(trees,'plantTrees',[{x:20,y:20}]).ok,false);assert.ok(spot.landValue>initial);assert.ok(build(trees,'bulldoze',[{x:20,y:20}]).ok);assert.equal(spot.nature,false);assert.ok(build(trees,'plantTrees',[{x:20,y:20}]).ok);assert.equal(spot.treeLevel,1);
const hill=base();hill.month=360;for(let i=0;i<4;i++)assert.ok(build(hill,'raise',[p]).ok);assert.ok(build(hill,'wind',[p]).ok);assert.equal(hill.stats.powerCapacity,35,'elevation improves wind output');const saved=validateSave(JSON.parse(serializeCity(hill)));assert.deepEqual(saved.stats,hill.stats);assert.equal(saved.tiles[idx(20,20)].elevation,4);const old=JSON.parse(serializeCity(hill));old.version=14;for(const t of old.tiles){delete t.elevation;delete t.treeLevel;}assert.equal(validateSave(old).tiles[idx(20,20)].elevation,0);
const renderer=Object.create(CityRenderer.prototype);Object.assign(renderer,{getCity:()=>hill,w:1200,h:800,pan:{x:0,y:0},zoom:1,rotation:0});for(let r=0;r<4;r++){renderer.rotation=r;const screen=renderer.project(20,20);assert.deepEqual(renderer.pick(screen.x,screen.y+renderer.unit/2),p,'raised tile is picked correctly in every rotation');}const flatY=(()=>{hill.tiles[idx(20,20)].elevation=0;return renderer.project(20,20).y;})();hill.tiles[idx(20,20)].elevation=4;assert.equal(renderer.project(20,20).y,flatY-46);
console.log('PASS: slope propagation/cost, protected and atomic edits, reverse leveling, flat foundations, freshwater pumping, utility protection, tree maturity/environment, hilltop wind, saves and rotated raised-tile picking.');
