import assert from 'node:assert/strict';
import {createScenario} from '../dist/scenario-setup.js';
import {scenarioGoals} from '../dist/scenarios.js';
import {build,tick,validateSave} from '../dist/engine.js';
import {serializeCity} from '../dist/save.js';
const c=createScenario('learningCity');assert.equal(c.stats.population,224);assert.equal(c.funds,8000);assert.equal(c.civic.adultEducation,40);assert.equal(c.stats.uncollectedWaste,0);assert.equal(serializeCity(c),serializeCity(createScenario('learningCity')));assert.equal(c.scenario.status,'playing');
assert.ok(build(c,'library',[{x:23,y:25}]).ok);assert.ok(build(c,'museum',[{x:27,y:21}]).ok);for(let i=0;i<6;i++)tick(c);assert.equal(c.scenario.status,'playing');const saved=validateSave(JSON.parse(serializeCity(c)));for(let i=6;i<24&&c.scenario.status==='playing';i++){tick(c);tick(saved);}assert.equal(c.scenario.status,'won');assert.ok(c.scenario.endedMonth<=24);assert.ok(scenarioGoals(c).every(g=>g.done));assert.equal(serializeCity(c),serializeCity(saved));
const neglected=createScenario('learningCity');for(let i=0;i<24;i++)tick(neglected);assert.equal(neglected.scenario.status,'lost');
const onlyLibraries=createScenario('learningCity');build(onlyLibraries,'library',[{x:23,y:25}]);build(onlyLibraries,'library',[{x:27,y:21}]);for(let i=0;i<24;i++)tick(onlyLibraries);assert.equal(onlyLibraries.scenario.status,'lost');assert.equal(scenarioGoals(onlyLibraries)[2].done,false);
console.log('PASS: deterministic learning challenge, ordinary-building win, gradual progress, exact saved continuation, neglect loss and complementary-service requirement.');
