import assert from 'node:assert/strict';
import {createCity,build,selection,idx,recompute,tick,validateSave} from '../dist/engine.js';
import {serializeCity} from '../dist/save.js';
import {connectionCandidates,addConnection,signDeal,exportGarbage,importGarbage,regionBudget,settleRegion} from '../dist/region.js';
import {renewDeal} from '../dist/regional-contract-reviews.js';
import {neighborSupply} from '../dist/neighbor-economies.js';
const base=()=>{const c=createCity('Trade commitments',false);c.startYear=2000;c.funds=100000;for(const t of c.tiles)Object.assign(t,{terrain:'land',nature:false});return c;};
function connect(c,kind,side){const p=connectionCandidates(c).find(p=>p.kind===kind&&p.side===side);assert.ok(p);assert.ok(addConnection(c,p).ok);return c.region.connections.length-1;}
const c=base();build(c,'powerline',selection('powerline',{x:0,y:20},{x:47,y:20}));for(const x of [20,21,22,23])assert.ok(build(c,'wind',[{x,y:19}]).ok);for(const side of ['west','east'])assert.ok(signDeal(c,connect(c,'power',side),'power','export',50).ok);recompute(c);assert.ok(c.region.deals.every(d=>d.delivered===50&&!d.failed));c.month=12;const before=serializeCity(c);assert.equal(renewDeal(c,c.region.deals[0].id,100).ok,false,'renewing an older contract must not break its younger neighbor commitment');assert.equal(serializeCity(c),before);
assert.ok(build(c,'bulldoze',[{x:23,y:19}]).ok);assert.equal(c.region.deals[0].delivered,50);assert.equal(c.region.deals[1].failed,true);const failed=c.region.deals[1],penalty=Math.ceil(Math.max(failed.minFee,failed.amount*failed.rate)*12);const result=tick(c);assert.equal(result.failedDeals,1);assert.equal(result.regionalPenalty,penalty);assert.equal(c.region.deals.length,1);assert.equal(c.region.deals[0].direction,'export');validateSave(JSON.parse(serializeCity(c)));
const g=base();build(g,'road',selection('road',{x:0,y:20},{x:47,y:20}));build(g,'road',selection('road',{x:20,y:0},{x:20,y:47}));Object.assign(g.tiles[idx(22,19)],{type:'residential',level:1,waste:100});for(const [side,space]of [['west',30],['east',40]]){const n=g.region.neighbors[side];n.wasteCapacity=n.wasteStored+Math.max(0,n.population*.005-20)+space;assert.ok(signDeal(g,connect(g,'road',side),'garbage','export',50).ok);}recompute(g);const untouched=structuredClone(g);exportGarbage(g);assert.deepEqual(g.region.deals.map(d=>d.delivered),[30,40]);assert.equal(g.tiles[idx(22,19)].waste,30);untouched.region.deals.reverse();exportGarbage(untouched);assert.equal(untouched.tiles[idx(22,19)].waste,30);for(const d of g.region.deals)assert.equal(untouched.region.deals.find(other=>other.id===d.id).delivered,d.delivered);
// Incoming waste from two other neighbors is injected once at their own routes.
for(const [side,amount]of [['north',25],['south',50]])assert.ok(signDeal(g,connect(g,'road',side),'garbage','import',amount).ok);recompute(g);const mass=g.tiles.reduce((sum,t)=>sum+t.waste,0);importGarbage(g);assert.equal(g.tiles.reduce((sum,t)=>sum+t.waste,0),mass+75);assert.equal(g.region.deals.filter(d=>d.direction==='import').reduce((sum,d)=>sum+d.delivered,0),75);const expected=regionBudget(g),deliveries=g.region.deals.map(d=>({side:g.region.connections[d.connection].side,direction:d.direction,amount:d.delivered,rate:d.rate,minFee:d.minFee}));g.month=1;const settlement=settleRegion(g);assert.equal(settlement.regionIncome,expected.regionIncome);assert.equal(settlement.regionExpense,expected.regionExpense);for(const d of deliveries)assert.equal(g.region.neighbors[d.side].lastTradeBalance,Math.round(d.direction==='export'?Math.max(d.minFee,d.amount*d.rate):-d.amount*d.rate));assert.equal(g.region.deals.length,4);validateSave(JSON.parse(serializeCity(g)));
for(let i=0;i<3;i++){const waiting=g.tiles.reduce((sum,t)=>sum+t.waste,0),restored=validateSave(JSON.parse(serializeCity(g)));tick(g);tick(restored);const record=g.history.at(-1),disposed=record.garbageRecycled+record.garbageIncinerated+record.garbageLandfilled+record.garbageExported;assert.equal(record.garbageImported,75);assert.ok(Math.abs(waiting+record.garbageGenerated+record.garbageImported-disposed-record.garbageUncollected)<1e-8,'monthly multi-neighbor garbage ledger conserves all mass');assert.equal(record.garbageExported,g.region.deals.filter(d=>d.kind==='garbage'&&d.direction==='export').reduce((sum,d)=>sum+d.delivered,0));assert.deepEqual(JSON.parse(serializeCity(restored)),JSON.parse(serializeCity(g)));}
console.log('PASS: multiple real export commitments, oldest-contract allocation and exact failure penalty, renewal rollback protecting other deals, conserved multi-route garbage, stable disposal order and separate neighbor settlement.');
