import {attachCustomScenario} from '../dist/custom-scenarios.js';
import {restartCustomScenario} from '../dist/scenario-replay.js';
import assert from 'node:assert/strict';
import {createCity,build,selection,idx,recompute,tick,validateSave,VERSION} from '../dist/engine.js';
import {serializeCity} from '../dist/save.js';
import {connectionCandidates,addConnection,signDeal,cancelDeal,validateRegion,freshRegion} from '../dist/region.js';
const c=createCity('Diversified supply',false);for(const t of c.tiles)Object.assign(t,{terrain:'land',nature:false});
for(const tool of ['powerline','pipe'])assert.ok(build(c,tool,selection(tool,{x:0,y:20},{x:47,y:20})).ok);
for(const x of [20,22,24])Object.assign(c.tiles[idx(x,19)],{type:'residential',level:1});Object.assign(c.tiles[idx(40,40)],{type:'residential',level:1});recompute(c);
const contracts={};for(const kind of ['power','water'])for(const side of ['west','east']){const candidate=connectionCandidates(c).find(p=>p.kind===kind&&p.side===side);assert.ok(candidate);assert.ok(addConnection(c,candidate).ok);const index=c.region.connections.length-1;assert.ok(signDeal(c,index,kind,'import',50).ok);contracts[kind+side]=c.region.deals.at(-1).id;}
assert.equal(c.region.deals.length,4);c.region.neighbors.west.powerCapacity=c.region.neighbors.west.population*.04+2;c.region.neighbors.east.powerCapacity=c.region.neighbors.east.population*.04+10;c.region.neighbors.west.waterCapacity=c.region.neighbors.west.population*.035+5;c.region.neighbors.east.waterCapacity=c.region.neighbors.east.population*.035+20;recompute(c);
const deal=key=>c.region.deals.find(d=>d.id===contracts[key]);assert.equal(deal('powerwest').delivered,2);assert.equal(deal('powereast').delivered,4);assert.equal(deal('waterwest').delivered,5);assert.equal(deal('watereast').delivered,7);for(const x of [20,22,24]){assert.ok(c.tiles[idx(x,19)].powered);assert.ok(c.tiles[idx(x,19)].watered);}assert.equal(c.tiles[idx(40,40)].powered,false);assert.equal(c.tiles[idx(40,40)].watered,false);assert.equal(c.stats.regionExpense,40,'minimum charges apply separately to all four contracts');
const loaded=validateSave(JSON.parse(serializeCity(c)));assert.deepEqual(loaded.region,c.region);assert.deepEqual(loaded.stats,c.stats);const before=new Map(c.region.deals.map(d=>[d.id,d.delivered]));c.region.deals.reverse();recompute(c);for(const d of c.region.deals)assert.equal(d.delivered,before.get(d.id),'array order cannot alter allocation');
const westPower=c.region.connections.findIndex(p=>p.kind==='power'&&p.side==='west'),unchanged=JSON.stringify(c.region);assert.equal(signDeal(c,westPower,'power','export',25).ok,false);assert.equal(JSON.stringify(c.region),unchanged);const duplicate=JSON.parse(serializeCity(c));duplicate.region.deals.push({...duplicate.region.deals.find(d=>d.id===contracts.powerwest),id:duplicate.region.nextId++});assert.throws(()=>validateSave(duplicate),/Duplicate/);
c.region.neighbors.west.powerCapacity=c.region.neighbors.west.population*.04;recompute(c);assert.equal(deal('powerwest').delivered,0);assert.equal(deal('powerwest').failed,false);assert.equal(deal('powereast').delivered,6);assert.equal(c.stats.regionExpense,40,'unused backup contracts retain their minimum fee');
const continuation=validateSave(JSON.parse(serializeCity(c)));tick(c);tick(continuation);assert.deepEqual(JSON.parse(serializeCity(c)),JSON.parse(serializeCity(continuation)));assert.equal(c.region.deals.length,4);const remaining=c.region.deals.filter(d=>d.id!==contracts.powerwest).map(d=>d.id);assert.ok(cancelDeal(c,contracts.powerwest).ok);assert.deepEqual(c.region.deals.map(d=>d.id),remaining);recompute(c);assert.ok(c.region.deals.find(d=>d.id===contracts.powereast));
const mixed=createCity('Separate trading grids',false,96);mixed.funds=100000;for(const t of mixed.tiles)Object.assign(t,{terrain:'land',nature:false});for(const [from,to]of [[{x:0,y:10},{x:10,y:10}],[{x:85,y:70},{x:95,y:70}]])assert.ok(build(mixed,'powerline',selection('powerline',from,to,96)).ok);Object.assign(mixed.tiles[9*96+8],{type:'residential',level:1});assert.ok(build(mixed,'coal',[{x:86,y:66}]).ok);recompute(mixed);for(const [side,direction]of [['west','import'],['east','export']]){const p=connectionCandidates(mixed).find(p=>p.kind==='power'&&p.side===side);assert.ok(addConnection(mixed,p).ok);assert.ok(signDeal(mixed,mixed.region.connections.length-1,'power',direction,50).ok);}recompute(mixed);assert.equal(mixed.region.deals[0].delivered,2);assert.equal(mixed.region.deals[1].delivered,50);assert.ok(mixed.tiles[9*96+8].powered);attachCustomScenario(mixed,{title:'Keep both grids',months:24,objectives:[{metric:'population',target:999999}]});const initialRegion=structuredClone(mixed.region),workerBefore=serializeCity(mixed),direct=structuredClone(mixed);let response;globalThis.self={postMessage:value=>{response=structuredClone(value);}};await import('../dist/simulation-worker.js');self.onmessage({data:{id:61,city:structuredClone(mixed)}});assert.equal(response.error,undefined);tick(direct);assert.deepEqual(JSON.parse(serializeCity(response.city)),JSON.parse(serializeCity(direct)));assert.equal(serializeCity(mixed),workerBefore);const replay=restartCustomScenario(validateSave(JSON.parse(serializeCity(response.city))));assert.deepEqual(replay.region,initialRegion);assert.equal(replay.month,0);
const maximum=freshRegion();for(const side of ['north','east','south','west','sea'])for(const kind of side==='sea'?['garbage']:['power','water','garbage']){const connection=maximum.connections.length;maximum.connections.push({tile:connection,kind:kind==='garbage'?(side==='sea'?'seaport':'road'):kind,side});maximum.deals.push({id:maximum.nextId++,connection,kind,direction:'import',amount:25,priceBand:'standard',issuedMonth:0,delivered:0});}assert.equal(validateRegion(maximum,0,48*48).deals.length,13);const over=structuredClone(maximum);over.deals.push({...over.deals[0],id:over.nextId++});assert.throws(()=>validateRegion(over,0,48*48));const sea=structuredClone(maximum);sea.connections[0].side='sea';assert.throws(()=>validateRegion(sea,0,48*48),/connection/);const legacy=JSON.parse(serializeCity(createCity()));legacy.version=110;assert.equal(validateSave(legacy).version,VERSION);
console.log('PASS: four real neighbor contracts, combined power/water delivery, isolated district exclusion, per-contract minimum fees, stable allocation, backup shortage, strict duplicate validation, saved monthly continuation and cancellation isolation.');
