import assert from 'node:assert/strict';
import {createCity,build,selection,recompute} from '../dist/engine.js';
import {connectionCandidates,addConnection,signDeal} from '../dist/region.js';
import {showRegion} from '../dist/region-ui.js';
const c=createCity('Trading desk',false);for(const t of c.tiles)Object.assign(t,{terrain:'land',nature:false});build(c,'powerline',selection('powerline',{x:0,y:20},{x:47,y:20}));for(const side of ['west','east'])assert.ok(addConnection(c,connectionCandidates(c).find(p=>p.kind==='power'&&p.side===side)).ok);assert.ok(signDeal(c,0,'power','import',50).ok);recompute(c);
let html='',saves=0,clears=0,updates=0;const controls=new Map(),buttons=[];
function dialog(title,body){html=body;controls.clear();buttons.length=0;for(const m of body.matchAll(/<\w+\b([^>]*\bid="([^"]+)"[^>]*)>/g))controls.set(m[2],{value:m[1].match(/value="([^"]*)"/)?.[1]||'',textContent:'',disabled:/ disabled/.test(m[1])});for(const m of body.matchAll(/<select[^>]*id="([^"]+)"[^>]*>([\s\S]*?)<\/select>/g)){const options=[...m[2].matchAll(/<option\b([^>]*)>/g)],chosen=options.find(o=>/selected/.test(o[1]))||options[0];controls.get(m[1]).value=chosen?.[1].match(/value="([^"]*)"/)?.[1]||'';}for(const m of body.matchAll(/data-(cancel|review)-deal="(\d+)"/g))buttons.push({dataset:{[m[1]+'Deal']:m[2]}});}
globalThis.document={querySelector:s=>controls.get(s.slice(1)),querySelectorAll:s=>buttons.filter(b=>s==='[data-cancel-deal]'?b.dataset.cancelDeal:b.dataset.reviewDeal)};
const ui={city:()=>c,dialog,save(){saves++;},clearUndo(){clears++;},update(){updates++;},notify(){}};showRegion(ui);assert.equal(controls.get('acceptDeal').disabled,true);assert.match(controls.get('dealTerms').textContent,/already has your power contract/);assert.match(html,/one deal per resource with each neighbor/);assert.match(html,/Every signed import has its own minimum fee/);assert.match(html,/Older export contracts/);
controls.get('dealConnection').value='1';controls.get('dealConnection').onchange();assert.equal(controls.get('acceptDeal').disabled,false);controls.get('acceptDeal').onclick();assert.equal(c.region.deals.length,2);assert.equal(saves,1);assert.equal(clears,1);assert.equal(updates,1);assert.equal(controls.get('acceptDeal').disabled,true);assert.match(html,/Westhaven/);assert.match(html,/Eastborough/);const remaining=c.region.deals[1].id;buttons.find(b=>b.dataset.cancelDeal===String(c.region.deals[0].id)).onclick();assert.equal(c.region.deals.length,1);assert.equal(c.region.deals[0].id,remaining);assert.equal(saves,2);assert.equal(controls.get('acceptDeal').disabled,false);
console.log('PASS: actual Region handlers prevent duplicate neighbor/resource offers, allow a second neighbor, explain allocation and minimum fees, persist accepted deals and cancel one contract without removing another.');
