import assert from 'node:assert/strict';
import {createCity,build,selection,recompute,tick,validateSave,idx} from '../dist/engine.js';
import {serializeCity} from '../dist/save.js';
import {connectionCandidates,addConnection,signDeal,exportGarbage,importGarbage,regionBudget} from '../dist/region.js';
import {neighborSupply,advanceNeighborEconomies,validateNeighborEconomies} from '../dist/neighbor-economies.js';
function city(){const c=createCity('Regional test',false);for(const t of c.tiles){t.terrain='land';t.nature=false;}return c;}
function connect(c,kind){assert.ok(addConnection(c,connectionCandidates(c).find(p=>p.kind===kind)).ok);return c.region.connections.length-1;}
const power=city();build(power,'powerline',selection('powerline',{x:42,y:20},{x:47,y:20}));const home=power.tiles[idx(43,21)];home.type='residential';home.level=3;home.density=3;recompute(power);const pc=connect(power,'power');assert.ok(signDeal(power,pc,'power','import',50).ok);const side=power.region.connections[pc].side,n=power.region.neighbors[side];n.powerCapacity=n.population*.04+5;n.treasury=0;recompute(power);assert.equal(power.region.deals[0].delivered,5);assert.equal(power.region.deals[0].failed,false);const stable=structuredClone(power.region.neighbors);for(let i=0;i<5;i++)recompute(power);assert.deepEqual(power.region.neighbors,stable,'read-only network refresh cannot grow neighbors or charge their budgets');const result=tick(power);assert.equal(result.failedDeals,0);assert.equal(result.regionalPenalty,0);assert.ok(power.region.deals.length);assert.equal(power.region.neighbors[side].lastTradeBalance,10,'minimum usage fee reaches neighbor ledger');
const garbage=city();build(garbage,'road',selection('road',{x:40,y:20},{x:47,y:20}));const gc=connect(garbage,'road');signDeal(garbage,gc,'garbage','export',50);const gs=garbage.region.connections[gc].side,gn=garbage.region.neighbors[gs];gn.treasury=0;gn.wasteStored=gn.wasteCapacity-Math.max(0,gn.population*.005-20)-5;const waste=garbage.tiles[idx(43,21)];waste.type='residential';waste.level=1;waste.waste=100;recompute(garbage);assert.equal(neighborSupply(garbage,gs,'garbage'),5);exportGarbage(garbage);assert.equal(garbage.region.deals[0].delivered,5);assert.equal(waste.waste,95,'undelivered garbage stays local');assert.equal(regionBudget(garbage).regionExpense,15);garbage.month=1;advanceNeighborEconomies(garbage,garbage.region.deals,garbage.region.connections);assert.equal(gn.wasteStored,gn.wasteCapacity);assert.equal(gn.lastTradeBalance,15);const once=structuredClone(garbage.region.neighbors);advanceNeighborEconomies(garbage,garbage.region.deals,garbage.region.connections);assert.deepEqual(garbage.region.neighbors,once,'neighbor advancement occurs at most once per city month');
const incoming=city();build(incoming,'road',selection('road',{x:40,y:20},{x:47,y:20}));const ic=connect(incoming,'road');signDeal(incoming,ic,'garbage','import',25);incoming.region.neighbors[incoming.region.connections[ic].side].wasteStored=3;importGarbage(incoming);assert.equal(incoming.region.deals[0].delivered,3);assert.equal(regionBudget(incoming).regionIncome,6,'incoming waste earns payment only for actual delivery');
const investing=createCity(),ownFunds=investing.funds,neighbor=investing.region.neighbors.north;neighbor.powerCapacity=100;const cash=neighbor.treasury;investing.month=1;advanceNeighborEconomies(investing,[]);assert.equal(neighbor.powerCapacity,400);assert.ok(neighbor.treasury<cash);assert.equal(investing.funds,ownFunds,'neighbor investment uses its own treasury');assert.ok(investing.region.neighbors.east.population>12000,'unconnected neighbors still evolve');
const loaded=validateSave(JSON.parse(serializeCity(power)));assert.deepEqual(loaded.region,power.region);tick(power);tick(loaded);assert.equal(serializeCity(loaded),serializeCity(power),'saved regional economies continue identically');
for(const mutate of [v=>delete v.north,v=>v.east.population=-1,v=>v.north.treasury=Infinity,v=>v.sea.population=1,v=>v.west.wasteStored=v.west.wasteCapacity+1,v=>v.south.month=999]){const bad=structuredClone(power.region.neighbors);mutate(bad);assert.throws(()=>validateNeighborEconomies(bad,power.month));}
const unavailable=city();build(unavailable,'pipe',selection('pipe',{x:44,y:20},{x:47,y:20}));const uc=connect(unavailable,'water');unavailable.region.neighbors[unavailable.region.connections[uc].side].waterCapacity=0;assert.equal(signDeal(unavailable,uc,'water','import',50).ok,false,'empty neighbor supply cannot be offered as a new contract');
const old=JSON.parse(serializeCity(power));old.version=85;delete old.region.neighbors;const migrated=validateSave(old);assert.equal(migrated.region.neighbors.north.month,migrated.month);assert.equal(migrated.region.neighbors.north.population,8000);
console.log('PASS: finite deficit supply, local retention of unshipped waste, actual incoming-waste payments, neighbor trade ledgers, independent growth/investment, once-monthly nonmutating recomputation, deterministic saves and legacy/malformed economies.');
