import assert from 'node:assert/strict';
import {createCity,validateSave} from '../dist/engine.js';
import {generateCity} from '../dist/terrain-generator.js';
import {serializeCity} from '../dist/save.js';
import {defaultBuildingDesign} from '../dist/building-designs.js';
import {copyBuildingSet} from '../dist/building-sets.js';
import {showNewCity} from '../dist/new-city-ui.js';
const current=createCity('Source town');current.buildingDesigns={'5@2x2':{...defaultBuildingDesign('5@2x2'),name:'Copper district',blocks:Array(100).fill(3)}};current.buildingReplacements={2:74};const original=serializeCity(current),buildingSet=copyBuildingSet(current);
for(const starter of [false,true])for(const size of [48,96]){const a=generateCity({starter,size,appearance:{landscape:'arid',trees:'palm'},buildingSet}),b=generateCity({starter,size});assert.deepEqual(a.tiles,b.tiles);assert.deepEqual(a.stats,b.stats);assert.equal(a.funds,b.funds);assert.deepEqual(a.appearance,{landscape:'arid',trees:'palm'});assert.deepEqual(copyBuildingSet(a),buildingSet);const restored=validateSave(JSON.parse(serializeCity(a)));assert.deepEqual(restored.appearance,a.appearance);assert.deepEqual(copyBuildingSet(restored),buildingSet);a.buildingDesigns['5@2x2'].blocks[0]=8;assert.equal(buildingSet.buildingDesigns['5@2x2'].blocks[0],3);}
for(const options of [{appearance:null},{appearance:{landscape:'bad',trees:'palm'}},{buildingSet:[]},{buildingSet:null},{buildingSet:{buildingReplacements:{2:75}}}])assert.throws(()=>generateCity(options));assert.equal(serializeCity(current),original);
let controls,coasts,started=null,closed=0,exports=0,colors=[];
const ctx=new Proxy({clearRect(){},fillRect(){colors.push(this.fillStyle);},createImageData:(w,h)=>({data:new Uint8ClampedArray(w*h*4)})},{get:(o,k)=>o[k]??(()=>{}),set:(o,k,v)=>{o[k]=v;return true;}}),canvas={width:288,height:288,getContext:()=>ctx,getBoundingClientRect:()=>({left:0,top:0,width:288,height:288}),setPointerCapture(){}};
function dialog(_,body){controls=new Map();coasts=[];for(const m of body.matchAll(/<\w+\b([^>]*\bid="([^"]+)"[^>]*)>/g))controls.set(m[2],{value:m[1].match(/value="([^"]*)"/)?.[1]||'',checked:/\bchecked\b/.test(m[1]),disabled:/\bdisabled\b/.test(m[1]),textContent:''});for(const m of body.matchAll(/<select[^>]*id="([^"]+)"[^>]*>([\s\S]*?)<\/select>/g)){const options=[...m[2].matchAll(/<option\b([^>]*)>([^<]*)<\/option>/g)],selected=options.find(o=>/selected/.test(o[1]))||options[0];controls.get(m[1]).value=selected[1].match(/value="([^"]*)"/)?.[1]||selected[2];}for(const m of body.matchAll(/<input[^>]*name="coast"([^>]*)>/g))if(/checked/.test(m[1]))coasts.push({value:m[1].match(/value="([^"]+)"/)[1]});controls.set('terrainPreview',canvas);controls.set('terrainArtworkPreview',{width:540,height:270,getContext:()=>ctx});}
globalThis.document={querySelector:s=>controls.get(s.slice(1)),querySelectorAll:()=>coasts,createElement:()=>({getContext:()=>ctx})};Object.defineProperty(globalThis,'crypto',{value:{getRandomValues:a=>{a[0]=81;return a;}},configurable:true});
const ui={currentCity:current,dialog,close:()=>closed++,start:v=>started=v,exportCity:()=>exports++},get=id=>controls.get('terrain'+id);
showNewCity(ui);get('Center').value='dry';get('-water').value='0';get('-mountains').value='0';get('Options').onchange();
get('Tool').value='raise';canvas.onpointerdown({clientX:144,clientY:144,pointerId:1});canvas.onpointerup({clientX:144,clientY:144});assert.match(get('Summary').textContent,/highest elevation 1/);
get('Appearance').value='alpine';get('TreeStyle').value='conifer';get('BuildingSet').checked=true;get('BuildingSet').onchange();get('ArtworkRotate').onclick();assert.match(get('ArtworkRotate').textContent,/East/);assert.match(get('Summary').textContent,/highest elevation 1/,'artwork changes preserve sculpting');assert.match(get('Summary').textContent,/Evergreen forest/);get('Export').onclick();assert.equal(exports,1);get('Accept').onclick();assert.equal(closed,1);assert.deepEqual(started.appearance,{landscape:'alpine',trees:'conifer'});assert.deepEqual(copyBuildingSet(started),buildingSet);assert.equal(started.tiles[24*48+24].elevation,1);assert.equal(serializeCity(current),original);
showNewCity(ui);get('Appearance').value='lush';get('BuildingSet').checked=true;get('BuildingSet').onchange();get('Regenerate').onclick();get('BuildingSet').checked=false;get('BuildingSet').onchange();get('Accept').onclick();assert.equal(started.seed,81);assert.equal(started.appearance.landscape,'lush');assert.deepEqual(copyBuildingSet(started),{buildingDesigns:{},buildingReplacements:{}});
started=null;showNewCity(ui);get('BuildingSet').checked=true;get('BuildingSet').onchange();get('Cancel').onclick();assert.equal(started,null);assert.equal(serializeCity(current),original);
console.log('PASS: empty/starter new-city artwork across map sizes, unchanged generation/funds, deep-copy inheritance, saved choices, invalid options, actual setup sculpting/style/reuse/regenerate/uncheck/export/accept/cancel controls and unchanged source city.');
