import assert from 'node:assert/strict';
import {createCity,recompute,validateSave} from '../dist/engine.js';
import {serializeCity} from '../dist/save.js';
import {changeCivic} from '../dist/civic.js';
import {analyzeOrdinances,ordinanceSnapshot,ADVISOR_POLICIES} from '../dist/ordinance-analysis.js';
import {showOrdinanceAnalysis,ordinanceComparisonMarkup} from '../dist/ordinance-analysis-ui.js';
import {educationTargets,advanceEducation} from '../dist/education.js';
const city=createCity(),original=serializeCity(city),proposal={...city.civic.ordinances,watch:true,fireCode:true,freeClinics:true,reading:true,juniorSports:true};
const result=analyzeOrdinances(city,proposal);
assert.equal(serializeCity(city),original,'preview must preserve full city, random state, history and funds');
assert.ok(result.after.cost>result.before.cost);assert.ok(result.after.crime<result.before.crime);assert.ok(result.after.flammability<result.before.flammability);
assert.equal(result.after.lifeTarget-result.before.lifeTarget,3);assert.equal(result.after.schoolTarget-result.before.schoolTarget,8);
const enacted=validateSave(JSON.parse(original));changeCivic(enacted,enacted.civic.funding,proposal);recompute(enacted);assert.deepEqual(result.after,ordinanceSnapshot(enacted),'projection matches actual recomputation');
assert.equal(enacted.month,city.month);assert.equal(enacted.funds,city.funds);assert.equal(enacted.civic.lifeExpectancy,city.civic.lifeExpectancy);
const targets=educationTargets(enacted),prior=enacted.civic.ageEducation[0];advanceEducation(enacted);assert.equal(enacted.civic.ageEducation[0],prior+(targets[0]-prior)/36,'displayed target drives learning');
const repeal=analyzeOrdinances(enacted,city.civic.ordinances);assert.ok(repeal.after.cost<repeal.before.cost);assert.throws(()=>analyzeOrdinances(city,{...proposal,watch:'yes'}));
const conservation=analyzeOrdinances(city,{...city.civic.ordinances,powerConservation:true,waterConservation:true,carpool:true});assert.ok(conservation.after.powerDemand<conservation.before.powerDemand);assert.ok(conservation.after.waterDemand<conservation.before.waterDemand);assert.ok(conservation.after.peakTraffic<=conservation.before.peakTraffic);
const empty=createCity('Empty',false),emptyResult=analyzeOrdinances(empty,proposal);assert.equal(emptyResult.after.lifeTarget,null);assert.match(ordinanceComparisonMarkup(emptyResult),/Not applicable/);
assert.deepEqual(ADVISOR_POLICIES.safety,['watch','fireCode','juniorSports']);
let live=city,body='',saved=0,returned=0,cleared=0;const nodes=new Map();globalThis.document={querySelector:s=>{if(!nodes.has(s))nodes.set(s,{checked:false,disabled:true,innerHTML:''});return nodes.get(s);}};
const ui={city:()=>live,dialog:(title,html)=>{body=html;nodes.clear();for(const match of html.matchAll(/id="(comparePolicy-[^"]+)" (checked)?/g))document.querySelector('#'+match[1]).checked=!!match[2];},save:()=>saved++,clearUndo:()=>cleared++,update:()=>{},notify:()=>{}};
showOrdinanceAnalysis(ui,'safety',()=>returned++);assert.match(body,/comparePolicy-watch/);assert.doesNotMatch(body,/comparePolicy-reading/);assert.equal(nodes.get('#applyComparedPolicies').disabled,true);
const toggle=key=>{const n=nodes.get('#comparePolicy-'+key);n.checked=!n.checked;n.onchange();};
toggle('watch');nodes.get('#comparePolicies').onclick();assert.equal(nodes.get('#applyComparedPolicies').disabled,false);assert.match(nodes.get('#policyComparison').innerHTML,/Resident crime/);assert.equal(saved,0);
toggle('fireCode');assert.equal(nodes.get('#applyComparedPolicies').disabled,true);nodes.get('#applyComparedPolicies').onclick();assert.equal(saved,0);
nodes.get('#comparePolicies').onclick();live.funds+=1;nodes.get('#applyComparedPolicies').onclick();assert.equal(saved,0);assert.match(nodes.get('#policyComparison').innerHTML,/city changed/);
nodes.get('#comparePolicies').onclick();const funds=live.funds,month=live.month;nodes.get('#applyComparedPolicies').onclick();assert.equal(saved,1);assert.equal(cleared,1);assert.equal(returned,1);assert.equal(live.civic.ordinances.watch,true);assert.equal(live.civic.ordinances.fireCode,true);assert.equal(live.civic.ordinances.reading,false);assert.equal(live.funds,funds);assert.equal(live.month,month);
showOrdinanceAnalysis(ui,null,()=>returned++);nodes.get('#comparePolicies').onclick();assert.equal(nodes.get('#applyComparedPolicies').disabled,true,'unchanged package cannot apply');assert.match(body,/comparePolicy-trashPresort/);nodes.get('#backPolicyComparison').onclick();assert.equal(returned,2);
console.log('PASS: detached ordinance projections match enactment, shared education targets, repeal, empty cities, advisor scopes, draft invalidation, stale-city protection and explicit application.');
