import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {PLAYTEST_CHECKPOINTS,readPlaytestFeedback,feedbackText,showPlaytestFeedback,showPlaytestRoadmap} from '../dist/playtest-checkpoints.js';
assert.equal(PLAYTEST_CHECKPOINTS.length,8);assert.equal(new Set(PLAYTEST_CHECKPOINTS.map(c=>c.id)).size,8);for(const c of PLAYTEST_CHECKPOINTS)assert.equal(new Set(c.steps.map(([key])=>key)).size,c.id===7?11:3);
const data=new Map([['sims3000.feedback.m5','Existing transport notes <script>'],['sims3000.feedback.checks.m5','["route","route","unknown"]']]),storage={getItem:key=>data.get(key)??null,setItem:(key,value)=>data.set(key,value)};
assert.deepEqual(readPlaytestFeedback(storage,5),{notes:'Existing transport notes <script>',checked:['route']});data.set('sims3000.feedback.checks.m5','invalid');assert.deepEqual(readPlaytestFeedback(storage,5).checked,[]);assert.equal(readPlaytestFeedback({getItem(){throw Error('blocked');}},7).notes,'');
const controls=Object.fromEntries(['reviewNotes','saveReview','exportReview','launchPlaytest','launchBuildingLibrary','launchLandmarks','backPlaytests'].map(k=>[k,{}])),checks=PLAYTEST_CHECKPOINTS[6].steps.map(([key])=>({checked:false,dataset:{playtestStep:key}})),buttons=PLAYTEST_CHECKPOINTS.map(c=>({dataset:{review:String(c.id)}}));globalThis.document={getElementById:id=>controls[id],querySelectorAll:s=>s==='[data-playtest-step]'?checks:buttons};let html='',launch=0,launchTarget,review=0,back=0,download,notice;const ui={storage,dialog:(title,body)=>html=body,notify:message=>notice=message,download:(...args)=>download=args,launch:(id,target)=>{launch=id;launchTarget=target;},roadmap:()=>back++,review:id=>review=id};
showPlaytestFeedback(ui,7);checks[0].checked=true;controls.reviewNotes.value='Roof paint test';controls.saveReview.onclick();assert.deepEqual(readPlaytestFeedback(storage,7),{notes:'Roof paint test',checked:['construct']});assert.equal(data.get('sims3000.feedback.m5'),'Existing transport notes <script>');assert.match(notice,/saved/);checks[1].checked=true;controls.reviewNotes.value='Unsaved newer note';controls.exportReview.onclick();assert.match(download[1],/Unsaved newer note/);assert.match(download[1],/\[x\] Paint one floor/);assert.equal(readPlaytestFeedback(storage,7).notes,'Roof paint test','download does not overwrite saved feedback');controls.launchPlaytest.onclick();assert.equal(launch,7);controls.launchBuildingLibrary.onclick();assert.equal(launchTarget,'library');controls.launchLandmarks.onclick();assert.equal(launchTarget,'landmarks');controls.backPlaytests.onclick();assert.equal(back,1);
showPlaytestRoadmap(ui);assert.match(html,/Eight playable/);assert.match(html,/1 \/ 11 tasks marked tried/);assert.doesNotMatch(html,/<script>/);buttons[7].onclick();assert.equal(review,8);assert.match(feedbackText(8,'Scenario test',['author']),/\[x\] Create a custom goal/);
showPlaytestFeedback({...ui,storage:{getItem(){return null;},setItem(){throw Error('full');}}},1);controls.saveReview.onclick();assert.match(notice,/Download/);delete globalThis.document;
const app=readFileSync(new URL('../dist/app.js',import.meta.url),'utf8');for(const callback of ['showGuide','showUtilities','showBudget','showServices','showTransit','emergencyPanel','scenarioPanel'])assert.ok(app.includes(callback));assert.match(app,/function showGuide\(\)/);assert.match(app,/showPlaytestFeedback\(feedbackUI\(\),milestone\)/);
assert.deepEqual(readPlaytestFeedback(storage,7).checked,['construct']);assert.match(feedbackText(7,'Architecture review',['props','landmarks']),/\[x\] Place and rotate props/);assert.match(feedbackText(7,'Architecture review',['props','landmarks']),/\[x\] Find a landmark/);
console.log('PASS: eight playable feedback checkpoints, legacy note preservation, checked-step validation, local save/export, current draft download, tool launching and storage failure recovery.');

// Execute the app's actual checkpoint router, including menu setup before menu actions.
const routing=[],names=['localStorage','dialog','notify','download','showReview','showRoadmap','showMenu','$','showGuide','showUtilities','showBudget','showServices','showTransit','emergencyPanel','scenarioPanel'];
const helpers=names.map(name=>name==='localStorage'?storage:name==='showMenu'?()=>routing.push('menu'):name==='$'?selector=>({click:()=>routing.push(selector)}):()=>{});
const router=new Function(...names,'return ('+app.match(/function feedbackUI\(\)\{[^\n]+/)[0]+')();')(...helpers);
router.launch(7,'library');router.launch(7,'landmarks');router.launch(7);assert.deepEqual(routing,['menu','#menuBuildingLibrary','menu','#menuLandmarks','#buildingDesignerBtn']);
console.log('PASS: actual architecture checkpoint launch routing opens the menu before library/landmark actions and preserves the designer shortcut.');

assert.ok(!readPlaytestFeedback(storage,7).checked.includes('ground'));assert.match(feedbackText(7,'Ground review',['ground']),/\[x\] Choose a material preview/);

for(const key of ['solid_paint','detail_stroke','construct_navigation'])assert.ok(!readPlaytestFeedback(storage,7).checked.includes(key),'new exercises are not marked tried from prior feedback');
const {importBuildingDesign}=await import('../dist/building-designs.js');
globalThis.document={getElementById:id=>controls[id],querySelectorAll:s=>s==='[data-playtest-step]'?checks:buttons};showPlaytestFeedback(ui,7);const samples=[...html.matchAll(/href="\.\/assets\/building-reviews\/([^"/]+\.building\.json)" download=/g)].map(m=>m[1]);assert.equal(samples.length,3);
const models=samples.map(name=>importBuildingDesign(readFileSync(new URL('../dist/assets/building-reviews/'+name,import.meta.url),'utf8')));assert.equal(models[0].paintColors.length,4);assert.equal(models[1].roofDetails.length,3);assert.ok(models[2].voxels);
assert.match(feedbackText(7,'New tools review',['detail_stroke']),/\[x\] Place and size wall details/);
console.log('PASS: new architecture exercises preserve earlier feedback without marking new work tried, and all three downloadable study models import with their intended features.');

const {validateSave}=await import('../dist/engine.js');const challenge=validateSave(JSON.parse(readFileSync(new URL('../dist/assets/building-reviews/chicago-museum-collection.city.json',import.meta.url),'utf8')));assert.equal(challenge.name,'Chicago museum collection');assert.equal(challenge.scenario.status,'playing');assert.match(html,/chicago-museum-collection\.city\.json/);
console.log('PASS: the checkpoint offers a valid, unstarted Chicago museum city challenge separately from portable building models.');
