import assert from 'node:assert/strict';
import {createPlayPreferences,PLAY_DEFAULTS,showPlayPreferences,automaticDisasterFocus} from '../dist/play-preferences.js';
import {CityRenderer} from '../dist/renderer.js';
import {createCity,build,validateSave,tick} from '../dist/engine.js';
import {serializeCity} from '../dist/save.js';
import {startUfo} from '../dist/ufo.js';
let raw=null;const storage={getItem:()=>raw,setItem:(k,v)=>raw=v};
const preferences=createPlayPreferences(storage);assert.deepEqual(preferences.settings,PLAY_DEFAULTS);
const copy=preferences.settings;copy.vehicleAnimations=false;assert.equal(preferences.settings.vehicleAnimations,true);
assert.ok(preferences.set('autoGoToDisasters',false));assert.equal(createPlayPreferences(storage).settings.autoGoToDisasters,false);
assert.throws(()=>preferences.set('__proto__',true));assert.throws(()=>preferences.set('vehicleAnimations','false'));
raw='{"autoGoToDisasters":false,"vehicleAnimations":"false","sceneryAnimations":false,"unknown":true}';
assert.deepEqual(createPlayPreferences(storage).settings,{constructionDetails:true,autoGoToDisasters:false,vehicleAnimations:true,sceneryAnimations:false,trafficMinZoom:.4,pedestriansVisible:true,pedestrianMinZoom:1});
raw='invalid';assert.deepEqual(createPlayPreferences(storage).settings,PLAY_DEFAULTS);
const unavailable=createPlayPreferences({getItem(){throw Error();},setItem(){throw Error();}});assert.equal(unavailable.set('vehicleAnimations',false),false);assert.equal(unavailable.settings.vehicleAnimations,false);
let focused=0;const focus=()=>focused++;assert.equal(automaticDisasterFocus(preferences,focus),false);assert.equal(focused,0);
preferences.set('autoGoToDisasters',true);assert.equal(automaticDisasterFocus(preferences,focus),true);assert.equal(focused,1);
const nodes={},messages=[];const ctx=()=>new Proxy({},{get:(_,k)=>k.startsWith('create')?()=>({addColorStop(){}}):()=>{},set:()=>true});
globalThis.document={hidden:false,querySelector:s=>nodes[s]||null,createElement:()=>({getContext:ctx})};
const city=createCity('Preferences',false);for(const t of city.tiles)Object.assign(t,{terrain:'land',nature:false,elevation:0});
assert.ok(build(city,'fountain',[{x:24,y:24}]).ok);
for(let x=20;x<27;x++){Object.assign(city.tiles[23*48+x],{type:'road',traffic:40});Object.assign(city.tiles[22*48+x],{rail:true,railRiders:30});}
const saved=serializeCity(city),renderer=Object.create(CityRenderer.prototype);let cars=0,trains=0,arcs=[],icons=[];
const canvasContext=new Proxy(ctx(),{get:(o,k)=>k==='arc'?(...v)=>arcs.push(v):o[k]});
Object.assign(renderer,{ctx:canvasContext,getCity:()=>city,w:1000,h:800,dpr:1,zoom:1,rotation:0,pan:{x:0,y:0},layer:'city',sprites:[],vehicleTime:4,hover:null,drag:null,tool:'query',reducedMotion:{matches:false},drawVehicle:()=>cars++,drawTrain:()=>trains++,sprite:(id)=>icons.push(id)});renderer.center();
showPlayPreferences({preferences,renderer,dialog:(title,html)=>{assert.equal(title,'Play preferences');for(const m of html.matchAll(/id="(pref-[^"]+)"/g))nodes['#'+m[1]]={};},notify:m=>messages.push(m)});
assert.equal(Object.keys(nodes).length,7);
const set=(k,v)=>nodes['#pref-'+k].onchange({target:{checked:v}});
set('vehicleAnimations',false);set('sceneryAnimations',false);set('pedestriansVisible',false);assert.equal(renderer.dirty,true);
renderer.draw();assert.equal(cars,0);assert.equal(trains,0);assert.equal(renderer.harborStats,undefined,'hidden vehicles skip shipping route generation');
const staticArcs=arcs;arcs=[];renderer.vehicleTime=12;renderer.draw();assert.deepEqual(arcs,staticArcs,'scenery-off fountain has a stable pose');
set('pedestriansVisible',true);arcs=[];renderer.draw();assert.deepEqual(arcs,staticArcs,'enabling pedestrians must not override the independent scenery preference');set('pedestriansVisible',false);
set('vehicleAnimations',true);renderer.draw();assert.ok(cars>0&&trains>0,'actual draw dispatches road and rail samples when enabled');assert.equal(renderer.harborStats,city.stats);
nodes['#pref-trafficMinZoom'].onchange({target:{value:'1.5'}});cars=0;trains=0;renderer.draw();assert.equal(cars+trains,0,'100% view hides vehicles below chosen close-view threshold');
renderer.setZoom(1.5);renderer.draw();assert.ok(cars+trains>0,'threshold is inclusive');
renderer.center();nodes['#pref-trafficMinZoom'].onchange({target:{value:'.4'}});
set('sceneryAnimations',true);arcs=[];renderer.draw();assert.notDeepEqual(arcs,staticArcs,'fountain uses animated scene time when enabled');
renderer.reducedMotion.matches=true;arcs=[];renderer.draw();assert.deepEqual(arcs,staticArcs,'system reduced motion overrides decorative animation');
assert.equal(serializeCity(city),saved,'all preferences and draws leave portable city state unchanged');
// Essential emergency graphics remain present with both decorative categories off.
startUfo(city,24,24);set('vehicleAnimations',false);set('sceneryAnimations',false);set('pedestriansVisible',false);icons=[];renderer.draw();assert.ok(icons.includes(71));
// Exercise the real frame clock and refresh scheduling, without a browser.
globalThis.requestAnimationFrame=()=>{};city.emergency.ufo=null;city.emergency.active=false;
Object.assign(renderer,{draw(){},running:true,vehicleTime:0,previousFrame:null,time:0,dirty:false});
renderer.reducedMotion.matches=false;renderer.frame(0);renderer.frame(100);assert.equal(renderer.vehicleTime,0);
set('sceneryAnimations',true);renderer.frame(200);assert.equal(renderer.vehicleTime,.1);
renderer.running=false;renderer.frame(300);assert.equal(renderer.vehicleTime,.1);
renderer.running=true;document.hidden=true;renderer.frame(400);assert.equal(renderer.vehicleTime,.1);
document.hidden=false;nodes['#dialog']={open:true};renderer.frame(500);assert.equal(renderer.vehicleTime,.1);
nodes['#dialog'].open=false;renderer.reducedMotion.matches=true;renderer.frame(600);assert.equal(renderer.vehicleTime,.1);
const a=validateSave(JSON.parse(saved)),b=validateSave(JSON.parse(saved));tick(a);tick(b);assert.deepEqual(a.stats,b.stats);
assert.ok(messages.every(m=>m==='Play preference saved.'));
console.log('PASS: persistent and unavailable-storage preferences, real dialog controls, automatic focus gate, actual vehicle/fountain rendering toggles, essential hazards, reduced motion and paused/hidden/dialog scene clock.');
