import assert from 'node:assert/strict';
import {createCity,build,selection,idx,tick,recompute,validateSave} from '../dist/engine.js';
import {serializeCity} from '../dist/save.js';
import {addConnection,connectionCandidates,signDeal} from '../dist/region.js';
function setup(){const c=createCity('Overload',false);c.month=360;for(const t of c.tiles){t.terrain='land';t.nature=false;}assert.ok(build(c,'wind',[{x:20,y:20}]).ok);assert.ok(build(c,'residential',selection('residential',{x:21,y:20},{x:26,y:24})).ok);assert.ok(build(c,'park',[{x:19,y:20}]).ok);return c;}
const c=setup(),root=c.tiles[idx(20,20)];assert.equal(c.stats.overloadedPlants,1);assert.equal(root.plantLoad,1.2);for(let i=0;i<5;i++){assert.equal(tick(c).powerFailures.length,0);assert.equal(root.stress,i+1);}const saved=validateSave(JSON.parse(serializeCity(c)));assert.equal(saved.tiles[idx(20,20)].stress,5);const result=tick(c);tick(saved);assert.equal(result.powerFailures.length,1);assert.equal(c.stats.plants,0);assert.equal(root.rubble,true);assert.equal(c.emergency.active,true);assert.ok(c.tiles[idx(19,20)].fire>0);assert.equal(serializeCity(saved),serializeCity(c),'overload countdown and failure survive save/load');
const relieved=setup();for(let i=0;i<3;i++)tick(relieved);assert.equal(relieved.tiles[idx(20,20)].stress,3);build(relieved,'wind',[{x:19,y:21}]);tick(relieved);assert.equal(relieved.tiles[idx(20,20)].stress,0);for(let i=0;i<8;i++)tick(relieved);assert.equal(relieved.stats.plants,2,'sufficient connected capacity prevents failure');
const isolated=setup();build(isolated,'wind',[{x:40,y:40}]);for(let i=0;i<6;i++)tick(isolated);assert.equal(isolated.tiles[idx(20,20)].rubble,true);assert.equal(isolated.tiles[idx(40,40)].type,'wind','unconnected spare capacity cannot rescue an overloaded grid');
const imported=setup();build(imported,'powerline',selection('powerline',{x:0,y:18},{x:20,y:18}));const con=connectionCandidates(imported).find(p=>p.kind==='power');assert.ok(addConnection(imported,con).ok);assert.ok(signDeal(imported,0,'power','import',50).ok);recompute(imported);assert.equal(imported.stats.overloadedPlants,0);for(let i=0;i<8;i++)tick(imported);assert.equal(imported.stats.plants,1,'imported deficit supply relieves native overload');
const exportCity=setup();build(exportCity,'wind',[{x:19,y:21}]);build(exportCity,'powerline',selection('powerline',{x:0,y:18},{x:20,y:18}));addConnection(exportCity,connectionCandidates(exportCity).find(p=>p.kind==='power'));signDeal(exportCity,0,'power','export',25);recompute(exportCity);assert.equal(exportCity.region.deals[0].failed,true,'unfulfillable export rejected by capacity logic');assert.equal(exportCity.stats.overloadedPlants,0,'failed exports do not add fictitious load');
console.log('PASS: six-month overload failure, warnings/load, adjacent ignition, saved countdown, added capacity recovery, isolated capacity, import relief and failed-export load accounting.');
