import assert from 'node:assert/strict';
import {createCity,build,idx,recompute,tick,validateSave} from '../dist/engine.js';
import {POWER_PLANTS,plantCapacity} from '../dist/power.js';
import {serializeCity} from '../dist/save.js';
import {ignite,stepFire} from '../dist/emergency.js';
function base(){const c=createCity('Power test',false);for(const t of c.tiles){t.terrain='land';t.nature=false;}c.funds=1000000;return c;}
for(const [type,def] of Object.entries(POWER_PLANTS)){const c=base();if(def.year>1950){c.month=(def.year-1950)*12-1;assert.equal(build(c,type,[{x:20,y:20}]).ok,false,type+' locked before invention');}c.month=Math.max(0,(def.year-1950)*12);const before=c.funds;assert.ok(build(c,type,[{x:20,y:20}]).ok);assert.equal(c.funds,before-def.cost);assert.equal(c.tiles.filter(t=>t.type===type).length,def.size**2);assert.equal(c.stats.plants,1);assert.equal(c.stats.powerCapacity,def.capacity);assert.equal(c.stats.powerUpkeep,def.upkeep);assert.equal(c.tiles[idx(20,20)].airPollution,def.air);assert.ok(build(c,'residential',[{x:19,y:20}]).ok);assert.equal(c.tiles[idx(19,20)].powered,true);const restored=validateSave(JSON.parse(serializeCity(c)));assert.deepEqual(restored.stats,c.stats);for(const t of c.tiles)if(t.type===type)t.age=600;recompute(c);assert.equal(c.stats.powerCapacity,Math.round(def.capacity*.25));const age=c.tiles[idx(20,20)].age;tick(c);assert.equal(c.tiles[idx(20,20)].age,age+1);assert.ok(build(c,'bulldoze',[{x:20+def.size-1,y:20+def.size-1}]).ok);assert.equal(c.stats.plants,0);assert.equal(c.tiles.filter(t=>t.type===type).length,0);}
const small=base();small.month=360;build(small,'wind',[{x:20,y:20}]);for(let x=21;x<25;x++){build(small,'residential',[{x,y:20}],3);small.tiles[idx(x,20)].level=3;}recompute(small);const powered=small.stats.powered;small.tiles[idx(20,20)].age=600;recompute(small);assert.ok(small.stats.powered<powered,'aging causes grid capacity blackouts');const isolated=small.tiles[idx(40,40)];isolated.type='commercial';recompute(small);assert.equal(isolated.powered,false,'a plant cannot supply a disconnected grid');
const damaged=base();damaged.month=180;build(damaged,'nuclear',[{x:20,y:20}]);ignite(damaged,22,22);assert.equal(build(damaged,'bulldoze',[{x:20,y:20}]).ok,false);const burning=damaged.tiles[idx(22,22)];burning.fire=100;burning.fireAge=100;stepFire(damaged);recompute(damaged);assert.equal(damaged.stats.plants,0);assert.equal(damaged.tiles.filter(t=>t.rubble).length,16,'fire destroys complete plant footprint');
const edge=base();edge.month=1200;assert.equal(build(edge,'fusion',[{x:46,y:46}]).ok,false);build(edge,'gas',[{x:20,y:20}]);const malformed=JSON.parse(serializeCity(edge));malformed.tiles[idx(21,21)].type=null;assert.throws(()=>validateSave(malformed),/plant footprint/);
console.log('PASS: all plant technology dates, cost/footprints, electrical supply, pollution/upkeep, aging/blackouts, isolated grids, full demolition/fire damage, save roundtrips and malformed footprints.');
