import assert from 'node:assert/strict';
import {createCity,build,selection,recompute,validateSave} from '../dist/engine.js';
import {SERVICE_JOBS} from '../dist/civic-jobs.js';
import {serializeCity} from '../dist/save.js';
import {civicFacilityReport} from '../dist/civic-service-report.js';
const setup=()=>{const c=createCity('Public jobs',false);c.funds=100000;for(const t of c.tiles)Object.assign(t,{terrain:'land',elevation:0,nature:false});for(const [tool,a,b] of [['coal',{x:35,y:15}],['powerline',{x:8,y:16},{x:34,y:16}],['road',{x:8,y:20},{x:30,y:20}],['residential',{x:8,y:18},{x:23,y:18}]])assert.ok(build(c,tool,selection(tool,a,b||a)).ok);for(const t of c.tiles)if(t.type==='residential'){t.level=1;t.age=10;}recompute(c);return c;};
for(const [type,jobs] of Object.entries(SERVICE_JOBS)){const c=setup();assert.equal(c.stats.jobs,0);assert.ok(build(c,type,[{x:27,y:17}]).ok);const t=c.tiles[17*48+27];assert.equal(c.stats.civicJobs,jobs,type);assert.equal(c.stats.civicEmployed,jobs,type);assert.equal(c.stats.jobs,jobs);assert.equal(t.civicEmployed,jobs);assert.equal(c.stats.commercialEmployed,0);assert.equal(c.stats.industrialEmployed,0);assert.ok(c.stats.peakTraffic>0);assert.match(civicFacilityReport(c,t),new RegExp(`${jobs} / ${jobs} operating jobs filled`));const saved=validateSave(JSON.parse(serializeCity(c)));assert.equal(saved.stats.civicEmployed,jobs);t.fire=10;recompute(c);assert.equal(c.stats.civicJobs,0);assert.equal(t.civicEmployed,0);t.fire=0;recompute(c);assert.equal(c.stats.civicJobs,jobs);c.civic.funding.education=0;if(['school','college','library','museum'].includes(type)){recompute(c);assert.equal(c.stats.civicJobs,0);}}
const c=setup();build(c,'hospital',[{x:27,y:17}]);build(c,'school',[{x:30,y:17}]);assert.equal(c.stats.civicJobs,90);assert.ok(Math.abs(c.stats.civicEmployed-c.stats.commuters)<1e-9);assert.ok(c.stats.unemployed<1e-9);assert.ok(c.stats.civicEmployed<90,'vacancies remain when available workers run out');assert.equal(c.tiles.reduce((sum,t)=>sum+(t.civicEmployed||0),0),c.stats.civicEmployed);
console.log('PASS: all eight services offer finite jobs and real road commutes, no cross-sector double counting, vacancy conservation, damaged/funding shutdown, inspection and save continuity.');
const r=createCity('Rail public jobs',false);r.funds=100000;for(const t of r.tiles)Object.assign(t,{terrain:'land',elevation:0,nature:false});Object.assign(r.tiles[18*48+12],{type:'residential',level:3,density:3});for(const [tool,x,y] of [['coal',34,10],['road',38,17],['school',34,16]])assert.ok(build(r,tool,[{x,y}]).ok);assert.ok(build(r,'powerline',selection('powerline',{x:12,y:15},{x:33,y:15})).ok);assert.ok(build(r,'rail',selection('rail',{x:12,y:20},{x:38,y:20})).ok);assert.ok(build(r,'trainStation',[{x:12,y:19}]).ok);assert.ok(build(r,'trainStation',[{x:34,y:19}]).ok);assert.equal(r.stats.civicJobs,45);assert.ok(r.stats.civicEmployed>0);assert.equal(r.stats.civicEmployed,r.stats.trainRiders);assert.equal(r.tiles[18*48+12].roadAccess,false);assert.ok(build(r,'removeRail',[{x:25,y:20}]).ok);assert.equal(r.stats.civicJobs,45);assert.equal(r.stats.civicEmployed,0);
