import {freshDemographics} from '../dist/demographics.js';
import assert from 'node:assert/strict';
import {createCity,build,selection,recompute,idx,validateSave} from '../dist/engine.js';
import {changeTransit,advanceTransit} from '../dist/transport.js';
function base(){const c=createCity('Rail',false);for(const t of c.tiles){t.terrain='land';t.nature=false;}const h=c.tiles[idx(12,18)],w=c.tiles[idx(36,18)];h.type='residential';h.level=3;h.density=3;w.type='industrial';w.level=3;w.density=3;c.demographics=freshDemographics(64,0);return c;}
const place=(c,tool,x,y)=>assert.ok(build(c,tool,[{x,y}]).ok,tool);
const line=(c,tool,x1,y1,x2,y2)=>assert.ok(build(c,tool,selection(tool,{x:x1,y:y1},{x:x2,y:y2})).ok,tool);
const c=base();line(c,'rail',12,20,36,20);assert.equal(c.stats.trainRiders,0,'track alone has no access');place(c,'trainStation',12,19);assert.equal(c.stats.trainRiders,0,'destination station is required');place(c,'trainStation',36,19);assert.equal(c.stats.trainRiders,32,'rail connects homes to jobs without road');assert.equal(c.stats.unemployed,0);assert.equal(c.tiles[idx(24,20)].railRiders,32);assert.equal(c.tiles[idx(12,19)].stationRiders,32);assert.equal(c.tiles[idx(12,18)].access,true);
place(c,'removeRail',24,20);assert.equal(c.stats.trainRiders,0);assert.equal(c.tiles[idx(12,18)].access,false);place(c,'rail',24,20);assert.equal(c.stats.trainRiders,32);
const s=base();line(s,'subway',12,20,36,20);place(s,'subwayStation',12,20);place(s,'subwayStation',36,20);assert.equal(s.stats.trainRiders,32);place(s,'pipe',24,20);place(s,'road',24,20);place(s,'removeSubway',24,20);assert.equal(s.tiles[idx(24,20)].type,'road');assert.equal(s.tiles[idx(24,20)].pipe,true);assert.equal(s.stats.trainRiders,0);place(s,'subway',24,20);assert.equal(s.stats.trainRiders,32);
const t=base();line(t,'rail',12,20,24,20);line(t,'subway',24,21,36,21);place(t,'trainStation',12,19);place(t,'subwayStation',36,20);assert.equal(t.stats.trainRiders,0,'adjacent rail and subway do not connect by themselves');place(t,'railTransfer',24,21);assert.equal(t.stats.trainRiders,32,'transfer joins above/below-ground routes');assert.ok(t.tiles[idx(25,21)].subwayRiders>0);assert.equal(t.tiles[idx(24,21)].stationRiders,32,'transfer station counts passing passengers');place(t,'bulldoze',24,21);assert.equal(t.tiles[idx(24,21)].subway,true,'surface demolition preserves subway');assert.equal(t.stats.trainRiders,0);
changeTransit(c,0);recompute(c);assert.equal(c.stats.trainRiders,0);for(let i=0;i<6;i++){advanceTransit(c);recompute(c);}assert.equal(c.stats.transitStrike,true);changeTransit(c,100);advanceTransit(c);recompute(c);assert.ok(c.stats.trainRiders>0);
const b=base();for(let x=23;x<27;x++)b.tiles[idx(x,20)].terrain='water';line(b,'rail',12,20,36,20);place(b,'trainStation',12,19);place(b,'trainStation',36,19);assert.equal(b.stats.trainRiders,32);assert.equal(b.tiles[idx(24,20)].railAxis,'x');assert.equal(build(b,'road',selection('road',{x:22,y:20},{x:27,y:20})).ok,false,'separate road and rail bridge spans');
const loaded=validateSave(JSON.parse(JSON.stringify(b)));assert.deepEqual(loaded.stats,b.stats);assert.equal(loaded.tiles[idx(24,20)].rail,true);const old=createCity();old.version=5;for(const t of old.tiles){delete t.rail;delete t.subway;}assert.equal(validateSave(old).tiles.some(t=>t.rail||t.subway),false);const bad=JSON.parse(JSON.stringify(b));bad.tiles[idx(24,20)].railAxis='bad';assert.throws(()=>validateSave(bad));
console.log('PASS: rail/subway station requirements, no-road job access, track ridership, disconnections, transfer-only mode connections, separate underground removal, strikes, rail bridges, independent bridge spans, saves and migration.');
