import assert from 'node:assert/strict';
import {recentDevelopment,constructionEdges,drawRecentConstruction,recentConstructionNote} from '../dist/recent-construction.js';
import {createPlayPreferences} from '../dist/play-preferences.js';
const t={x:4,y:6,type:'residential',industry:'dirty',level:1,age:0};assert.ok(recentDevelopment(t));assert.ok(recentDevelopment({...t,age:1}));assert.equal(recentDevelopment({...t,age:2}),false);
for(const change of [{level:0},{historicalLevel:1},{abandonedLevel:1},{fire:1},{rubble:true},{radiation:true},{industry:'farm'},{type:'road'}])assert.equal(recentDevelopment({...t,...change}),false);
let fills=0,saved=0,restored=0;const ctx={save:()=>saved++,restore:()=>restored++,beginPath(){},moveTo(x,y){assert.ok(Number.isFinite(x+y));},lineTo(x,y){assert.ok(Number.isFinite(x+y));},closePath(){},fill:()=>fills++,stroke(){}};
for(let rotation=0;rotation<4;rotation++){const transform=(x,y)=>[[x,y],[-y,x],[-x,-y],[y,-x]][rotation],r={unit:24,ctx,layer:'city',preferences:{},transform,project:(x,y)=>{const [a,b]=transform(x,y);return{x:(a-b)*24,y:(a+b)*12-48};}};const edges=constructionEdges(r,t,3,2);assert.equal(edges.length,2);for(const edge of edges)assert.ok(Math.abs(edge.a.x-edge.b.x)<=24);const before=JSON.stringify(t);drawRecentConstruction(r,t,{width:3,height:2});assert.equal(JSON.stringify(t),before);const count=fills;r.layer='power';drawRecentConstruction(r,t);assert.equal(fills,count);r.layer='city';r.preferences.constructionDetails=false;drawRecentConstruction(r,t);assert.equal(fills,count);}
assert.ok(fills>0);assert.equal(saved,restored);assert.match(recentConstructionNote(t),/do not delay occupancy/);assert.equal(recentConstructionNote({...t,age:2}),'');const store=new Map(),storage={getItem:k=>store.get(k),setItem:(k,v)=>store.set(k,v)},prefs=createPlayPreferences(storage);assert.equal(prefs.settings.constructionDetails,true);prefs.set('constructionDetails',false);assert.equal(createPlayPreferences(storage).settings.constructionDetails,false);
console.log('PASS: recent-development cues expire with growth age, exclude hazards and farms, project correctly in four views, preserve state and respect display preferences and data layers.');
