import assert from 'node:assert/strict';
import {generateCity} from '../dist/terrain-generator.js';
import {build,planBuild,idx,recompute,validateSave} from '../dist/engine.js';
import {RECREATION} from '../dist/recreation.js';
import {ignite,stepFire} from '../dist/emergency.js';
import {advanceCivic} from '../dist/civic.js';
import {serializeCity} from '../dist/save.js';
const base=()=>generateCity({water:0,trees:0,mountains:0});
for(const [type,d] of Object.entries(RECREATION)){const c=base();if(type==='marina')c.tiles[idx(19,21)].terrain='water';const funds=c.funds;assert.ok(build(c,type,[{x:20,y:20}]).ok,type);assert.equal(c.tiles.filter(t=>t.type===type).length,d.size*d.size);assert.equal(c.funds,funds-d.cost);assert.equal(c.stats.recreationUpkeep,d.upkeep);assert.equal(c.stats.spending.parks,d.upkeep);assert.equal(c.stats.plants,0);assert.equal(c.stats.powerCapacity,0);const saved=validateSave(JSON.parse(serializeCity(c)));assert.deepEqual(saved.stats,c.stats);if(d.size>1){const bad=JSON.parse(serializeCity(c));bad.tiles[idx(21,20)].type=null;assert.throws(()=>validateSave(bad));}assert.ok(build(c,'bulldoze',[{x:20+d.size-1,y:20+d.size-1}]).ok);assert.equal(c.stats.recreationCount,0);assert.equal(c.stats.spending.parks,0);}
const marina=base();assert.equal(planBuild(marina,'marina',[{x:20,y:20}]).ok,false);marina.tiles[idx(19,19)].terrain='water';assert.equal(planBuild(marina,'marina',[{x:20,y:20}]).ok,false,'diagonal water is insufficient');marina.tiles[idx(19,20)].terrain='water';assert.equal(planBuild(marina,'marina',[{x:20,y:20}]).ok,true);marina.tiles[idx(21,21)].elevation=1;assert.equal(planBuild(marina,'marina',[{x:20,y:20}]).ok,false);
const c=base();build(c,'residential',[{x:19,y:21}]);c.tiles[idx(19,21)].level=1;recompute(c);const value=c.tiles[idx(19,21)].landValue,health=c.civic.lifeExpectancy;build(c,'sportsPark',[{x:20,y:20}]);assert.ok(c.tiles[idx(19,21)].landValue>value);assert.ok(c.stats.recreationHealth>0);advanceCivic(c);assert.ok(c.civic.lifeExpectancy>health);const demand=c.stats.demand.residential;build(c,'zoo',[{x:30,y:20}]);assert.equal(c.stats.activeZoos,1);assert.ok(c.stats.demand.residential>demand);ignite(c,31,21);recompute(c);assert.equal(c.stats.activeZoos,0,'burning sites lose their benefit');assert.equal(build(c,'bulldoze',[{x:30,y:20}]).ok,false,'whole footprint protected during fire');for(let i=0;i<100&&c.emergency.active;i++)stepFire(c);recompute(c);assert.equal(c.tiles.filter(t=>t.type==='zoo').length,0,'fire destroys entire site');assert.ok(validateSave(JSON.parse(serializeCity(c))));
console.log('PASS: recreation catalog, footprint/cost/upkeep, no accidental generation, saves, full demolition, shoreline and slope rules, neighborhood health/value, zoo demand and whole-site fire damage.');
