import assert from 'node:assert/strict';
import {allocateUtilityContracts,disposalContractOrder} from '../dist/regional-allocation.js';
const imports=[{id:1,direction:'import',rate:2,amount:50},{id:2,direction:'import',rate:1,amount:50},{id:3,direction:'import',rate:1,amount:50}],supply=d=>({1:100,2:30,3:40})[d.id];
const unchanged=JSON.stringify(imports),r=allocateUtilityContracts(imports,20,100,supply);assert.equal(r.imported,80);assert.equal(r.capacity,100);assert.equal(r.unmetDemand,0);assert.equal(r.deliveries.get(2),30);assert.equal(r.deliveries.get(3),40);assert.equal(r.deliveries.get(1),10);assert.equal(JSON.stringify(imports),unchanged);
for(const deals of [[imports[2],imports[0],imports[1]],[...imports].reverse()]){const result=allocateUtilityContracts(deals,20,100,supply);assert.equal(result.capacity,r.capacity);for(const [id,amount]of r.deliveries)assert.equal(result.deliveries.get(id),amount);}
const short=allocateUtilityContracts(imports,0,200,supply);assert.equal(short.imported,170);assert.equal(short.unmetDemand,30);assert.equal(short.failed.size,0,'a neighbor running short is not a player export failure');
const exports=[{id:4,direction:'export',amount:50,rate:1},{id:5,direction:'export',amount:25,rate:2},{id:6,direction:'export',amount:100,rate:3}];const out=allocateUtilityContracts([...exports].reverse(),180,100,()=>0);assert.equal(out.exported,75);assert.equal(out.capacity,105);assert.deepEqual([...out.failed],[6]);assert.equal(out.deliveries.get(4),50);assert.equal(out.deliveries.get(5),25);
const mixed=allocateUtilityContracts([...imports,...exports],20,100,supply);assert.equal(mixed.imported,80);assert.equal(mixed.exported,0);assert.equal(mixed.failed.size,3,'bought deficit supply cannot be resold as local surplus');
const local=allocateUtilityContracts([...imports,...exports],180,100,supply);assert.equal(local.imported,0);assert.equal(local.exported,75);for(const d of imports)assert.equal(local.deliveries.get(d.id),0);
assert.equal(allocateUtilityContracts([],10,30,()=>0).unmetDemand,20);assert.throws(()=>allocateUtilityContracts(imports,0,10,()=>NaN));assert.throws(()=>allocateUtilityContracts([],Infinity,10,()=>0));assert.deepEqual(disposalContractOrder(imports).map(d=>d.id),[2,3,1]);assert.equal(JSON.stringify(imports),unchanged);
console.log('PASS: conserved network-local multi-neighbor utility allocation, cheapest import priority, stable export seniority, shortage handling, no deficit re-export, order independence and immutable inputs.');
