import assert from 'node:assert/strict';
import {createCity,build,selection,idx,recompute,tick,validateSave} from '../dist/engine.js';
import {addConnection,connectionCandidates} from '../dist/region.js';
import {serializeCity} from '../dist/save.js';
import {regionalMarketAccess,marketAccessDescription} from '../dist/regional-market-access.js';
const base=()=>{const c=createCity('Markets',false);for(const t of c.tiles){t.terrain='land';t.nature=false;}return c;};
const line=(c,type,x,y,xx,yy)=>assert.ok(build(c,type,selection(type,{x,y},{x:xx,y:yy})).ok,type);
const zone=(c,x,y,type='commercial')=>{const t=c.tiles[idx(x,y)];t.type=type;return t;};
const connect=(c,kind,x,y)=>{assert.ok(addConnection(c,connectionCandidates(c).find(p=>p.kind===kind&&p.tile===idx(x,y))).ok);recompute(c);};
const c=base(),shop=zone(c,20,19),remote=zone(c,8,8);line(c,'road',20,20,24,20);line(c,'road',46,20,47,20);connect(c,'road',47,20);assert.equal(shop.marketDemandBonus,0,'isolated border stub gives no local boost');line(c,'road',24,20,46,20);assert.equal(shop.marketDemandBonus,3);assert.equal(remote.marketDemandBonus,0);assert.equal(c.stats.marketDemandBonus.commercial,1.5,'city indicator averages actual access');assert.match(marketAccessDescription(shop),/east neighbor/);assert.match(marketAccessDescription(remote),/No reachable/);
line(c,'road',46,21,47,21);connect(c,'road',47,21);assert.equal(shop.marketDemandBonus,3,'duplicate neighbor counted once');line(c,'road',25,0,25,20);connect(c,'road',25,0);assert.equal(shop.marketDemandBonus,6);assert.ok(build(c,'bulldoze',[{x:25,y:10}]).ok);assert.equal(shop.marketDemandBonus,3);assert.ok(build(c,'bulldoze',[{x:35,y:20}]).ok);assert.equal(shop.marketDemandBonus,0,'route break removes access');
const h=base(),hs=zone(h,12,16);line(h,'road',12,17,12,22);line(h,'highway',12,20,47,20);connect(h,'highway',47,20);assert.equal(hs.marketDemandBonus,0);assert.ok(build(h,'ramp',[{x:13,y:21}]).ok);assert.equal(hs.marketDemandBonus,3);build(h,'bulldoze',[{x:13,y:21}]);assert.equal(hs.marketDemandBonus,0);
const r=base(),rs=zone(r,30,23,'industrial');line(r,'rail',30,20,47,20);build(r,'trainStation',[{x:30,y:21}]);connect(r,'rail',47,20);assert.equal(rs.marketDemandBonus,3,'nearby active station carries freight');build(r,'removeRail',[{x:40,y:20}]);assert.equal(rs.marketDemandBonus,0);line(r,'rail',40,20,40,20);r.transport.funding=0;recompute(r);assert.equal(rs.marketDemandBonus,0,'inactive station cannot carry freight');
const a=base();for(let y=0;y<48;y++)a.tiles[idx(18,y)].terrain='water';build(a,'pump',[{x:19,y:21}]);line(a,'pipe',19,21,23,21);line(a,'road',24,20,24,25);build(a,'coal',[{x:26,y:20}]);line(a,'airport',20,20,22,24);const as=zone(a,25,24),isolated=zone(a,5,5);for(let i=0;i<6;i++)tick(a);assert.equal(a.stats.activeAirports,1);assert.equal(as.marketDemandBonus,20);assert.equal(isolated.marketDemandBonus,0);const raw=serializeCity(a);assert.ok(!raw.includes('marketDemandBonus'));const saved=validateSave(JSON.parse(raw));assert.deepEqual(saved.stats,a.stats);recompute(a);assert.equal(serializeCity(a),raw,'recompute is observational');const old=JSON.parse(raw);old.version=87;assert.deepEqual(validateSave(old).stats,a.stats);build(a,'bulldoze',[{x:26,y:20}]);assert.equal(as.marketDemandBonus,0,'service loss removes operating airport benefit');
// Port routing consumes the same operating footprint data produced by facilities.
const p=base(),ps=zone(p,5,5,'industrial'),pf=zone(p,35,35,'industrial');ps.roadIds=[7];pf.roadIds=[8];p.tiles[0].roadIds=[7];p.stats.facilityPlots=[{type:'seaport',operating:true,ids:[0]}];regionalMarketAccess(p);assert.equal(ps.marketDemandBonus,20);assert.equal(pf.marketDemandBonus,0);p.stats.facilityPlots[0].operating=false;regionalMarketAccess(p);assert.equal(ps.marketDemandBonus,0);
console.log('PASS: reachable markets, broken and duplicate border routes, highway ramps, active rail freight, isolated districts, operating facilities, city averages, persistence and legacy migration.');
