import assert from 'node:assert/strict';
import {createCity,build,selection,idx,recompute,tick,validateSave} from '../dist/engine.js';
import {connectionCandidates,addConnection,signDeal,cancelDeal,terminationFee} from '../dist/region.js';
function base(){const c=createCity('Neighbors',false);for(const t of c.tiles){t.terrain='land';t.nature=false;}return c;}
function connect(c,kind){const p=connectionCandidates(c).find(p=>p.kind===kind);assert.ok(p,kind+' border route');assert.ok(addConnection(c,p).ok);return c.region.connections.length-1;}
const c=base();build(c,'powerline',selection('powerline',{x:42,y:20},{x:47,y:20}));const h=c.tiles[idx(40,20)];h.type='residential';h.level=1;const far=c.tiles[idx(20,20)];far.type='residential';far.level=1;recompute(c);const con=connect(c,'power');assert.ok(signDeal(c,con,'power','import',50).ok);recompute(c);assert.equal(h.powered,true);assert.equal(far.powered,false,'remote disconnected deficit cannot be imported');assert.equal(c.region.deals[0].delivered,2);assert.equal(c.stats.regionExpense,10,'minimum fee applies');const cash=c.funds,baseBalance=c.stats.balance;tick(c);assert.equal(c.funds,cash+baseBalance);assert.equal(c.history.at(-1).expenses,c.stats.expenses);assert.equal(signDeal(c,con,'power','export',50).ok,false,'no simultaneous opposing resource deals');
const fee=terminationFee(c,c.region.deals[0]);const before=c.funds;assert.equal(cancelDeal(c,c.region.deals[0].id).fee,fee);assert.equal(c.funds,before-fee);assert.ok(signDeal(c,con,'power','import',50).ok);c.month+=12;assert.equal(terminationFee(c,c.region.deals[0]),0);assert.equal(cancelDeal(c,c.region.deals[0].id).fee,0);
assert.ok(build(c,'coal',[{x:35,y:18}]).ok);assert.ok(signDeal(c,con,'power','export',50).ok);recompute(c);assert.equal(c.region.deals[0].failed,false);assert.equal(c.stats.regionIncome,20);build(c,'bulldoze',[{x:35,y:18}]);assert.equal(c.region.deals[0].failed,true);const funds=c.funds,result=tick(c);assert.equal(result.failedDeals,1);assert.equal(result.regionalPenalty,240);assert.equal(c.region.deals.length,0);assert.equal(c.funds,funds+c.history.at(-1).income-c.history.at(-1).expenses-result.regionalPenalty);
const w=base();build(w,'pipe',selection('pipe',{x:42,y:20},{x:47,y:20}));w.tiles[idx(40,20)].type='residential';w.tiles[idx(40,20)].level=1;recompute(w);const wc=connect(w,'water');signDeal(w,wc,'water','import',50);recompute(w);assert.equal(w.tiles[idx(40,20)].watered,true);assert.equal(w.region.deals[0].delivered,4);assert.equal(w.stats.waterUsed,4);assert.equal(w.stats.regionExpense,10);build(w,'removePipe',[{x:45,y:20}]);assert.equal(w.tiles[idx(40,20)].watered,true,'remaining supplied border pipes can still cover nearby land');build(w,'removePipe',[{x:47,y:20}]);const wr=tick(w);assert.equal(wr.failedDeals,1,'connection loss ends contract');
const g=base();build(g,'road',selection('road',{x:35,y:20},{x:47,y:20}));const gh=g.tiles[idx(37,19)];gh.type='residential';gh.level=1;g.tiles[idx(38,19)].type='industrial';g.tiles[idx(38,19)].level=1;recompute(g);const gc=connect(g,'road');signDeal(g,gc,'garbage','export',50);gh.waste=50;recompute(g);tick(g);assert.equal(g.stats.uncollectedWaste,0);assert.ok(g.history.at(-1).expenses>=100,'actual excess garbage drives bill');cancelDeal(g,g.region.deals[0].id);build(g,'landfill',[{x:36,y:21}]);signDeal(g,gc,'garbage','import',25);recompute(g);tick(g);assert.ok(g.tiles[idx(36,21)].garbage>=25);assert.equal(g.stats.regionIncome,50);const loaded=validateSave(JSON.parse(JSON.stringify(g)));assert.deepEqual(loaded.region,g.region);assert.deepEqual(loaded.stats,g.stats);
const fake=JSON.parse(JSON.stringify(g));fake.region.deals[0].rate=99999;assert.equal(validateSave(fake).region.deals[0].rate,2,'import cannot forge contract rates');
const island=base();island.tiles[idx(47,20)].terrain='water';island.tiles[idx(47,20)].pipe=true;assert.equal(connectionCandidates(island).some(p=>p.kind==='water'),false,'utility border connections require dry land');
const ew=base();ew.tiles[idx(43,21)].terrain='water';build(ew,'pump',[{x:44,y:21}]);build(ew,'coal',[{x:38,y:19}]);build(ew,'pipe',selection('pipe',{x:44,y:21},{x:47,y:21}));recompute(ew);const ewc=connect(ew,'water');signDeal(ew,ewc,'water','export',25);recompute(ew);assert.equal(ew.region.deals[0].delivered,25);assert.equal(ew.stats.regionIncome,5);build(ew,'removePipe',[{x:45,y:21}]);assert.equal(ew.region.deals[0].failed,true,'disconnected pump cannot supply water export');
const freight=base();build(freight,'rail',selection('rail',{x:30,y:20},{x:47,y:20}));build(freight,'trainStation',[{x:30,y:21}]);build(freight,'road',selection('road',{x:30,y:22},{x:34,y:22}));build(freight,'landfill',[{x:33,y:23}]);const fc=connect(freight,'rail');signDeal(freight,fc,'garbage','import',25);recompute(freight);tick(freight);assert.ok(freight.tiles[idx(33,23)].garbage>=25,'rail freight transfers through station onto local roads');
console.log('PASS: connected deficit imports, isolated networks, minimum fees, monthly accounting, duplicate-resource prevention, cancellation/review fees, export shortfall penalties, water delivery/connection loss, garbage export actual billing/import storage, saves and validated contract rates.');
