import assert from 'node:assert/strict';
import {generateCity} from '../dist/terrain-generator.js';
import {REWARDS,advanceRewards,freshRewards,rewardActive} from '../dist/rewards.js';
import {build,idx,recompute,validateSave,selection,tick} from '../dist/engine.js';
import {serializeCity} from '../dist/save.js';
const c=generateCity({water:0,mountains:0,trees:0});assert.equal(build(c,'mayorHouse',[{x:20,y:20}]).ok,false);Object.assign(c.stats,{population:150000,aura:95,balance:100,education:70,activeServices:{college:1}});c.month=1;advanceRewards(c);assert.equal(c.rewards.streaks.mayorHouse,1);advanceRewards(c);assert.equal(c.rewards.streaks.mayorHouse,1,'same month cannot count twice');c.month++;c.stats.aura=20;advanceRewards(c);assert.equal(c.rewards.streaks.mayorHouse,1,'earned offer stays recorded');c.stats.aura=60;const offers=[];for(let i=0;i<6;i++){c.month++;offers.push(...advanceRewards(c));}assert.deepEqual(offers,[]);c.stats.population=0;c.month++;assert.deepEqual(advanceRewards(c),[]);assert.ok(c.rewards.earned.mayorHouse!==null,'earned offers are retained');
for(const k of Object.keys(REWARDS)){const city=generateCity({startYear:2000,water:0,mountains:0,trees:0});city.funds=50000+2*REWARDS[k].cost;city.rewards.earned[k]=0;build(city,'solar',[{x:10,y:20}]);build(city,'powerline',selection('powerline',{x:14,y:20},{x:19,y:20}));build(city,'road',selection('road',{x:20,y:19},{x:25,y:19}));const base=city.stats.demand.residential;assert.ok(build(city,k,[{x:20,y:20}]).ok);assert.equal(city.stats.rewardUpkeep,REWARDS[k].upkeep);assert.equal(city.stats.spending.rewards,REWARDS[k].upkeep);assert.equal(build(city,k,[{x:30,y:30}]).ok,false,'duplicate placement rejected');if(k==='cityHall')assert.equal(rewardActive(city,city.tiles[20*city.size+20]),true);if(k==='stadium'){assert.equal(city.stats.activeStadium,true);assert.ok(city.stats.demand.residential>base);}if(k==='university')assert.equal(city.stats.activeUniversity,true);const loaded=validateSave(JSON.parse(serializeCity(city)));assert.deepEqual(loaded.stats,city.stats);city.finance.roadCondition=0;recompute(city);assert.equal(city.stats.activeStadium,false);assert.equal(city.stats.activeUniversity,false);assert.ok(build(city,'bulldoze',[{x:20+Math.min(1,REWARDS[k].size-1),y:20+Math.min(1,REWARDS[k].size-1)}]).ok);assert.equal(city.tiles.filter(t=>t.type===k).length,0);assert.ok(build(city,k,[{x:20,y:20}]).ok,'earned reward can be rebuilt');}
const legacy=JSON.parse(serializeCity(c));legacy.version=19;delete legacy.rewards;assert.deepEqual(validateSave(legacy).rewards,freshRewards());const bad=JSON.parse(serializeCity(c));bad.rewards.earned.mayorHouse=c.month+1;assert.throws(()=>validateSave(bad));const integrated=generateCity({water:0,trees:0,mountains:0});const result=tick(integrated);assert.deepEqual(result.rewardsUnlocked,[]);assert.equal(integrated.rewards.lastMonth,1);
console.log('PASS: reward eligibility/streak reset, monthly idempotence, durable offers, placement gates, unique footprints, operating demand/education flags, upkeep, disconnection, rebuilding, saves and migration.');
