import assert from 'node:assert/strict';
import {showRewards} from '../dist/rewards-ui.js';
import {REWARDS} from '../dist/rewards.js';
import {createCity} from '../dist/engine.js';
import {serializeCity} from '../dist/save.js';
const canvases=new Map(),rotate=new Map(),place=[];let renders=0,closed=0,tool=null;
const ctx={clearRect(){},fillRect(){},save(){},restore(){},drawImage(){renders++;},createImageData:(w,h)=>({data:new Uint8ClampedArray(w*h*4)}),putImageData(){}};
globalThis.document={createElement:()=>({getContext:()=>ctx}),getElementById:id=>canvases.get(id),querySelector:s=>rotate.get(s),querySelectorAll:()=>place};
const c=createCity('Reward previews',false);c.rewards.earned.mayorHouse=0;const before=serializeCity(c);
showRewards({city:()=>c,dialog(title,html){assert.match(title,/Rewards/);for(const k of Object.keys(REWARDS)){assert.ok(html.includes('rewardPreview-'+k));canvases.set('rewardPreview-'+k,{getContext:()=>ctx});rotate.set('[data-reward-rotate="'+k+'"]',{});place.push({dataset:{reward:k}});}},close(){closed++;},setTool:v=>tool=v});
assert.equal(renders,Object.keys(REWARDS).length);for(const b of rotate.values())for(let i=0;i<4;i++)b.onclick();assert.equal(renders,Object.keys(REWARDS).length*5);assert.equal(serializeCity(c),before,'inspection never changes the city');place.find(b=>b.dataset.reward==='mayorHouse').onclick();assert.equal(tool,'mayorHouse');assert.equal(closed,1);
console.log('PASS: reward panel previews every reward, rotates each through four views without city mutation, and retains placement controls.');
