import assert from 'node:assert/strict';
import {createCity,build,selection,recompute,tick,validateSave} from '../dist/engine.js';
import {serializeCity} from '../dist/save.js';
import {processGarbage,wasteProduction} from '../dist/utilities.js';
import {REWARD_WASTE,garbageSourceRoads,rewardWasteReport,rewardGarbageInspection} from '../dist/reward-waste.js';
import {wasteState} from '../dist/waste-accounting.js';
import {connectionCandidates,addConnection,signDeal,exportGarbage} from '../dist/region.js';
const put=(c,k,a,b=a)=>assert.ok(build(c,k,selection(k,a,b)).ok,k);
function campus(){const c=createCity('Campus collection',false);c.startYear=2000;c.funds=500000;for(const t of c.tiles)Object.assign(t,{terrain:'land',elevation:0,nature:false});c.rewards.earned.themePark=0;put(c,'solar',{x:10,y:20});put(c,'powerline',{x:14,y:20},{x:19,y:20});put(c,'road',{x:20,y:30},{x:39,y:30});put(c,'themePark',{x:20,y:20});return c;}
const c=campus(),root=c.tiles[20*48+20];assert.equal(root.roadIds.length,0);assert.ok(garbageSourceRoads(c,root).length>0);c.finance.roadCondition=20;assert.deepEqual(garbageSourceRoads(c,root),[]);c.finance.roadCondition=100;assert.equal(wasteProduction(root,c),144);assert.equal(c.stats.wasteProduction,144);assert.equal(c.tiles.filter(t=>t.type==='themePark').reduce((sum,t)=>sum+wasteProduction(t,c),0),144,'one production charge for the whole campus');assert.equal(REWARD_WASTE.university,88);
put(c,'landfill',{x:40,y:30},{x:40,y:32});processGarbage(c);assert.equal(root.waste,0);assert.equal(wasteState(c).stored,144,'far-side road reaches landfill');
put(c,'bulldoze',{x:34,y:30},{x:37,y:30});processGarbage(c);assert.equal(root.waste,144,'isolated landfill cannot collect campus waste');assert.match(rewardWasteReport(c),/144/);assert.match(rewardGarbageInspection(c,c.tiles[29*48+29]),/144.00 waiting/);const saved=serializeCity(c);assert.equal(serializeCity(validateSave(JSON.parse(saved))),saved);
put(c,'road',{x:34,y:30},{x:37,y:30});processGarbage(c);assert.equal(root.waste,0);assert.ok(Math.abs(wasteState(c).stored-431)<1e-8);
c.tiles[29*48+29].fire=5;recompute(c);assert.equal(c.stats.wasteProduction,0);root.waste=12;const before=wasteState(c);processGarbage(c);assert.equal(root.waste,0,'old waste is collectable while operation is suspended');assert.ok(Math.abs(wasteState(c).stored-(before.stored-before.decay+12))<1e-8);c.tiles[29*48+29].fire=0;recompute(c);assert.equal(c.stats.wasteProduction,144);
const recycling=campus();put(recycling,'landfill',{x:40,y:30});put(recycling,'recycling',{x:19,y:29});processGarbage(recycling);assert.ok(Math.abs(wasteState(recycling).recycled-43.2)<1e-8);assert.ok(Math.abs(wasteState(recycling).stored-100.8)<1e-8);
const burning=campus();put(burning,'incinerator',{x:19,y:29});processGarbage(burning);assert.equal(wasteState(burning).burned,100);assert.equal(wasteState(burning).waiting,44);
const trade=campus();put(trade,'road',{x:40,y:30},{x:47,y:30});assert.ok(addConnection(trade,connectionCandidates(trade).find(p=>p.kind==='road'&&p.side==='east')).ok);assert.ok(signDeal(trade,0,'garbage','export',100).ok);recompute(trade);processGarbage(trade);exportGarbage(trade);assert.equal(wasteState(trade).waiting,0);assert.equal(trade.region.deals[0].delivered,144,'export uses far-side campus road access');
const rail=campus();put(rail,'trainStation',{x:33,y:32});put(rail,'rail',{x:34,y:32},{x:44,y:32});put(rail,'landfill',{x:44,y:33});assert.equal(rail.tiles[33*48+44].roadIds.length,0);processGarbage(rail);assert.equal(wasteState(rail).waiting,0);assert.equal(wasteState(rail).stored,144,'far-side road transfers campus waste to a rail-only landfill');
const ledger=campus();put(ledger,'landfill',{x:40,y:30},{x:40,y:32});const restored=validateSave(JSON.parse(serializeCity(ledger)));for(let month=0;month<3;month++){const prior=wasteState(ledger);tick(ledger);tick(restored);const h=ledger.history.at(-1);assert.equal(h.garbageGenerated,144);assert.ok(Math.abs(prior.waiting+h.garbageGenerated-h.garbageLandfilled-h.garbageIncinerated-h.garbageRecycled-h.garbageExported-h.garbageUncollected)<1e-8);assert.equal(serializeCity(ledger),serializeCity(restored));}
console.log('PASS: once-per-campus reward garbage, far-side landfill/recycling/incineration/export, disconnected disposal backlog, suspended-operation cleanup, inspection and conserved saved monthly accounting.');
