import assert from 'node:assert/strict';
import {createCity,validateSave} from '../dist/engine.js';
import {serializeCity} from '../dist/save.js';
import {attachCustomScenario} from '../dist/custom-scenarios.js';
import {runScenarioEvents,validateEventCondition,eventConditionMet,eventConditionLabel} from '../dist/scenario-events.js';
const crime={metric:'crime',operator:'gte',target:50},funds={metric:'funds',operator:'lte',target:1000};
const all={match:'all',conditions:[crime,funds]},any={match:'any',conditions:[crime,funds]};
const c=createCity();c.funds=2000;c.stats.averageCrime=50;
assert.equal(eventConditionMet(c,all),false);assert.equal(eventConditionMet(c,any),true);
c.funds=1000;assert.equal(eventConditionMet(c,all),true);
c.stats.averageCrime=49;c.funds=1001;assert.equal(eventConditionMet(c,any),false);
assert.match(eventConditionLabel(all),/ AND /);assert.match(eventConditionLabel(any),/ OR /);
const definition={title:'Two pressures',months:12,objectives:[{metric:'population',target:10000}],events:[{type:'riot',month:3,x:20,y:20,condition:all}]};
attachCustomScenario(c,definition);c.month=3;c.stats.averageCrime=80;c.funds=2000;assert.equal(runScenarioEvents(c),null);
c.month=4;c.funds=1000;assert.equal(runScenarioEvents(c).status,'triggered');assert.ok(c.emergency.riot);
assert.deepEqual(validateSave(JSON.parse(serializeCity(c))).scenario,c.scenario);
for(const invalid of [{match:'all',conditions:[]},{match:'none',conditions:[crime]},{match:'all',conditions:[all]},{match:'all',conditions:[null]},{match:'all',conditions:Array(5).fill(crime)},{match:'any',conditions:[{...crime,target:Infinity}]},4])assert.throws(()=>validateEventCondition(invalid));
const old=createCity();attachCustomScenario(old,{...definition,events:[{...definition.events[0],condition:crime}]});const legacy=JSON.parse(serializeCity(old));legacy.version=39;assert.deepEqual(validateSave(legacy).scenario.definition.events[0].condition,crime);
console.log('PASS: AND/OR truth tables, inclusive boundaries, conditional riot timing, grouped save continuity, bounded validation and legacy single predicates.');
