import assert from 'node:assert/strict';
import {createCity} from '../dist/engine.js';
import {serializeCity} from '../dist/save.js';
import {SCENARIOS} from '../dist/scenarios.js';
import {createScenario} from '../dist/scenario-setup.js';
import {navigationColor} from '../dist/navigation-map.js';
import {SCENARIO_PREVIEW_LAYERS,scenarioPreviewMap,scenarioPreviewPanel} from '../dist/scenario-preview.js';
import {showScenarios} from '../dist/scenario-ui.js';
for(const id of Object.keys(SCENARIOS)){const city=createScenario(id),before=serializeCity(city);for(const layer of Object.keys(SCENARIO_PREVIEW_LAYERS)){const svg=scenarioPreviewMap(city,layer),pixels=Array(city.tiles.length);for(const [,color,path]of svg.matchAll(/<path fill="([^"]+)" d="([^"]+)"/g))for(const [,x,y,length,back]of path.matchAll(/M(\d+) (\d+)h(\d+)v1h-(\d+)z/g)){assert.equal(length,back);for(let i=0;i<Number(length);i++){const index=Number(y)*city.size+Number(x)+i;assert.equal(pixels[index],undefined,'no overlapping map runs');pixels[index]=color;}}assert.deepEqual(pixels,city.tiles.map(t=>navigationColor(t,layer)));assert.ok(svg.length<100000);assert.match(svg,/role="img"/);}assert.equal(serializeCity(city),before);assert.ok(scenarioPreviewPanel(city).includes(city.stats.population.toLocaleString('en-US')+' residents'));}
for(const type of ['coal','waterTower','police','park','landfill'])assert.equal(navigationColor({type,terrain:'land',watered:false},'water'),'#344c42','nonconsuming buildings are not false water outages');assert.equal(navigationColor({type:'residential',terrain:'land',level:1,watered:false},'water'),'#ce855e');assert.equal(navigationColor({type:'residential',terrain:'land',level:1,watered:true},'water'),'#82cfbe');
assert.throws(()=>scenarioPreviewMap(createScenario('growth'),'bogus'));
let current=createCity(),html='',controls=new Map(),buttons=[],starts=0,exports=0,closes=0;const original=serializeCity(current);globalThis.document={querySelector:s=>controls.get(s.slice(1)),querySelectorAll:s=>s==='[data-scenario]'?buttons:[]};
const ui={city:()=>current,dialog:(_,body)=>{html=body;controls=new Map([...body.matchAll(/id="([^"]+)"/g)].map(m=>[m[1],{value:'city',innerHTML:'',textContent:''}]));buttons=[...body.matchAll(/data-scenario="([^"]+)"/g)].map(m=>({dataset:{scenario:m[1]}}));},close:()=>closes++,start:id=>{starts++;current=createScenario(id);},exportCity:()=>exports++,review(){},update(){},save(){}};
showScenarios(ui);for(const id of Object.keys(SCENARIOS)){buttons.find(b=>b.dataset.scenario===id).onclick();assert.match(html,/Inspect the starting town/);assert.equal(serializeCity(current),original);for(const layer of Object.keys(SCENARIO_PREVIEW_LAYERS)){controls.get('scenarioPreviewLayer').value=layer;controls.get('scenarioPreviewLayer').onchange();assert.equal(controls.get('scenarioPreviewMap').innerHTML,scenarioPreviewMap(createScenario(id),layer));assert.ok(controls.get('scenarioPreviewLegend').textContent.includes('Top-down'));}assert.equal(serializeCity(current),original);controls.get('exportScenario').onclick();controls.get('cancelScenario').onclick();assert.equal(starts,0);}
assert.equal(exports,Object.keys(SCENARIOS).length);buttons.find(b=>b.dataset.scenario==='waterRecovery').onclick();controls.get('startScenario').onclick();assert.equal(starts,1);assert.equal(closes,1);assert.equal(serializeCity(current),serializeCity(createScenario('waterRecovery')));
console.log('PASS: all seven real starting towns match four pixel-exact preview layers, bounded accessible SVGs, read-only inspection, actual layer/Back/Export controls and explicit Start transition.');
