import assert from 'node:assert/strict';
import {mountScenarioProgramEditor} from '../dist/scenario-program-editor.js';
import {createCity,tick} from '../dist/engine.js';
import {attachCustomScenario} from '../dist/custom-scenarios.js';
class Node{constructor(tag){this.tag=tag;if(tag==='textarea')Object.defineProperty(this,'type',{get:()=> 'textarea'});this.children=[];this.textContent='';this.value='';}append(...items){for(const n of items){n.parent=this;this.children.push(n);}}replaceChildren(...items){this.children=[];this.append(...items);}setAttribute(){}}
globalThis.document={createElement:tag=>new Node(tag)};const walk=n=>[n,...n.children.flatMap(walk)],click=(n,label)=>{const b=n.children.find(c=>c.tag==='button'&&c.textContent===label);assert.ok(b,label);assert.ok(!b.disabled,label);b.onclick();},rows=box=>box.children.filter(n=>n.tag==='section'),legend=(root,name)=>walk(root).find(n=>n.tag==='legend'&&n.textContent===name).parent;
const action={kind:'action',action:{type:'variable',variable:0,operation:'add',value:2}},branch={kind:'if',condition:{metric:'population',operator:'gte',target:0},then:[action],else:[]},root=new Node('div'),editor=mountScenarioProgramEditor(root,{initial:[{name:'Main',steps:[branch]},{name:'Helper',steps:[]}]});
click(rows(legend(root,'Actions'))[0],'Copy step');click(legend(root,'Actions'),'Paste at end');assert.deepEqual(editor.draft()[0].steps,[branch,branch]);let value=walk(rows(legend(root,'Actions'))[0]).find(n=>n.tag==='label'&&n.textContent==='Value').children[0];value.value='9';value.oninput();assert.equal(editor.draft()[0].steps[0].then[0].action.value,9);assert.equal(editor.draft()[0].steps[1].then[0].action.value,2,'pasted branches are independent copies');
click(rows(legend(root,'Actions'))[0],'Cut step');assert.equal(editor.draft()[0].steps.length,1);const helper=legend(root,'Routine 2');click(legend(helper,'Actions'),'Paste at end');assert.equal(editor.draft()[1].steps[0].then[0].action.value,9);click(rows(legend(root,'Actions'))[0],'Paste before step');assert.equal(editor.draft()[0].steps[0].then[0].action.value,9);
// A copied call protects its target and is remapped when earlier routines disappear.
const refsRoot=new Node('div'),refs=mountScenarioProgramEditor(refsRoot,{initial:[{name:'Unused',steps:[]},{name:'Main',steps:[{kind:'call',routine:2}]},{name:'Target',steps:[action]}]});click(rows(legend(legend(refsRoot,'Routine 2'),'Actions'))[0],'Cut step');click(legend(refsRoot,'Routine 3'),'Delete routine');assert.equal(refs.draft().length,3);click(legend(refsRoot,'Routine 1'),'Delete routine');assert.equal(refs.draft().length,2);click(legend(refsRoot,'Actions'),'Paste at end');assert.equal(refs.draft()[0].steps[0].routine,1);
// Pasting bounded drafts fails atomically when it would exceed compiler limits.
const limitRoot=new Node('div'),limit=mountScenarioProgramEditor(limitRoot,{initial:[{name:'Full',steps:Array.from({length:128},()=>structuredClone(action))}]});click(rows(legend(limitRoot,'Actions'))[0],'Copy step');click(legend(limitRoot,'Actions'),'Paste at end');assert.equal(limit.draft()[0].steps.length,128);assert.ok(walk(limitRoot).some(n=>n.textContent.includes('exceed 128')));
const playRoot=new Node('div'),play=mountScenarioProgramEditor(playRoot,{initial:[{name:'Main',steps:[action]}]});click(rows(legend(playRoot,'Actions'))[0],'Copy step');click(legend(playRoot,'Actions'),'Paste at end');const city=createCity();attachCustomScenario(city,{title:'Copied logic',months:24,objectives:[{metric:'population',target:999999}],programs:play.read([0]),events:[{type:'program',routine:0,month:1}]});tick(city);assert.equal(city.scenario.variables[0],4,'copied steps execute in the actual scenario engine');click(playRoot,'Clear copied step');assert.ok(legend(playRoot,'Actions').children.find(n=>n.textContent==='Paste at end').disabled);
console.log('PASS: independent script branch copying, cut/paste across routines, insertion order, clipboard call protection/remapping, bounded paste rejection and actual copied-step execution.');
let nested=structuredClone(action);for(let i=0;i<7;i++)nested={kind:'if',condition:{metric:'population',operator:'gte',target:0},then:[nested],else:[]};const depthRoot=new Node('div'),depthEditor=mountScenarioProgramEditor(depthRoot,{initial:[{name:'Deep',steps:[nested]}]});click(rows(legend(depthRoot,'Actions'))[0],'Copy step');const depthBefore=JSON.stringify(depthEditor.draft());click(legend(depthRoot,'If true'),'Paste at end');assert.equal(JSON.stringify(depthEditor.draft()),depthBefore);assert.ok(walk(depthRoot).some(n=>n.textContent.includes('eight nesting')));
