import assert from 'node:assert/strict';
import {generateCity} from '../dist/terrain-generator.js';
import {build,selection,recompute,validateSave} from '../dist/engine.js';
import {serializeCity} from '../dist/save.js';
import {STRUCTURE_METRICS,COUNTED_STRUCTURES,structureRoots} from '../dist/scenario-structures.js';
import {attachCustomScenario,customCurrentGoals} from '../dist/custom-scenarios.js';
import {eventConditionMet} from '../dist/scenario-events.js';
const c=generateCity({startYear:2050,water:0,mountains:0,trees:0});c.funds=1000000;
for(const [tool,x,y] of [['police',10,10],['school',20,10],['coal',10,20],['busStop',20,20],['recycling',25,25]])assert.ok(build(c,tool,[{x,y}]).ok,tool);
assert.equal(STRUCTURE_METRICS.structuresCoal.read(c),1,'16 coal tiles count once');assert.equal(STRUCTURE_METRICS.structuresPolice.read(c),1,'unserviced buildings still count');
assert.equal(STRUCTURE_METRICS.structuresCoal.read(c,{x:11,y:21,radius:0}),0,'member tile is not another building');assert.equal(STRUCTURE_METRICS.structuresCoal.read(c,{x:10,y:20,radius:0}),1);
assert.ok(Object.keys(COUNTED_STRUCTURES).length>40);
assert.ok(build(c,'airport',selection('airport',{x:30,y:30},{x:32,y:34})).ok);assert.equal(STRUCTURE_METRICS.structuresAirport.read(c),0,'undeveloped zoning does not count');
for(const t of c.tiles)if(t.type==='airport')t.level=1;recompute(c);assert.equal(STRUCTURE_METRICS.structuresAirport.read(c),1);assert.equal(c.stats.activeAirports,0,'placed and operating are distinct');
attachCustomScenario(c,{title:'Build city services',months:24,objectives:[{metric:'structuresPolice',target:1,area:{x:10,y:10,radius:0}},{metric:'structuresAirport',target:1}]});assert.ok(customCurrentGoals(c).every(g=>g.done));
const saved=validateSave(JSON.parse(serializeCity(c)));assert.ok(customCurrentGoals(saved).every(g=>g.done));
assert.ok(build(saved,'bulldoze',[{x:10,y:10}]).ok);assert.equal(customCurrentGoals(saved)[0].done,false);assert.ok(!eventConditionMet(saved,{metric:'structuresPolice',operator:'gte',target:1}));
const coal=structureRoots(c,'coal')[0];coal.rubble=true;assert.equal(STRUCTURE_METRICS.structuresCoal.read(c),0,'rubble excluded');coal.rubble=false;coal.radiation=true;assert.equal(STRUCTURE_METRICS.structuresCoal.read(c),0,'contamination excluded');
console.log('PASS: complete implemented structure catalog, actual construction, root-only local counts, undeveloped facility exclusion, placed versus operating distinction, save roundtrip and bulldoze goal failure.');
