import assert from 'node:assert/strict';
import {createCity,tick,validateSave} from '../dist/engine.js';
import {serializeCity} from '../dist/save.js';
import {attachCustomScenario,validateCustomDefinition} from '../dist/custom-scenarios.js';
import {scenarioEnding,runScenarioEventBatch,scenarioEventReport} from '../dist/scenario-events.js';
import {restartCustomScenario} from '../dist/scenario-replay.js';
const definition={title:'Rescue objective',months:12,completionMode:'scripted',eventMode:'together',objectiveMode:'sequence',objectives:[{metric:'population',target:999999},{metric:'population',target:1000000}],ranks:[{name:'Rescuer',outcome:'won',message:'You saved the city.',condition:null}],events:[{type:'variable',variable:0,operation:'add',value:1,month:1,repeatCount:3,repeatEvery:1},{type:'ending',outcome:'won',month:2,message:'Rescue complete after {variable1} signals.',condition:{metric:'variable1',operator:'gte',target:2}},{type:'earthquake',month:2,x:24,y:24},{type:'announcement',month:2,message:'This must never run.'}]};
const c=createCity();attachCustomScenario(c,definition);tick(c);assert.equal(c.scenario.status,'playing');const saved=validateSave(JSON.parse(serializeCity(c)));tick(c);tick(saved);assert.deepEqual(saved.scenario,c.scenario);assert.equal(c.scenario.status,'won');assert.equal(c.scenario.rank,'Rescuer');assert.equal(c.scenario.endedMonth,2);assert.equal(scenarioEnding(c.scenario).message,'Rescue complete after 2 signals.');assert.equal(c.emergency.active,false);assert.equal(c.scenario.events[2].runs,0);assert.equal(c.scenario.events[3].runs,0);assert.deepEqual(c.scenario.stageCompletedMonths,[],'script victory can end with incomplete optional stages');assert.deepEqual(validateSave(JSON.parse(serializeCity(c))).scenario,c.scenario);assert.deepEqual(runScenarioEventBatch(c),[]);assert.match(scenarioEventReport(c),/Rescue complete after 2 signals/);const restart=restartCustomScenario(c);assert.equal(restart.scenario.status,'playing');assert.equal(restart.scenario.resultGoals,undefined);assert.ok(c.scenario.resultGoals.some(g=>!g.done),'scripted victory records incomplete optional goals honestly');assert.equal(scenarioEnding(restart.scenario),null);
const loss=createCity();attachCustomScenario(loss,{title:'Critical failure',months:12,objectives:[{metric:'population',target:1}],events:[{type:'ending',outcome:'lost',month:1,message:'Critical failure.',condition:{metric:'funds',operator:'gte',target:0}}]});tick(loss);assert.equal(loss.scenario.status,'lost','scripted failure overrides otherwise-satisfied goals');assert.equal(loss.scenario.endedMonth,1);assert.equal(validateSave(JSON.parse(serializeCity(loss))).scenario.status,'lost');
const deadline=createCity();attachCustomScenario(deadline,{title:'Wait for rescue',completionMode:'scripted',months:12,objectives:[{metric:'population',target:1}],events:[{type:'ending',outcome:'won',month:12,message:'Rescue arrived.'}]});for(let i=0;i<11;i++){tick(deadline);assert.equal(deadline.scenario.status,'playing','satisfied goals do not end script-controlled challenges');}tick(deadline);assert.equal(deadline.scenario.status,'won');assert.equal(deadline.scenario.endedMonth,12);
const timeout=createCity();attachCustomScenario(timeout,{title:'Missed rescue',completionMode:'scripted',months:12,objectives:[{metric:'population',target:1}],events:[{type:'ending',outcome:'won',month:12,message:'Rescue arrived.',condition:{metric:'variable1',operator:'gte',target:1}}]});for(let i=0;i<12;i++)tick(timeout);assert.equal(timeout.scenario.status,'lost');assert.equal(scenarioEnding(timeout.scenario),null);
assert.throws(()=>validateCustomDefinition({...definition,events:[]}));assert.throws(()=>validateCustomDefinition({...definition,completionMode:'unknown'}));assert.throws(()=>validateCustomDefinition({...definition,events:[{type:'ending',outcome:'won',month:1,message:'Repeat',repeatCount:2,repeatEvery:1}]}));assert.throws(()=>validateCustomDefinition({...definition,events:[{type:'ending',outcome:'other',month:1,message:'Bad'}]}));
for(const mutate of [raw=>raw.scenario.status='lost',raw=>raw.scenario.endedMonth=3,raw=>raw.scenario.events[1].message=null]){const raw=JSON.parse(serializeCity(c));mutate(raw);assert.throws(()=>validateSave(raw));}
const legacy=createCity();attachCustomScenario(legacy,{title:'Old goals',months:12,objectives:[{metric:'population',target:1}]});const old=JSON.parse(serializeCity(legacy));old.version=83;delete old.scenario.definition.completionMode;const migrated=validateSave(old);assert.equal(migrated.scenario.definition.completionMode,'goals');tick(migrated);assert.equal(migrated.scenario.status,'won');
console.log('PASS: conditional scripted victory/loss, terminating action groups, incomplete-stage victory, outcome ranks, saved ending messages, replay reset, deadline victory/timeout and legacy goal completion.');
