import assert from 'node:assert/strict';
import {createCity,build,tick,recompute,validateSave,VERSION} from '../dist/engine.js';
import {NEIGHBORS,connectionCandidates,addConnection,signDeal,cancelDeal} from '../dist/region.js';
import {NEIGHBOR_METRICS,neighborConnectionActive,neighborDealActive} from '../dist/scenario-neighbor-metrics.js';
import {CUSTOM_METRICS,attachCustomScenario,validateCustomDefinition} from '../dist/custom-scenarios.js';
import {validateEventCondition,eventConditionMet} from '../dist/scenario-events.js';
import {serializeCity} from '../dist/save.js';
import {restartCustomScenario} from '../dist/scenario-replay.js';
import {recomputeFacilities,advanceFacilities} from '../dist/facilities.js';
const base=()=>{const c=createCity('Neighbor challenge',false);for(const t of c.tiles)Object.assign(t,{terrain:'land',elevation:0,nature:false});return c;};
const point=side=>({north:{x:24,y:0},east:{x:47,y:24},south:{x:24,y:47},west:{x:0,y:24}}[side]);
const connect=(c,side,kind)=>{const p=point(side);assert.ok(build(c,kind==='power'?'powerline':kind==='water'?'pipe':kind,[p]).ok);assert.equal(neighborConnectionActive(c,side,kind),0,'boundary infrastructure alone is not registered');assert.ok(addConnection(c,connectionCandidates(c).find(q=>q.side===side&&q.kind===kind)).ok);return c.tiles[p.y*48+p.x];};
assert.equal(Object.keys(NEIGHBOR_METRICS).length,47);
for(const [key,m]of Object.entries(NEIGHBOR_METRICS)){assert.equal(CUSTOM_METRICS[key].name,m.name);assert.equal(CUSTOM_METRICS[key].read(base()),0);assert.deepEqual(m.states,['Inactive','Active']);for(const target of [0,1])assert.deepEqual(validateEventCondition({metric:key,target,operator:'eq'}),{metric:key,target,operator:'eq'});assert.throws(()=>validateCustomDefinition({title:'Invalid state',months:12,objectives:[{metric:key,target:.5}]}));}
for(const side of ['north','east','south','west'])for(const kind of ['road','highway','rail','power','water']){const c=base(),tile=connect(c,side,kind);assert.equal(neighborConnectionActive(c,side,kind),1);const before=serializeCity(c);assert.equal(neighborConnectionActive(c,side,kind),1);assert.equal(serializeCity(c),before);if(kind==='water')tile.pipe=false;else if(kind==='highway')tile.highway=false;else if(kind==='rail')tile.rail=false;else tile.type=null;assert.equal(neighborConnectionActive(c,side,kind),0);}
for(const side of ['north','east','south','west'])for(const kind of ['power','water','garbage'])for(const direction of ['import','export']){const c=base(),tile=connect(c,side,kind==='garbage'?'road':kind);assert.ok(signDeal(c,0,kind,direction,25).ok);assert.equal(neighborDealActive(c,side,kind,direction),1,'signed idle contracts count as active');assert.equal(neighborDealActive(c,side==='east'?'west':'east',kind,direction),0,'another neighbor does not satisfy this deal query');assert.equal(neighborDealActive(c,side,kind,direction==='import'?'export':'import'),0);c.region.deals[0].failed=true;assert.equal(neighborDealActive(c,side,kind,direction),0);c.region.deals[0].failed=false;assert.ok(cancelDeal(c,c.region.deals[0].id).ok);assert.equal(neighborDealActive(c,side,kind,direction),0);}
// The overseas connection follows the actual developed seaport service state.
const port=base();for(let y=20;y<26;y++)for(let x=20;x<22;x++)Object.assign(port.tiles[y*48+x],{type:'seaport',powered:true,watered:true,roadIds:[1]});for(let y=20;y<26;y++)port.tiles[y*48+19].terrain='water';for(let x=0;x<20;x++)port.tiles[20*48+x].terrain='water';port.stats={...port.stats,...recomputeFacilities(port)};for(let i=0;i<6;i++)advanceFacilities(port);port.stats={...port.stats,...recomputeFacilities(port)};assert.equal(port.stats.activeSeaports,1);assert.ok(addConnection(port,connectionCandidates(port).find(p=>p.side==='sea')).ok);assert.equal(neighborConnectionActive(port,'sea','seaport'),1);for(const direction of ['import','export']){assert.ok(signDeal(port,0,'garbage',direction,25).ok);assert.equal(neighborDealActive(port,'sea','garbage',direction),1);cancelDeal(port,port.region.deals[0].id);}for(const t of port.tiles)if(t.type==='seaport')t.watered=false;port.stats={...port.stats,...recomputeFacilities(port)};assert.equal(neighborConnectionActive(port,'sea','seaport'),0);
const c=base();attachCustomScenario(c,{title:'Keep the eastern lifeline',months:12,holdMonths:2,objectives:[{metric:'connectionEastPower',target:1},{metric:'dealEastPowerImport',target:1}],events:[{type:'announcement',month:1,message:'Eastern import: {dealEastPowerImport}.',condition:{metric:'dealEastPowerImport',operator:'eq',target:1}}]});tick(c);assert.equal(c.scenario.streak,0);const edge=connect(c,'east','power');assert.ok(signDeal(c,0,'power','import',25).ok);recompute(c);assert.equal(c.region.deals[0].delivered,0);tick(c);assert.equal(c.scenario.streak,1);assert.equal(c.scenario.events[0].message,'Eastern import: 1.');assert.ok(build(c,'bulldoze',[{x:47,y:24}]).ok);assert.equal(eventConditionMet(c,{metric:'connectionEastPower',target:0,operator:'eq'}),true);tick(c);assert.equal(c.scenario.streak,0);assert.equal(c.region.deals.length,0);assert.ok(build(c,'powerline',[{x:47,y:24}]).ok);assert.ok(signDeal(c,0,'power','import',25).ok);tick(c);assert.equal(c.scenario.streak,1);const loaded=validateSave(JSON.parse(serializeCity(c)));tick(c);tick(loaded);assert.equal(c.scenario.status,'won');assert.deepEqual(c.scenario,loaded.scenario);const restarted=restartCustomScenario(c);assert.equal(restarted.region.connections.length,0);assert.equal(neighborDealActive(restarted,'east','power','import'),0);
const legacy=JSON.parse(serializeCity(base()));legacy.version=112;assert.equal(validateSave(legacy).version,VERSION);
const large=createCity('Branching trade program',false,96);for(const t of large.tiles)Object.assign(t,{terrain:'land',nature:false});
attachCustomScenario(large,{title:'Regional council',months:12,objectives:[{metric:'variable1',target:1}],programs:[{name:'Check import',steps:[{kind:'if',condition:{metric:'dealEastPowerImport',operator:'eq',target:1},then:[{kind:'action',action:{type:'variable',variable:0,operation:'set',value:1}}],else:[{kind:'action',action:{type:'variable',variable:0,operation:'set',value:0}}]}]}],events:[{type:'program',routine:0,month:1,repeatCount:3,repeatEvery:1}]});tick(large);assert.equal(large.scenario.variables[0],0);assert.equal(large.scenario.status,'playing');assert.ok(build(large,'powerline',[{x:95,y:24}]).ok);assert.ok(addConnection(large,connectionCandidates(large).find(p=>p.side==='east')).ok);assert.ok(signDeal(large,0,'power','import',25).ok);
const direct=validateSave(JSON.parse(serializeCity(large)));tick(direct);let response;globalThis.self={postMessage:v=>response=v};await import('../dist/simulation-worker.js');self.onmessage({data:{id:17,city:structuredClone(large)}});assert.equal(response.error,undefined);assert.equal(response.city.scenario.status,'playing','remaining required repeat holds victory');assert.equal(response.city.scenario.variables[0],1);assert.deepEqual(JSON.parse(serializeCity(response.city)),JSON.parse(serializeCity(direct)));assert.equal(large.scenario.variables[0],0,'worker input is an independent city');tick(response.city);tick(direct);assert.equal(response.city.scenario.status,'won');assert.deepEqual(JSON.parse(serializeCity(response.city)),JSON.parse(serializeCity(direct)));
console.log('PASS: 47 neighbor connection/deal state queries, all land links and contract directions, actual seaport activation/loss, idle versus failed/cancelled contracts, strict state targets and a real interrupted/recovered two-month trading challenge with saved victory and replay.');
