import assert from 'node:assert/strict';
import {createCity} from '../dist/engine.js';
import {attachCustomScenario} from '../dist/custom-scenarios.js';
import {compileGameScenarioPrograms} from '../dist/scenario-program-definitions.js';
import {startProgramInvocation,advanceProgramInvocation,acknowledgeProgramMessage,validateProgramInvocation,programActionSources,programInvocationFinished} from '../dist/scenario-program-history.js';
import {validateGoalMarks} from '../dist/scenario-goal-marks.js';
import {validateGoalActivations} from '../dist/scenario-goal-activation.js';
const action=a=>({kind:'action',action:a}),say=message=>action({type:'announcement',message});
const c=createCity();attachCustomScenario(c,{title:'Program persistence',months:24,objectives:[{metric:'population',target:999999}]});c.month=1;
const programs=compileGameScenarioPrograms([{name:'Council',steps:[action({type:'variable',variable:0,operation:'add',value:1}),{kind:'if',condition:{metric:'variable1',operator:'eq',target:1},then:[action({type:'popup',message:'The counter is {variable1}'}),action({type:'markGoal',goal:0,goalStatus:'satisfied'})],else:[say('Wrong branch')]},say('Complete')]}],{objectives:c.scenario.definition.objectives});
let run=startProgramInvocation(programs,0,1,0);assert.equal(advanceProgramInvocation(c,programs,run).type,'variable');assert.equal(advanceProgramInvocation(c,programs,run).type,'popup');assert.equal(run.text[0].message,'The counter is 1');const paused=JSON.stringify(run);assert.equal(advanceProgramInvocation(c,programs,run),null);assert.equal(JSON.stringify(run),paused);
run=validateProgramInvocation(JSON.parse(paused),programs,{startMonth:0,month:1});assert.equal(acknowledgeProgramMessage(run,0),false);assert.equal(acknowledgeProgramMessage(run,1),true);c.scenario.variables[0]=9;
assert.equal(advanceProgramInvocation(c,programs,run).type,'markGoal','a persisted branch is not re-evaluated');assert.equal(advanceProgramInvocation(c,programs,run).message,'Complete');assert.equal(advanceProgramInvocation(c,programs,run),null);assert.ok(programInvocationFinished(run));const checked=validateProgramInvocation(JSON.parse(JSON.stringify(run)),programs,{startMonth:0,month:1});assert.deepEqual(checked,run);
const sources=programActionSources(checked,programs);assert.deepEqual(validateGoalMarks(c.scenario.goalMarks,c.scenario.definition,0,1,[],[],sources),c.scenario.goalMarks);assert.throws(()=>validateGoalMarks(c.scenario.goalMarks,c.scenario.definition,0,1,[]),/Invalid/);
for(const mutate of [r=>r.branches[0]=false,r=>r.receipts[0].steps++,r=>r.receipts[1].acknowledged=false,r=>r.receipts[2].month=0,r=>r.text.pop(),r=>r.ended=true,r=>r.cursor.steps--]){const bad=structuredClone(run);mutate(bad);assert.throws(()=>validateProgramInvocation(bad,programs,{startMonth:0,month:1}));}
// Program-sourced activation requires an actual receipt at the activation month.
const activationPrograms=compileGameScenarioPrograms([{name:'Add goal',steps:[action({type:'addGoal',goal:0})]}],{objectives:c.scenario.definition.objectives});c.scenario.definition.objectives[0].addAtStartup=false;c.scenario.goalActivatedMonths[0]=null;const activation=startProgramInvocation(activationPrograms,0,1,1);advanceProgramInvocation(c,activationPrograms,activation);const active=validateProgramInvocation(activation,activationPrograms,{startMonth:0,month:1}),activeSources=programActionSources(active,activationPrograms);assert.deepEqual(validateGoalActivations([1],c.scenario.definition,0,1,[],null,activeSources),[1]);assert.throws(()=>validateGoalActivations([2],c.scenario.definition,0,2,[],null,activeSources));
// Text is bounded, while action receipts preserve all control-flow provenance.
const messages=compileGameScenarioPrograms([{name:'Many messages',steps:Array.from({length:40},(_,i)=>say('Message '+i))}],{objectives:c.scenario.definition.objectives}),many=startProgramInvocation(messages,0,1,2);while(!programInvocationFinished(many))advanceProgramInvocation(c,messages,many);assert.equal(many.receipts.length,40);assert.equal(many.text.length,32);assert.equal(many.text[0].receipt,8);assert.deepEqual(validateProgramInvocation(many,messages,{startMonth:0,month:1}),many);
const endingPrograms=compileGameScenarioPrograms([{name:'End',steps:[action({type:'ending',outcome:'lost',message:'The end'}),say('Must not run')]}],{objectives:c.scenario.definition.objectives}),ending=startProgramInvocation(endingPrograms,0,1,3);assert.equal(advanceProgramInvocation(c,endingPrograms,ending).type,'ending');assert.equal(advanceProgramInvocation(c,endingPrograms,ending),null);assert.ok(programInvocationFinished(ending));validateProgramInvocation(ending,endingPrograms,{startMonth:0,month:1});
const held=startProgramInvocation(programs,0,1,4);c.emergency.active=true;assert.equal(advanceProgramInvocation(c,programs,held),null);assert.equal(held.cursor.steps,0);c.emergency.active=false;c.scenario.status='won';assert.equal(advanceProgramInvocation(c,programs,held),null);
const repeatedMarks=[{e:{type:'markGoal',goal:0,goalStatus:'satisfied'},state:{status:'triggered',runs:1,month:1},program:true},{e:{type:'markGoal',goal:0,goalStatus:'unsatisfied'},state:{status:'triggered',runs:1,month:1},program:true}];assert.throws(()=>validateGoalMarks([{satisfied:true,month:1}],c.scenario.definition,0,1,[],[],repeatedMarks),/last routine/);assert.deepEqual(validateGoalMarks([{satisfied:false,month:1}],c.scenario.definition,0,1,[],[],repeatedMarks),[{satisfied:false,month:1}]);assert.throws(()=>validateGoalActivations([2],c.scenario.definition,0,2,[],null,[...activeSources,{...activeSources[0],state:{...activeSources[0].state,month:2}}]),/first routine/);
console.log('PASS: persistent action receipts and branch proof, popup acknowledgement/resume, bounded message history, goal-mark/activation provenance, ending/emergency guards and tampered-history rejection.');
