import assert from 'node:assert/strict';
import {createCity,tick,validateSave,VERSION} from '../dist/engine.js';
import {attachCustomScenario,validateCustomDefinition} from '../dist/custom-scenarios.js';
import {scenarioStory} from '../dist/scenario-story.js';
import {serializeCity} from '../dist/save.js';
import {restartCustomScenario} from '../dist/scenario-replay.js';
import {pendingScenarioPopup} from '../dist/scenario-popups.js';
const definition={title:'Changing instructions',months:12,briefing:'Original briefing',winMessage:'Original victory',lossMessage:'Original loss',objectives:[{metric:'population',target:1000}]};
const c=createCity('Story city',false);attachCustomScenario(c,{...definition,eventMode:'together',events:[{type:'variable',month:1,variable:0,operation:'set',value:7},{type:'dialogText',month:1,message:'Stage {variable1}: <restore> & rebuild\nThen return.'},{type:'resultText',month:2,outcome:'both',message:'Council record: {variable1}'},{type:'dialogText',month:3,message:'Stage two: {variable1}',repeatCount:2,repeatEvery:1}]});const original=structuredClone(c.scenario.definition);tick(c);assert.equal(c.scenario.textOverrides.briefing,'Stage 7: <restore> & rebuild\nThen return.');assert.match(scenarioStory(c.scenario,c),/Stage 7: &lt;restore&gt; &amp; rebuild/);assert.equal(pendingScenarioPopup(c),null);c.scenario.variables[0]=9;assert.match(scenarioStory(c.scenario,c),/Stage 7:/,'captured values are not re-expanded');tick(c);assert.equal(c.scenario.textOverrides.winMessage,'Council record: 9');assert.equal(c.scenario.textOverrides.lossMessage,'Council record: 9');const saved=validateSave(JSON.parse(serializeCity(c)));tick(c);tick(saved);assert.deepEqual(c.scenario,saved.scenario);assert.equal(c.scenario.textOverrides.briefing,'Stage two: 9');c.scenario.variables[0]=11;tick(c);assert.equal(c.scenario.textOverrides.briefing,'Stage two: 11');assert.equal(c.scenario.events[3].runs,2);assert.deepEqual(c.scenario.definition,original);const restarted=restartCustomScenario(c);assert.deepEqual(restarted.scenario.textOverrides,{});assert.match(scenarioStory(restarted.scenario,restarted),/Original briefing/);
for(const bad of [null,{briefing:4},{briefing:'x'.repeat(4001)},{briefing:'bad\u0000text'},{unknown:'bad'},{}]){const payload=JSON.parse(serializeCity(c));payload.scenario.textOverrides=bad;assert.throws(()=>validateSave(payload));}const missing=JSON.parse(serializeCity(c));delete missing.scenario.textOverrides;assert.throws(()=>validateSave(missing));
for(const outcome of ['won','lost']){const city=createCity('Outcome text',false);attachCustomScenario(city,{...definition,completionMode:'scripted',eventMode:'together',events:[{type:'resultText',month:1,outcome,message:'Updated '+outcome},{type:'ending',month:1,outcome,message:'Done'}]});tick(city);const story=scenarioStory(city.scenario,city);assert.match(story,new RegExp('Updated '+outcome));assert.doesNotMatch(story,/Original victory|Original loss/);assert.deepEqual(validateSave(JSON.parse(serializeCity(city))).scenario,city.scenario);}
// A deadline result update applies before the ordinary deadline loss.
const deadline=createCity('Deadline story',false);attachCustomScenario(deadline,{...definition,events:[{type:'resultText',month:12,outcome:'lost',message:'The deadline has passed.'}]});for(let i=0;i<12;i++)tick(deadline);assert.equal(deadline.scenario.status,'lost');assert.match(scenarioStory(deadline.scenario,deadline),/The deadline has passed/);
const routine=createCity('Routine story',false);routine.mayorName='';attachCustomScenario(routine,{...definition,programs:[{name:'Rewrite status',steps:[{kind:'action',action:{type:'dialogText',message:'{mayor}'}},...Array.from({length:35},(_,i)=>({kind:'action',action:{type:'announcement',message:'Notice '+i}})),{kind:'action',action:{type:'resultText',outcome:'won',message:'Earned {funds}'}},{kind:'action',action:{type:'ending',outcome:'won',message:'Complete'}}]}],events:[{type:'program',month:1,routine:0}]});tick(routine);assert.equal(routine.scenario.textOverrides.briefing,'');assert.equal(routine.scenario.status,'won');assert.equal(routine.scenario.programInvocations[0].text.length,32);assert.doesNotThrow(()=>validateSave(JSON.parse(serializeCity(routine))));assert.match(scenarioStory(routine.scenario,routine),/Earned/);
for(const bad of [{message:''},{message:'x'.repeat(1501)},{message:'bad\u0000text'},{outcome:'unknown'}])assert.throws(()=>validateCustomDefinition({...definition,events:[{type:'resultText',month:1,message:'Valid',...bad}]}));assert.doesNotThrow(()=>validateCustomDefinition({...definition,events:[{type:'dialogText',month:1,message:'x'.repeat(1500)}]}));
const old=createCity('Old story',false);attachCustomScenario(old,definition);const payload=JSON.parse(serializeCity(old));payload.version=116;delete payload.scenario.textOverrides;assert.equal(validateSave(payload).version,VERSION);assert.deepEqual(validateSave(payload).scenario.textOverrides,{});
console.log('PASS: live progress/result text actions, captured and escaped values, no popup, repeats, deadline loss, outcome selection, unchanged definitions/replay reset, saved continuity, evicted routine text, empty captured values and strict override/source validation with schema116 migration.');
const expanded=createCity('A'.repeat(30),false);attachCustomScenario(expanded,{...definition,events:[{type:'dialogText',month:1,message:'{city}'.repeat(250)}]});tick(expanded);assert.equal(expanded.scenario.textOverrides.briefing.length,4000);assert.doesNotThrow(()=>validateSave(JSON.parse(serializeCity(expanded))));
