import assert from 'node:assert/strict';
import {createCity,tick,validateSave,build} from '../dist/engine.js';
import {attachCustomScenario} from '../dist/custom-scenarios.js';
import {serializeCity} from '../dist/save.js';
import {restartCustomScenario,decodeScenarioStart} from '../dist/scenario-replay.js';
const c=createCity();for(let i=0;i<3;i++)tick(c);const original=JSON.parse(serializeCity(c));
const definition={title:'Repeatable city',months:24,objectives:[{metric:'variable1',target:99}],events:[{type:'variable',variable:0,operation:'add',value:1,month:1,repeatCount:4,repeatEvery:1}]};
attachCustomScenario(c,definition);const baseline=structuredClone(c.scenario.startingCity);assert.equal(baseline.city.scenario,null);assert.ok(JSON.stringify(baseline).length<serializeCity({...c,scenario:null}).length/2,'shared tile keys compact the starting snapshot');
const occupied=c.tiles.find(t=>t.type==='residential');assert.ok(build(c,'bulldoze',[occupied]).ok);c.funds=1234;for(let i=0;i<2;i++)tick(c);assert.equal(c.scenario.variables[0],2);const before=serializeCity(c),restart=restartCustomScenario(c);assert.equal(serializeCity(c),before,'exporting/restarting produces an independent city without modifying the attempt');assert.equal(restart.month,original.month);assert.equal(restart.funds,original.funds);assert.equal(restart.scenario.startMonth,original.month);assert.equal(restart.scenario.status,'playing');assert.deepEqual(restart.scenario.variables,[0,0,0,0]);assert.ok(restart.scenario.events.every(e=>e.runs===0));assert.deepEqual(JSON.parse(serializeCity({...restart,scenario:null})),original,'terrain, structures, economy, census, history and setup return exactly to the authored start');
const restored=validateSave(JSON.parse(before)),a=restartCustomScenario(restored),b=restartCustomScenario(c);for(let i=0;i<4;i++){tick(a);tick(b);}assert.equal(serializeCity(a),serializeCity(b),'portable restart reproduces the same simulation sequence');
const exportedStart=validateSave(JSON.parse(serializeCity(restart)));assert.equal(exportedStart.scenario.events[0].runs,0);assert.equal(exportedStart.month,original.month);assert.deepEqual(exportedStart.scenario.startingCity,restart.scenario.startingCity);
attachCustomScenario(c,{...definition,title:'Replacement challenge'});assert.equal(c.scenario.startingCity.city.scenario,null,'authoring over another challenge never nests snapshots');assert.ok(JSON.stringify(c.scenario.startingCity).length<600000);
for(const mutate of [v=>v.city.scenario={startingCity:baseline},v=>v.city.month++,v=>v.tiles.pop(),v=>v.keys[0]='__proto__',v=>v.tiles[0]=null,v=>v.tiles[0][0]=[1]]){const bad=structuredClone(baseline);mutate(bad);assert.throws(()=>decodeScenarioStart(bad,original.month));}
const legacy=JSON.parse(serializeCity(restored));legacy.version=82;delete legacy.scenario.startingCity;const old=validateSave(legacy);assert.equal(old.scenario.startingCity,null);assert.throws(()=>restartCustomScenario(old),/no saved starting city/);
console.log('PASS: compact complete starting snapshots, independent restart, exact authored-state restoration, reset progress, portable deterministic replay, nonrecursive replacement, invalid snapshot rejection and legacy behavior.');
