import assert from 'node:assert/strict';
import {createCity,validateSave} from '../dist/engine.js';
import {attachCustomScenario} from '../dist/custom-scenarios.js';
import {advanceScenario} from '../dist/scenarios.js';
import {runScenarioEvents,eventConditionMet,validateEventCondition,scenarioEventReport} from '../dist/scenario-events.js';
import {serializeCity} from '../dist/save.js';
const d={title:'Keep the peace',months:12,objectives:[{metric:'population',target:400}],events:[{type:'riot',month:3,x:20,y:20,condition:{metric:'crime',operator:'gte',target:50}}]};const c=createCity();attachCustomScenario(c,d);c.month=2;c.stats.averageCrime=80;assert.equal(runScenarioEvents(c),null);c.month=3;c.stats.averageCrime=20;assert.equal(runScenarioEvents(c),null);c.month=4;c.stats.averageCrime=50;assert.equal(runScenarioEvents(c).status,'triggered');assert.ok(c.emergency.riot);assert.equal(runScenarioEvents(c),null);assert.deepEqual(validateSave(JSON.parse(serializeCity(c))).scenario,c.scenario);
const avoid=createCity();attachCustomScenario(avoid,{...d,objectives:[{metric:'population',target:200}]});avoid.month=3;avoid.stats.averageCrime=10;assert.equal(runScenarioEvents(avoid),null);advanceScenario(avoid);assert.equal(avoid.scenario.status,'won');assert.match(scenarioEventReport(avoid),/Not triggered/);
const queue=createCity();attachCustomScenario(queue,{...d,events:[d.events[0],{type:'fire',month:4,x:20,y:20}]});queue.month=4;queue.stats.averageCrime=0;assert.equal(runScenarioEvents(queue).type,'fire','unmet condition cannot block later timed event');assert.equal(queue.scenario.events[0].status,'pending');
assert.ok(eventConditionMet(queue,{metric:'crime',operator:'lte',target:0}));for(const condition of [{metric:'constructor',operator:'gte',target:0},{metric:'crime',operator:'unknown',target:0},{metric:'crime',operator:'gte',target:101}])assert.throws(()=>validateEventCondition(condition));
const old=createCity();attachCustomScenario(old,{...d,events:[{type:'fire',month:3,x:20,y:20}]});const legacy=JSON.parse(serializeCity(old));legacy.version=36;delete legacy.scenario.definition.events[0].condition;assert.equal(validateSave(legacy).scenario.definition.events[0].condition,null);
console.log('PASS: conditional start windows, inclusive thresholds, one-time triggering, prevention-compatible victory, event queue fairness, validation and migration.');
