import assert from 'node:assert/strict';
import {createCity,tick,validateSave,build} from '../dist/engine.js';
import {serializeCity} from '../dist/save.js';
import {attachCustomScenario,validateCustomDefinition} from '../dist/custom-scenarios.js';
import {eventConditionMet,eventConditionLabel,validateEventCondition} from '../dist/scenario-events.js';
import {restartCustomScenario} from '../dist/scenario-replay.js';
import {removeScenarioVariable} from '../dist/scenario-variable-references.js';
const condition={metric:'variable3',operator:'eq',right:{metric:'variable2'}};
const definition={title:'Meet the recorded target',months:12,eventMode:'together',completionMode:'scripted',variables:[{name:'Unused',initial:7},{name:'Target',initial:2},{name:'Progress',initial:0}],objectives:[{metric:'population',target:999999}],events:[{type:'variable',variable:2,operation:'add',value:1,month:1,repeatCount:3,repeatEvery:1},{type:'ending',outcome:'won',month:1,message:'Reached the saved target.',condition}]};
const city=createCity();attachCustomScenario(city,definition);tick(city);assert.equal(city.scenario.status,'playing');
const save=JSON.parse(serializeCity(city)),restored=validateSave(save);tick(city);tick(restored);assert.equal(city.scenario.status,'won');assert.deepEqual(restored.scenario,city.scenario);
assert.equal(city.scenario.variables[2],2);assert.equal(eventConditionMet(city,condition),true);
city.scenario.variables[1]=3;assert.equal(eventConditionMet(city,condition),false,'comparison reads the live saved target, not a captured constant');city.scenario.variables[1]=2;
const replay=restartCustomScenario(city);assert.equal(eventConditionMet(replay,condition),false);tick(replay);tick(replay);assert.equal(replay.scenario.status,'won');
const compact=removeScenarioVariable(definition,0);assert.equal(compact.events[1].condition.metric,'variable2');assert.equal(compact.events[1].condition.right.metric,'variable1');
const compactCity=createCity();attachCustomScenario(compactCity,compact);tick(compactCity);tick(compactCity);assert.equal(compactCity.scenario.status,'won');
assert.throws(()=>removeScenarioVariable(definition,1),/comparison value/);
const branch={...definition,events:[definition.events[0],{type:'program',routine:0,month:1,repeatCount:3,repeatEvery:1}],programs:[{name:'Check progress',steps:[{kind:'if',condition,then:[{kind:'action',action:{type:'ending',outcome:'won',message:'Routine target reached.'}}],else:[]}]}]};
const branchCity=createCity();attachCustomScenario(branchCity,branch);tick(branchCity);const resumed=validateSave(JSON.parse(serializeCity(branchCity)));tick(resumed);assert.equal(resumed.scenario.status,'won');
for(const [operator,expected] of [['eq',true],['ne',false],['gt',false],['lt',false],['gte',true],['lte',true]])assert.equal(eventConditionMet(city,{...condition,operator}),expected);
city.scenario.variables[1]=NaN;assert.equal(eventConditionMet(city,{...condition,operator:'ne'}),false,'unavailable right values cannot satisfy inequality');
assert.match(eventConditionLabel(condition),/Scenario variable 3 = Scenario variable 2/);
for(const bad of [{...condition,target:2},{...condition,right:{metric:'missing'}},{...condition,right:[]},{...condition,right:{metric:'variable2',area:{x:0,y:0,radius:1}}}])assert.throws(()=>validateEventCondition(bad));
assert.throws(()=>validateCustomDefinition({...definition,events:[{...definition.events[1],condition:{...condition,right:{metric:'variable4'}}}]}),/undefined scenario variable/);
assert.throws(()=>validateCustomDefinition({...definition,events:[{...definition.events[1],condition:{...condition,right:{metric:'goalStatus2'}}}]}),/undefined goal/);
const old=structuredClone(save);old.version=159;assert.throws(()=>validateSave(old),/version 160/);
console.log('PASS live scenario comparisons: changing counter targets, scheduled/routine endings, save/replay, reference remapping and invalid operands');

const areas=createCity('Separate comparison areas',false);for(const tile of areas.tiles)Object.assign(tile,{terrain:'land',nature:false,elevation:0});
assert.ok(build(areas,'eiffelTower',[{x:10,y:10}]).ok);assert.ok(build(areas,'bigBen',[{x:30,y:30}]).ok);assert.ok(build(areas,'statueLiberty',[{x:35,y:30}]).ok);
const spatial={metric:'landmarks',area:{x:10,y:10,radius:5},operator:'lt',right:{metric:'landmarks',area:{x:32,y:30,radius:6}}};
assert.equal(eventConditionMet(areas,validateEventCondition(spatial)),true);
assert.equal(eventConditionMet(areas,{...spatial,operator:'eq'}),false);
assert.ok(build(areas,'bulldoze',[{x:35,y:30}]).ok);assert.equal(eventConditionMet(areas,{...spatial,operator:'eq'}),true);
console.log('PASS independently scoped comparison areas respond to actual landmark construction and demolition');
