import assert from 'node:assert/strict';
import {createCity,build,tick,validateSave,VERSION} from '../dist/engine.js';
import {connectionCandidates,addConnection} from '../dist/region.js';
import {executeNeighborDeal,validateNeighborDealAction,validateNeighborDealResult} from '../dist/scenario-neighbor-deals.js';
import {attachCustomScenario} from '../dist/custom-scenarios.js';
import {serializeCity} from '../dist/save.js';
const base=()=>{const c=createCity('Scripted trade',false);for(const t of c.tiles)Object.assign(t,{terrain:'land',elevation:0,nature:false});return c;};
const action={type:'neighborDeal',operation:'enable',neighbor:'east',resource:'power',direction:'import',amount:25};
const connect=(c,side,resource)=>{const p={east:{x:47,y:24},west:{x:0,y:24},north:{x:24,y:0},south:{x:24,y:47}}[side];const kind=resource==='garbage'?'road':resource;assert.ok(build(c,kind==='power'?'powerline':kind==='water'?'pipe':kind,[p]).ok);assert.ok(addConnection(c,connectionCandidates(c).find(v=>v.side===side&&v.kind===kind)).ok);};
for(const neighbor of ['north','east','south','west'])for(const resource of ['power','water','garbage'])for(const direction of ['import','export']){
 const c=base(),a={...action,neighbor,resource,direction};assert.equal(executeNeighborDeal(c,a).dealResult.outcome,'missingConnection');connect(c,neighbor,resource);
 assert.equal(executeNeighborDeal(c,a).dealResult.outcome,'created');const funds=c.funds,deal=structuredClone(c.region.deals[0]);assert.equal(executeNeighborDeal(c,{...a,amount:100}).dealResult.outcome,'alreadyActive');assert.deepEqual(c.region.deals[0],deal);assert.equal(c.funds,funds);
 assert.equal(executeNeighborDeal(c,{...a,direction:direction==='import'?'export':'import'}).dealResult.outcome,'conflictingDeal');assert.equal(executeNeighborDeal(c,{...a,operation:'disable',direction:direction==='import'?'export':'import'}).dealResult.outcome,'alreadyInactive');assert.equal(c.region.deals.length,1);
 const ended=executeNeighborDeal(c,{...a,operation:'disable'});assert.equal(ended.dealResult.outcome,'ended');assert.equal(c.funds,funds-ended.dealResult.fee);assert.equal(c.region.deals.length,0);const after=c.funds;assert.equal(executeNeighborDeal(c,{...a,operation:'disable'}).dealResult.outcome,'alreadyInactive');assert.equal(c.funds,after);
}
for(const bad of [{amount:26},{neighbor:'invalid'},{neighbor:'sea',resource:'power'},{direction:'both'},{operation:'toggle'}])assert.throws(()=>validateNeighborDealAction({...action,...bad}));
assert.deepEqual(validateNeighborDealAction({...action,operation:'disable',amount:999}),{neighbor:'east',resource:'power',direction:'import',operation:'disable'});
assert.throws(()=>validateNeighborDealResult({outcome:'created',dealId:1,fee:2},action,'triggered'));
assert.throws(()=>validateNeighborDealResult({outcome:'created',dealId:1,fee:0},action,'skipped'));
const c=base();connect(c,'east','power');attachCustomScenario(c,{title:'A temporary import',months:12,objectives:[{metric:'population',target:1000}],events:[{...action,month:1},{...action,operation:'disable',month:2,repeatCount:2,repeatEvery:1}]});
tick(c);assert.equal(c.scenario.events[0].dealResult.outcome,'created');const loaded=validateSave(JSON.parse(serializeCity(c)));assert.equal(loaded.region.deals.length,1);tick(c);tick(loaded);assert.deepEqual(JSON.parse(serializeCity(loaded)),JSON.parse(serializeCity(c)));const receipt=c.scenario.events[1].dealResult;assert.equal(receipt.outcome,'ended');assert.ok(receipt.fee>0);assert.equal(c.history.at(-1).regionalPenalty,receipt.fee);const penalty=c.region.totalPenalties;tick(c);assert.equal(c.scenario.events[1].dealResult.outcome,'alreadyInactive');assert.equal(c.region.totalPenalties,penalty);assert.equal(c.history.at(-1).regionalPenalty,0);assert.doesNotThrow(()=>validateSave(JSON.parse(serializeCity(c))));
const routine=base();connect(routine,'east','power');attachCustomScenario(routine,{title:'Council command',months:12,objectives:[{metric:'population',target:1000}],programs:[{name:'Open then close',steps:[{kind:'action',action},{kind:'if',condition:{metric:'dealEastPowerImport',operator:'eq',target:1},then:[{kind:'action',action:{type:'variable',variable:0,operation:'set',value:1}}],else:[]},{kind:'action',action:{...action,operation:'disable'}}]}],events:[{type:'program',routine:0,month:1}]});tick(routine);assert.equal(routine.scenario.variables[0],1,'later branches see the new agreement');assert.equal(routine.region.deals.length,0);assert.ok(routine.history.at(-1).regionalPenalty>0);assert.doesNotThrow(()=>validateSave(JSON.parse(serializeCity(routine))));
const legacy=JSON.parse(serializeCity(base()));legacy.version=113;assert.equal(validateSave(legacy).version,VERSION);
console.log('PASS: scripted neighbor contracts across 24 land trade combinations, idempotence, conflicts, fees, scheduled repeats, save/load and immediate routine status queries.');

const mature=base();connect(mature,'east','power');executeNeighborDeal(mature,action);mature.month=12;assert.equal(executeNeighborDeal(mature,{...action,operation:'disable'}).dealResult.fee,0);
const grouped=base();connect(grouped,'east','power');connect(grouped,'west','power');executeNeighborDeal(grouped,action);executeNeighborDeal(grouped,{...action,neighbor:'west'});attachCustomScenario(grouped,{title:'End both imports',months:12,eventMode:'together',objectives:[{metric:'population',target:1000}],events:[{...action,operation:'disable',month:1},{...action,neighbor:'west',operation:'disable',month:1}]});tick(grouped);const fees=grouped.scenario.events.reduce((n,e)=>n+e.dealResult.fee,0);assert.equal(grouped.history.at(-1).regionalPenalty,fees);assert.equal(grouped.region.totalPenalties,fees);const bad=JSON.parse(serializeCity(grouped));bad.scenario.events[0].dealResult.fee=-1;assert.throws(()=>validateSave(bad));
let response;globalThis.self={postMessage:v=>response=v};await import('../dist/simulation-worker.js');const workerStart=validateSave(JSON.parse(serializeCity(loaded))),direct=validateSave(JSON.parse(serializeCity(loaded)));tick(direct);self.onmessage({data:{id:99,city:workerStart}});assert.equal(response.error,undefined);assert.deepEqual(JSON.parse(serializeCity(response.city)),JSON.parse(serializeCity(direct)));
