import assert from 'node:assert/strict';
import {createCity,tick,validateSave} from '../dist/engine.js';
import {attachCustomScenario,customGoals,validateCustomDefinition} from '../dist/custom-scenarios.js';
import {serializeCity} from '../dist/save.js';
import {restartCustomScenario} from '../dist/scenario-replay.js';
const def={title:'A changing mandate',months:12,holdMonths:2,objectives:[{metric:'funds',target:0,name:'Treasury'},{metric:'population',target:0,name:'New mandate',addAtStartup:false}],events:[{type:'addGoal',month:3,goal:1,repeatCount:2,repeatEvery:1}]};
const c=createCity('Activation',false);attachCustomScenario(c,def);assert.deepEqual(c.scenario.goalActivatedMonths,[0,null]);assert.ok(!customGoals(c).some(g=>g.title==='New mandate'));
tick(c);tick(c);assert.equal(c.scenario.status,'playing');tick(c);assert.deepEqual(c.scenario.goalActivatedMonths,[0,3]);assert.ok(customGoals(c).some(g=>g.title==='New mandate'));assert.equal(c.scenario.streak,0,'pending required repeats keep the hold from starting');
const raw=JSON.parse(serializeCity(c)),loaded=validateSave(raw);assert.deepEqual(loaded.scenario,c.scenario);
tick(c);tick(loaded);assert.equal(c.scenario.goalActivatedMonths[1],3,'repeat activation preserves first activation month');assert.equal(c.scenario.streak,1);tick(c);tick(loaded);assert.equal(c.scenario.status,'won');assert.deepEqual(loaded.scenario,c.scenario);
const restarted=restartCustomScenario(c);assert.deepEqual(restarted.scenario.goalActivatedMonths,[0,null]);assert.equal(restarted.scenario.status,'playing');
const conditional=createCity('Conditional',false);attachCustomScenario(conditional,{...def,holdMonths:3,events:[{type:'addGoal',month:2,goal:1,condition:{metric:'funds',operator:'gte',target:0}}]});tick(conditional);assert.equal(conditional.scenario.streak,1);tick(conditional);assert.equal(conditional.scenario.streak,1,'new active requirement resets the prior hold, then participates in this month check');tick(conditional);tick(conditional);assert.equal(conditional.scenario.status,'won');
const waiting=createCity('Await instructions',false);attachCustomScenario(waiting,{title:'Initially empty',months:12,objectives:[{metric:'funds',target:0,addAtStartup:false}],events:[{type:'addGoal',month:1,goal:0,condition:{metric:'population',operator:'gte',target:1000}}]});for(let i=0;i<12;i++)tick(waiting);assert.equal(waiting.scenario.status,'lost','an empty active list must not win');assert.equal(waiting.scenario.streak,0);
const sequence=createCity('Ordered activation',false);attachCustomScenario(sequence,{...def,objectiveMode:'sequence',holdMonths:1,events:[{type:'addGoal',month:4,goal:1}]});for(let i=0;i<3;i++)tick(sequence);assert.deepEqual(sequence.scenario.stageCompletedMonths,[1]);tick(sequence);assert.equal(sequence.scenario.status,'won');assert.deepEqual(sequence.scenario.stageCompletedMonths,[1,4]);
const grouped=createCity('Grouped activation',false);attachCustomScenario(grouped,{...def,holdMonths:1,eventMode:'together',events:[{type:'variable',month:1,variable:0,operation:'set',value:5},{type:'addGoal',month:1,goal:1,condition:{metric:'variable1',operator:'gte',target:5}}]});tick(grouped);assert.equal(grouped.scenario.goalActivatedMonths[1],1);assert.equal(grouped.scenario.status,'won');
for(const mutate of [v=>v.scenario.streak=2,v=>v.scenario.goalActivatedMonths=[0,null],v=>v.scenario.goalActivatedMonths=[0,4],v=>v.scenario.goalActivatedMonths=[1,3],v=>delete v.scenario.goalActivatedMonths,v=>v.scenario.definition.events[0].goal=3]){const bad=structuredClone(raw);mutate(bad);assert.throws(()=>validateSave(bad));}
assert.throws(()=>validateCustomDefinition({...def,events:[]}));assert.throws(()=>validateCustomDefinition({...def,objectives:[{metric:'funds',target:0,addAtStartup:'false'}]}));
const legacy=createCity('Legacy',false);attachCustomScenario(legacy,{title:'Original goals',months:12,objectives:[{metric:'population',target:400}]});const old=JSON.parse(serializeCity(legacy));old.version=97;delete old.scenario.goalActivatedMonths;assert.deepEqual(validateSave(old).scenario.goalActivatedMonths,[0]);
console.log('PASS: timed and conditional goal activation, independent repeat behavior, required-event victory, hold reset, empty-list deadline loss, sequential activation, grouped variable conditions, save/replay and legacy validation.');
