import assert from 'node:assert/strict';
import {showPendingScenarioPopup,pendingScenarioPopup} from '../dist/scenario-popups.js';
import {createCity} from '../dist/engine.js';
import {attachCustomScenario} from '../dist/custom-scenarios.js';
import {compileGameScenarioPrograms} from '../dist/scenario-program-definitions.js';
import {startProgramInvocation,advanceProgramInvocation,programInvocationFinished,acknowledgeProgramMessage} from '../dist/scenario-program-history.js';
import {validateProgramInvocations,activeProgramInvocation,pendingProgramPopup} from '../dist/scenario-program-invocations.js';
const c=createCity();attachCustomScenario(c,{title:'Invocation binding',months:24,objectives:[{metric:'population',target:999999}]});
const definition={...c.scenario.definition,programs:[{name:'Report',steps:[{kind:'action',action:{type:'popup',message:'Read this once'}},{kind:'action',action:{type:'variable',variable:0,operation:'add',value:1}}]},{name:'Grant',steps:[{kind:'action',action:{type:'reward',reward:'university'}}]}],events:[{type:'program',routine:0,month:1,repeatCount:2,repeatEvery:2},{type:'program',routine:1,month:2,repeatCount:1,repeatEvery:0}]};
const programs=compileGameScenarioPrograms(definition.programs,{objectives:definition.objectives}),states=[{status:'pending',month:null,runs:0},{status:'pending',month:null,runs:0}];
// This fixture exercises the collection boundary directly; definition loading
// and normal month scheduling are separate integration gates.
c.scenario.definition=definition;c.scenario.programInvocations=[];c.month=1;let first=startProgramInvocation(programs,0,1,0);c.scenario.programInvocations.push(first);advanceProgramInvocation(c,programs,first);states[0]={status:'triggered',month:1,runs:1};let checked=validateProgramInvocations(c.scenario.programInvocations,definition,states,0,1);assert.equal(checked.invocations.length,1);assert.equal(activeProgramInvocation(c.scenario),first);const popup=pendingProgramPopup(c.scenario);assert.equal(popup.message,'Read this once');assert.equal(popup.state,first.receipts[0]);let saved=0,closed=0,html='',onclose;const controls={'#dismissScenarioPopup':{},'#popupScenarioStatus':{}};assert.ok(showPendingScenarioPopup({city:()=>c,dialog(title,body){html=body;},save(){saved++;},close(){closed++;},status(){},element:{addEventListener(name,handler){onclose=handler;},querySelector:id=>controls[id]}}));assert.match(html,/Read this once/);controls['#dismissScenarioPopup'].onclick();onclose();assert.equal(saved,1);assert.equal(closed,1);assert.equal(pendingScenarioPopup(c),null);
c.month=3;while(!programInvocationFinished(first))advanceProgramInvocation(c,programs,first);states[0].month=3;assert.equal(first.finishedMonth,3);assert.equal(activeProgramInvocation(c.scenario),null);assert.equal(pendingProgramPopup(c.scenario),null);
c.month=4;const grant=startProgramInvocation(programs,1,4,12);while(!programInvocationFinished(grant))advanceProgramInvocation(c,programs,grant);c.scenario.programInvocations.push(grant);states[1]={status:'triggered',month:4,runs:1};
c.month=5;const repeat=startProgramInvocation(programs,0,5,1);advanceProgramInvocation(c,programs,repeat);acknowledgeProgramMessage(repeat,0);while(!programInvocationFinished(repeat))advanceProgramInvocation(c,programs,repeat);c.scenario.programInvocations.push(repeat);states[0]={status:'triggered',month:5,runs:2};checked=validateProgramInvocations(JSON.parse(JSON.stringify(c.scenario.programInvocations)),definition,states,0,5);assert.deepEqual(checked.invocations,c.scenario.programInvocations);assert.equal(checked.sources.length,5);assert.equal(c.scenario.variables[0],2);
for(const mutate of [v=>v[2].id=2,v=>v[1].id=0,v=>v[2].startedMonth=4,v=>v.splice(1,1),v=>v[0].cursor.entry=1,v=>v[0].finishedMonth=6]){const bad=structuredClone(c.scenario.programInvocations);mutate(bad);assert.throws(()=>validateProgramInvocations(bad,definition,states,0,5));}
const wrong=structuredClone(states);wrong[0].runs=1;assert.throws(()=>validateProgramInvocations(checked.invocations,definition,wrong,0,5));wrong[0].runs=2;wrong[0].month=4;assert.throws(()=>validateProgramInvocations(checked.invocations,definition,wrong,0,5));
assert.throws(()=>validateProgramInvocations(undefined,definition,states,0,5));assert.throws(()=>validateProgramInvocations(checked.invocations,{...definition,months:4},states,0,5),'receipt dates cannot extend beyond the challenge deadline');assert.deepEqual(validateProgramInvocations(undefined,{events:[]},[],0,0),{invocations:[],sources:[]});assert.throws(()=>validateProgramInvocations([first],{events:[]},[],0,5));
console.log('PASS: scheduled-entry and repeat identity binding, completion-based repeat dates, persistent pending-message references, sequential invocation order, goal-source projection and missing/duplicate/early history rejection.');
