import assert from 'node:assert/strict';
import {generateCity} from '../dist/terrain-generator.js';
import {build,selection,recompute,validateSave,tick,idx} from '../dist/engine.js';
import {advanceIndustry} from '../dist/industry.js';
import {attachCustomScenario} from '../dist/custom-scenarios.js';
import {CUSTOM_METRICS} from '../dist/scenario-metrics.js';
import {eventConditionMet,runScenarioEvents} from '../dist/scenario-events.js';
import {ignite,stepFire} from '../dist/emergency.js';
import {serializeCity} from '../dist/save.js';
const c=generateCity({startYear:2000,water:0,mountains:0,trees:0});
build(c,'solar',[{x:10,y:15}]);build(c,'road',selection('road',{x:15,y:20},{x:20,y:20}));build(c,'residential',[{x:16,y:19}]);build(c,'industrial',selection('industrial',{x:19,y:23},{x:21,y:25}));
assert.equal(CUSTOM_METRICS.farms.read(c),0);assert.equal(CUSTOM_METRICS.cleanIndustry.read(c),0);
for(let i=0;i<100&&!c.stats.farms;i++){c.month++;advanceIndustry(c);recompute(c);}
assert.equal(CUSTOM_METRICS.farms.read(c),1,'nine fields count as one farm');
attachCustomScenario(c,{title:'A rural recovery',months:60,holdMonths:2,objectives:[{metric:'farms',target:1}],events:[]});
tick(c);assert.equal(c.scenario.streak,1);assert.equal(c.scenario.status,'playing');
const field=c.tiles[idx(21,25)];ignite(c,field.x,field.y);field.fire=100;field.fireAge=100;stepFire(c);recompute(c);
assert.equal(CUSTOM_METRICS.farms.read(c),0);tick(c);assert.equal(c.scenario.streak,0);assert.equal(c.scenario.status,'playing');
const resume=validateSave(JSON.parse(serializeCity(c)));assert.equal(resume.scenario.definition.objectives[0].metric,'farms');
assert.ok(build(resume,'bulldoze',selection('bulldoze',{x:19,y:23},{x:21,y:25})).ok);
for(let i=0;i<60&&resume.scenario.status==='playing';i++)tick(resume);
assert.equal(resume.scenario.status,'won','normal monthly redevelopment completes the farm recovery challenge');
assert.ok(eventConditionMet(resume,{metric:'farms',operator:'gte',target:1}));
attachCustomScenario(resume,{title:'Protect the harvest',months:24,objectives:[{metric:'farms',target:2}],events:[{type:'locust',month:1,x:19,y:23,condition:{metric:'farms',operator:'gte',target:1}}]});resume.month++;
assert.equal(runScenarioEvents(resume).status,'triggered');assert.ok(resume.emergency.locust);
const clean=generateCity({startYear:2000,water:0,mountains:0,trees:0});build(clean,'solar',[{x:20,y:20}]);build(clean,'road',selection('road',{x:20,y:19},{x:28,y:19}));build(clean,'residential',[{x:25,y:18}]);build(clean,'industrial',[{x:26,y:20}]);
const factory=clean.tiles[idx(26,20)];factory.level=1;factory.age=12;clean.civic.education=90;recompute(clean);
assert.equal(CUSTOM_METRICS.cleanIndustry.read(clean),0,'dirty factories do not qualify');
for(let i=0;i<100&&factory.industry!=='clean';i++){clean.month++;advanceIndustry(clean);}recompute(clean);
assert.equal(CUSTOM_METRICS.cleanIndustry.read(clean),1);attachCustomScenario(clean,{title:'A cleaner economy',months:12,objectives:[{metric:'cleanIndustry',target:1}],events:[]});
assert.equal(validateSave(JSON.parse(serializeCity(clean))).scenario.definition.objectives[0].metric,'cleanIndustry');tick(clean);assert.equal(clean.scenario.status,'won');
factory.level=0;assert.equal(CUSTOM_METRICS.cleanIndustry.read(clean),0,'vacant factories do not count');
const bad=JSON.parse(serializeCity(clean));bad.scenario.definition.objectives[0].target=2305;assert.throws(()=>validateSave(bad));
console.log('PASS: farm and clean-industry objectives, empty/dirty exclusions, whole-farm counting, fire-loss streak reset, saved redevelopment victory, agricultural locust conditions and bounded targets.');
