import assert from 'node:assert/strict';
import {createCity,tick,validateSave} from '../dist/engine.js';
import {attachCustomScenario,customGoals,validateCustomDefinition} from '../dist/custom-scenarios.js';
import {CONDITION_METRICS} from '../dist/scenario-events.js';
import {serializeCity} from '../dist/save.js';
import {restartCustomScenario} from '../dist/scenario-replay.js';
const all=c=>CONDITION_METRICS.allGoalsMet.read(c);
const d={title:'Reopened mandate',months:12,eventMode:'together',objectiveMode:'sequence',holdMonths:2,objectives:[{metric:'funds',target:0},{metric:'population',target:0}],events:[{type:'markGoal',goal:0,goalStatus:'unsatisfied',month:3},{type:'markGoal',goal:0,goalStatus:'satisfied',month:5,repeatCount:2,repeatEvery:1},{type:'markGoal',goal:1,goalStatus:'satisfied',month:5},{type:'announcement',message:'Review complete',month:10}]};
const c=createCity('Marked goals',false);attachCustomScenario(c,d);tick(c);tick(c);assert.deepEqual(c.scenario.stageCompletedMonths,[2]);tick(c);assert.deepEqual(c.scenario.stageCompletedMonths,[]);assert.equal(c.scenario.streak,0);assert.equal(CONDITION_METRICS.goalStatus1.read(c),1);
const reopened=JSON.parse(serializeCity(c));assert.deepEqual(validateSave(reopened).scenario,c.scenario);const invalid=structuredClone(reopened);invalid.scenario.stageCompletedMonths=[2];assert.throws(()=>validateSave(invalid),/unsatisfied/);
tick(c);tick(c);assert.equal(c.scenario.streak,1);assert.equal(all(c),1,'explicit goal satisfaction is separate from the stage hold');assert.equal(c.scenario.status,'playing');
const loaded=validateSave(JSON.parse(serializeCity(c)));for(let i=0;i<5;i++){tick(c);tick(loaded);}assert.deepEqual(c.scenario.stageCompletedMonths,[6,8]);assert.equal(c.scenario.status,'won');assert.deepEqual(c.scenario,loaded.scenario);assert.ok(customGoals(c).every(g=>g.done));assert.deepEqual(restartCustomScenario(c).scenario.goalMarks,[null,null]);
const direct=createCity('Explicit ending',false);attachCustomScenario(direct,{title:'Script decides',months:12,completionMode:'scripted',eventMode:'together',objectives:[{metric:'population',target:999999}],events:[{type:'markGoal',goal:0,goalStatus:'satisfied',month:1},{type:'ending',outcome:'won',message:'Mandate complete',month:1,condition:{metric:'allGoalsMet',operator:'eq',target:1}}]});assert.equal(all(direct),0);tick(direct);assert.equal(direct.scenario.status,'won');assert.equal(all(direct),1);assert.match(customGoals(direct).at(-1).detail,/Scripted status: satisfied/);assert.equal(validateSave(JSON.parse(serializeCity(direct))).scenario.status,'won');
const hidden=createCity('Hidden marks',false);attachCustomScenario(hidden,{title:'Later reveal',months:12,objectives:[{metric:'population',target:999999,addAtStartup:false}],events:[{type:'markGoal',goal:0,goalStatus:'satisfied',month:1},{type:'addGoal',goal:0,month:2}]});tick(hidden);assert.equal(all(hidden),0);assert.equal(CONDITION_METRICS.goalStatus1.read(hidden),0);assert.equal(hidden.scenario.status,'playing');tick(hidden);assert.equal(hidden.scenario.status,'won');
for(const mutate of [v=>v.scenario.goalMarks=null,v=>v.scenario.goalMarks[0].satisfied=true,v=>v.scenario.goalMarks[0].month=2]){const bad=structuredClone(reopened);mutate(bad);assert.throws(()=>validateSave(bad));}
assert.throws(()=>validateCustomDefinition({...d,events:[{type:'markGoal',goal:3,goalStatus:'satisfied',month:1}]}));assert.throws(()=>validateCustomDefinition({...d,events:[{type:'markGoal',goal:0,goalStatus:'maybe',month:1}]}));
const old=createCity('Legacy goals',false);attachCustomScenario(old,{title:'Legacy',months:12,objectives:[{metric:'population',target:1000}]});const raw=JSON.parse(serializeCity(old));raw.version=100;delete raw.scenario.goalMarks;assert.deepEqual(validateSave(raw).scenario.goalMarks,[null]);
console.log('PASS: scripted satisfaction and reopening, sequential rollback/hold replay, idempotent repeat marks, all-active-goal checks, same-batch endings, inactive marks, saved continuation and legacy/history validation.');
