import assert from 'node:assert/strict';
import {createCity,build,selection,recompute,validateSave} from '../dist/engine.js';
import {serializeCity} from '../dist/save.js';
import {REWARDS,REWARD_APPROVAL,rewardCondition,advanceRewards} from '../dist/rewards.js';
import {rewardGeometry,rasterizeReward,drawCityReward} from '../dist/reward-models.js';
import {themeParkRideState,wheelCabins,themeParkRidePixels} from '../dist/theme-park-rides.js';
import {rewardNeighborhoodReport} from '../dist/reward-neighborhood.js';
const c=createCity('Theme district',false);c.startYear=2000;c.funds=500000;for(const t of c.tiles)Object.assign(t,{terrain:'land',nature:false,elevation:0});
c.stats.population=79999;c.stats.aura=REWARD_APPROVAL;assert.equal(rewardCondition(c,'themePark'),false);c.stats.population=80000;c.stats.aura-=.001;assert.equal(rewardCondition(c,'themePark'),false);c.stats.aura=REWARD_APPROVAL;c.month=1;assert.ok(advanceRewards(c).includes('themePark'));c.stats.population=0;c.month++;advanceRewards(c);assert.equal(c.rewards.earned.themePark,1);
const place=(k,a,b=a)=>assert.ok(build(c,k,selection(k,a,b),3).ok);place('solar',{x:10,y:20});place('powerline',{x:14,y:20},{x:19,y:20});place('road',{x:8,y:19},{x:32,y:19});place('residential',{x:8,y:17},{x:25,y:17});for(const t of c.tiles)if(t.type==='residential')t.level=3;place('commercial',{x:26,y:17});place('industrial',{x:31,y:17});recompute(c);
const home=c.tiles[17*48+24],before={air:home.airPollution,water:home.waterPollution,crime:home.crime},funds=c.funds;place('themePark',{x:20,y:20});assert.equal(c.funds,funds-125000);assert.equal(REWARDS.themePark.size,10);assert.equal(c.tiles.filter(t=>t.type==='themePark').length,100);assert.equal(c.stats.residentialCap.limit,225000);assert.equal(c.stats.civicJobs,400);assert.equal(c.stats.civicEmployed,400);assert.equal(build(c,'themePark',[{x:32,y:30}]).ok,false);
assert.ok(Math.abs(home.themeParkLandValue-(-18)*7/15)<1e-9);assert.ok(Math.abs(c.tiles[17*48+26].themeParkLandValue-12*7/15)<1e-9);assert.equal(c.tiles[17*48+31].themeParkLandValue,0);assert.ok(home.airPollution>before.air);assert.ok(home.waterPollution>before.water);assert.ok(home.crime>before.crime);assert.ok(home.themeParkCrimePressure>0);assert.ok(home.themeParkAura>0);assert.match(rewardNeighborhoodReport(home),/-8\.4 points/);
const value=home.landValue;recompute(c);assert.equal(home.landValue,value);const saved=JSON.parse(serializeCity(c));assert.equal(saved.version,141);assert.equal(validateSave(saved).tiles[17*48+24].landValue,value);const old=structuredClone(saved);old.version=140;assert.throws(()=>validateSave(old));
const root=c.tiles[20*48+20],corner=c.tiles[29*48+29],renderer={getCity:()=>c,layer:'city',preferences:{},reducedMotion:{matches:false},vehicleTime:10};assert.deepEqual(themeParkRideState(renderer,root),{active:true,time:10});renderer.preferences.sceneryAnimations=false;assert.equal(themeParkRideState(renderer,root).time,0);renderer.preferences.sceneryAnimations=true;renderer.reducedMotion.matches=true;assert.equal(themeParkRideState(renderer,root).time,0);renderer.reducedMotion.matches=false;renderer.layer='water';assert.equal(themeParkRideState(renderer,root).active,false);renderer.layer='city';corner.fire=5;assert.equal(themeParkRideState(renderer,root).active,false);recompute(c);assert.equal(c.stats.civicJobs,0);assert.equal(c.stats.residentialCap.limit,25000);assert.equal(home.themeParkLandValue,0);assert.equal(home.themeParkAura,0);assert.equal(home.themeParkCrimePressure,0);assert.equal(home.airPollution,before.air);assert.equal(home.waterPollution,before.water);corner.fire=0;recompute(c);place('bulldoze',{x:29,y:29});place('themePark',{x:20,y:20});
const legacy=JSON.parse(serializeCity(createCity('Legacy park',false)));legacy.version=140;delete legacy.rewards.earned.themePark;delete legacy.rewards.streaks.themePark;assert.equal(validateSave(legacy).rewards.earned.themePark,null);legacy.version=141;assert.throws(()=>validateSave(legacy));
assert.equal(wheelCabins(0).length,12);assert.notDeepEqual(wheelCabins(0),wheelCabins(1));assert.deepEqual(wheelCabins(4),wheelCabins(4));assert.ok(rewardGeometry('themePark').length>500);for(let r=0;r<4;r++){const raster=rasterizeReward('themePark',r,true);assert.ok(raster.data.some((n,i)=>i%4===3&&n>0));const pixels=themeParkRidePixels(1,r,raster.depth);assert.ok(pixels.length>0);assert.ok(pixels.length<themeParkRidePixels(1,r).length);assert.deepEqual(themeParkRidePixels(1,r,new Float32Array(512*512).fill(Infinity)),[]);}
let painted=0;globalThis.document={createElement:()=>({getContext:()=>({createImageData:(w,h)=>({data:new Uint8ClampedArray(w*h*4)}),putImageData:()=>{}})})};drawCityReward({save:()=>{},restore:()=>{},drawImage:()=>{},fillRect:()=>painted++},'themePark',0,256,320,512,1,{active:true,time:1});assert.ok(painted>0);delete globalThis.document;
console.log('PASS: Theme Park gates, paid unique 10x10 placement, 200,000 capacity, 400 jobs, neighborhood tradeoffs, shutdown/rebuild, saves, four-view ride depth and scenery-clock controls.');
