import assert from 'node:assert/strict';
import {createCity,recompute,tick,validateSave} from '../dist/engine.js';
import {startTornado,stepFire,soundSiren} from '../dist/emergency.js';
import {defaultTornadoSettings,validateTornadoSettings,tornadoVector} from '../dist/tornado-settings.js';
import {attachCustomScenario} from '../dist/custom-scenarios.js';
import {serializeCity} from '../dist/save.js';
const settings=extra=>({...defaultTornadoSettings(),warning:false,direction:'east',distance:4,...extra});
const base=()=>{const c=createCity('Authored storm',false);for(const t of c.tiles)Object.assign(t,{terrain:'land',nature:false,elevation:0,type:'road',pipe:true,subway:true});recompute(c);return c;};
for(const bad of [{direction:'up'},{intensity:0},{intensity:101},{distance:0},{distance:257},{distance:1.5},{speed:'instant'},{warning:1}]){assert.throws(()=>validateTornadoSettings(settings(bad)));const c=base(),before=serializeCity(c);assert.equal(startTornado(c,24,24,settings(bad)).ok,false);assert.equal(serializeCity(c),before);}
for(const direction of ['north','northeast','east','southeast','south','southwest','west','northwest']){const c=base();startTornado(c,24,24,settings({direction}));const [dx,dy]=tornadoVector(direction,24,24,48);for(let i=0;i<4;i++){assert.equal(c.emergency.tornado.x,24+i*dx);assert.equal(c.emergency.tornado.y,24+i*dy);stepFire(c);}assert.equal(c.emergency.tornado,null);for(let i=0;i<4;i++)assert.equal(c.tiles[(24+i*dy)*48+24+i*dx].type,null);for(const t of c.tiles){assert.equal(t.pipe,true);assert.equal(t.subway,true);}}
const outputs=[];for(const speed of ['slow','normal','fast']){const c=base();startTornado(c,10,24,settings({speed,distance:6}));let steps=0;while(c.emergency.active){stepFire(c);steps++;assert.ok(steps<20);}assert.equal(steps,{slow:11,normal:6,fast:3}[speed]);outputs.push(c.tiles.map(t=>t.type));}assert.deepEqual(outputs[0],outputs[1]);assert.deepEqual(outputs[1],outputs[2],'fast does not skip path positions and slow does not repeat wind hits');
const low=base(),high=base();startTornado(low,10,24,settings({intensity:1,distance:12}));startTornado(high,10,24,settings({intensity:100,distance:12}));while(low.emergency.active)stepFire(low);while(high.emergency.active)stepFire(high);assert.ok(high.emergency.infrastructureLost>low.emergency.infrastructureLost);
const edge=base();startTornado(edge,47,24,settings({distance:256,speed:'fast'}));stepFire(edge);assert.equal(edge.emergency.tornado,null,'storm exits at map boundary');
const slow=base();startTornado(slow,10,24,settings({speed:'slow',distance:8}));stepFire(slow);recompute(slow);assert.equal(slow.emergency.tornado.phase,1);const saved=validateSave(JSON.parse(serializeCity(slow)));while(slow.emergency.active){stepFire(slow);recompute(slow);stepFire(saved);recompute(saved);}assert.deepEqual(JSON.parse(serializeCity(slow)),JSON.parse(serializeCity(saved)));
const warned=base();startTornado(warned,10,24,settings({warning:true}));const before=warned.emergency.infrastructureLost;assert.ok(soundSiren(warned).ok);for(let i=0;i<8;i++)stepFire(warned);assert.equal(warned.emergency.infrastructureLost,before);assert.equal(warned.emergency.tornado.age,0);assert.equal(warned.emergency.tornado.shelter,.6);assert.doesNotThrow(()=>validateSave(JSON.parse(serializeCity(warned))));stepFire(warned);assert.equal(warned.emergency.tornado.age,1);const surprise=base();startTornado(surprise,10,24,settings());assert.equal(soundSiren(surprise).ok,false);stepFire(surprise);assert.equal(surprise.emergency.tornado.age,1);
const legacyCity=base();startTornado(legacyCity,10,24);const legacy=JSON.parse(serializeCity(legacyCity));legacy.version=115;for(const k of ['intensity','distance','speed','phase'])delete legacy.emergency.tornado[k];assert.deepEqual(validateSave(legacy).emergency,legacyCity.emergency);
for(const bad of [{phase:1},{intensity:undefined},{distance:undefined},{distance:0},{speed:'bad'},{age:24},{dx:0,dy:0}]){const payload=JSON.parse(serializeCity(legacyCity));Object.assign(payload.emergency.tornado,bad);assert.throws(()=>validateSave(payload));}
const scenario=base();attachCustomScenario(scenario,{title:'Short diagonal storm',months:12,objectives:[{metric:'funds',target:0}],events:[{type:'tornado',month:1,x:24,y:24,tornado:settings({direction:'northeast',distance:3,speed:'fast'})}]});tick(scenario);assert.equal(scenario.emergency.tornado.dx,1);assert.equal(scenario.emergency.tornado.dy,-1);assert.equal(scenario.scenario.status,'playing');stepFire(scenario);assert.equal(scenario.emergency.tornado.age,2);const restored=validateSave(JSON.parse(serializeCity(scenario)));stepFire(restored);recompute(restored);tick(restored);assert.equal(restored.scenario.status,'won');
console.log('PASS: authored tornado directions, intensity, distance, slow/normal/fast equivalence, warning/siren behavior, edge exit, saved slow phase, schema115 migration, strict current saves and a saved playable diagonal-storm challenge.');
const routine=base();attachCustomScenario(routine,{title:'Storm then recovery',months:12,objectives:[{metric:'variable1',target:1}],programs:[{name:'Emergency exercise',steps:[{kind:'action',action:{type:'tornado',x:24,y:24,tornado:settings({direction:'southwest',speed:'slow',distance:3,intensity:75})}},{kind:'action',action:{type:'variable',variable:0,operation:'set',value:1}}]}],events:[{type:'program',routine:0,month:1}]});tick(routine);assert.equal(routine.emergency.tornado.dx,-1);assert.equal(routine.emergency.tornado.dy,1);assert.equal(routine.scenario.variables[0],0);stepFire(routine);recompute(routine);const resumed=validateSave(JSON.parse(serializeCity(routine)));while(resumed.emergency.active){stepFire(resumed);recompute(resumed);}tick(resumed);assert.equal(resumed.scenario.variables[0],1);assert.equal(resumed.scenario.status,'won');assert.doesNotThrow(()=>validateSave(JSON.parse(serializeCity(resumed))));
