import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {createScenario} from '../dist/scenario-setup.js';
import {build,selection,tick} from '../dist/engine.js';
import {townGoals,showTownGuide} from '../dist/town-guide.js';
const c=createScenario('growth');c.scenario=null;
assert.equal(townGoals(c).filter(g=>g.done).length,0,'empty land cannot pass service checks');
const lay=(k,x,y,xx=x,yy=y)=>assert.ok(build(c,k,selection(k,{x,y},{x:xx,y:yy})).ok);
lay('road',14,18,34,18);lay('road',14,25,34,25);lay('road',14,18,14,25);lay('road',24,18,24,25);lay('coal',27,28);lay('residential',15,19,23,24);lay('commercial',25,19,27,24);lay('industrial',28,19,33,24);lay('landfill',15,26,20,27);
for(let y=19;y<=24;y++)lay('waterTower',13,y);lay('pipe',13,18,13,25);lay('pipe',13,18,34,18);lay('pipe',13,25,34,25);
for(let i=0;i<9;i++)tick(c);
assert.equal(townGoals(c).filter(g=>g.done).length,8,'ordinary construction and nine months can complete the exercise');
const goal=(city,id)=>townGoals(city).find(g=>g.id===id);
const bad=structuredClone(c);bad.stats.waterUsed=0;bad.stats.powerServed=0;bad.stats.unemployed=bad.stats.commuters;bad.stats.uncollectedWaste=1;bad.finance.monthsInSurplus=0;
for(const id of ['water','power','jobs','waste','budget'])assert.equal(goal(bad,id).done,false,id+' can regress');
const stale=structuredClone(c);stale.month++;assert.equal(goal(stale,'waste').done,false,'old waste history cannot prove a new month');
const idle=structuredClone(c);idle.history.at(-1).garbageGenerated=0;assert.equal(goal(idle,'waste').done,false,'zero generation is not a collection month');
const calls=[],buttons=townGoals(c).map(g=>({getAttribute:()=>g.action})),ids={returnPlay:{},reviewFromGuide:{}};
globalThis.document={querySelectorAll:()=>buttons,getElementById:id=>ids[id]};
const before=JSON.stringify(c);let html='';showTownGuide({city:()=>c,dialog:(title,body)=>{assert.equal(title,'Build your first town');html=body;},close:()=>calls.push('close'),tool:k=>calls.push(k),...Object.fromEntries(['utilities','transport','budget','play','review'].map(k=>[k,()=>calls.push(k)]))});
buttons.forEach(b=>b.onclick());ids.returnPlay.onclick();ids.reviewFromGuide.onclick();
assert.deepEqual(calls,['close','road','close','residential','utilities','play','utilities','transport','utilities','budget','close','review']);assert.match(html,/A functioning town/);assert.equal(JSON.stringify(c),before);delete globalThis.document;
const app=readFileSync(new URL('../dist/app.js',import.meta.url),'utf8');assert.match(app,/if\(city.scenario\)return scenarioPanel\(\)/);assert.match(app,/transport:showTransit/);
console.log('PASS: first-town construction, live service regression, collection proof, report shortcuts and scenario routing.');
