import {cityGrowthTargets,cityGrowthGuide,cityGrowthIssues} from '../dist/city-growth-guide.js';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {createScenario} from '../dist/scenario-setup.js';
import {build,selection,tick} from '../dist/engine.js';
import {townGoals,showTownGuide} from '../dist/town-guide.js';
const c=createScenario('growth');c.scenario=null;
assert.equal(townGoals(c).filter(g=>g.done).length,0,'empty land cannot pass service checks');
const lay=(k,x,y,xx=x,yy=y)=>assert.ok(build(c,k,selection(k,{x,y},{x:xx,y:yy})).ok);
lay('road',14,18,34,18);lay('road',14,25,34,25);lay('road',14,18,14,25);lay('road',24,18,24,25);lay('coal',27,28);lay('residential',15,19,23,24);lay('commercial',25,19,27,24);lay('industrial',28,19,33,24);lay('landfill',15,26,20,27);
for(let y=19;y<=24;y++)lay('waterTower',13,y);lay('pipe',13,18,13,25);lay('pipe',13,18,34,18);lay('pipe',13,25,34,25);
for(let i=0;i<9;i++)tick(c);
assert.equal(townGoals(c).filter(g=>g.done).length,8,'ordinary construction and nine months can complete the exercise');
const goal=(city,id)=>townGoals(city).find(g=>g.id===id);
const bad=structuredClone(c);bad.stats.waterUsed=0;bad.stats.powerServed=0;bad.stats.unemployed=bad.stats.commuters;bad.stats.uncollectedWaste=1;bad.finance.monthsInSurplus=0;
for(const id of ['water','power','jobs','waste','budget'])assert.equal(goal(bad,id).done,false,id+' can regress');
const stale=structuredClone(c);stale.month++;assert.equal(goal(stale,'waste').done,false,'old waste history cannot prove a new month');
const idle=structuredClone(c);idle.history.at(-1).garbageGenerated=0;assert.equal(goal(idle,'waste').done,false,'zero generation is not a collection month');
const calls=[],buttons=townGoals(c).map(g=>({getAttribute:()=>g.action})),ids={returnPlay:{},reviewFromGuide:{}};
globalThis.document={querySelectorAll:()=>buttons,getElementById:id=>ids[id]};
const before=JSON.stringify(c);let html='';showTownGuide({city:()=>c,dialog:(title,body)=>{assert.equal(title,'Build your first town');html=body;},close:()=>calls.push('close'),tool:k=>calls.push(k),...Object.fromEntries(['utilities','transport','budget','play','review'].map(k=>[k,()=>calls.push(k)]))});
buttons.forEach(b=>b.onclick());ids.returnPlay.onclick();ids.reviewFromGuide.onclick();
assert.deepEqual(calls,['close','road','close','residential','utilities','play','utilities','transport','utilities','budget','close','review']);assert.match(html,/A functioning town/);assert.match(html,/From town to city/);assert.deepEqual(cityGrowthTargets(c).map(t=>t.done),[false,false,false,false,false,false,false]);const grown=structuredClone(c);grown.stats.population=25000;assert.deepEqual(cityGrowthTargets(grown).map(t=>t.done),[true,true,true,false,false,false,false]);grown.stats.population=10000;assert.deepEqual(cityGrowthTargets(grown).map(t=>t.done),[true,false,false,false,false,false,false]);assert.match(cityGrowthGuide(grown),/Landfills fill over time/);assert.equal(JSON.stringify(c),before);delete globalThis.document;
const constrained=structuredClone(c);constrained.stats.population=140000;constrained.stats.demand.residential=-100;constrained.stats.demandBreakdown.residential=[{label:'Available jobs',amount:31000},{label:'Existing residents',amount:-32000},{label:'Congested roads and highways',amount:-35}];constrained.stats.economicCaps.commercial.remaining=4;
assert.ok(cityGrowthIssues(constrained).some(i=>i.id==='workplaces'&&i.action==='industrial'));
assert.ok(cityGrowthIssues(constrained).some(i=>i.id==='commercial-cap'&&i.action==='transport'));
assert.ok(cityGrowthIssues(constrained).some(i=>i.id==='traffic'));
constrained.stats.demandBreakdown.residential[0].amount=33000;
assert.ok(!cityGrowthIssues(constrained).some(i=>i.id==='workplaces'),'negative demand alone does not prove insufficient jobs');
constrained.stats.population=150000;assert.equal(cityGrowthTargets(constrained).at(-1).done,false);constrained.stats.population=200000;assert.ok(cityGrowthTargets(constrained).every(t=>t.done));constrained.stats.population=149999;assert.equal(cityGrowthTargets(constrained).at(-1).done,false);
assert.match(cityGrowthGuide(constrained),/do not predict/);
constrained.stats.residentialCap.remaining=0;constrained.stats.demandBreakdown.residential[0].amount=31000;
const issueButtons=cityGrowthIssues(constrained).map(i=>({getAttribute:()=>i.action})),issued=[];
globalThis.document={querySelectorAll:()=>issueButtons,getElementById:()=>({})};
showTownGuide({city:()=>constrained,dialog:()=>{},close:()=>issued.push('close'),tool:k=>issued.push(k),transport:()=>issued.push('transport'),utilities:()=>issued.push('utilities'),budget:()=>issued.push('budget'),review:()=>{}});
issueButtons.forEach(b=>b.onclick());assert.ok(issued.includes('park'));assert.ok(issued.includes('industrial'));assert.ok(issued.includes('transport'));delete globalThis.document;
const app=readFileSync(new URL('../dist/app.js',import.meta.url),'utf8');assert.match(app,/if\(city.scenario\)return scenarioPanel\(\)/);assert.match(app,/transport:showTransit/);
console.log('PASS: first-town construction, live service regression, collection proof, report shortcuts and scenario routing.');
