import assert from 'node:assert/strict';
import {createCity,build,planBuild,recompute,selection,idx,tick,validateSave} from '../dist/engine.js';
import {changeTransit,advanceTransit,freshTransport} from '../dist/transport.js';
function fixture(){const c=createCity('Transport',false);for(const t of c.tiles){t.terrain='land';t.nature=false;}build(c,'road',selection('road',{x:12,y:20},{x:40,y:20}));for(let y=16;y<=19;y++)for(let x=12;x<=15;x++){const t=c.tiles[idx(x,y)];t.type='residential';t.level=3;t.density=3;}for(let y=21;y<=24;y++)for(let x=36;x<=39;x++){const t=c.tiles[idx(x,y)];t.type='industrial';t.level=3;t.density=3;}recompute(c);return c;}
const c=fixture();assert.equal(c.stats.unemployed,0);assert.ok(c.stats.peakTraffic>40);assert.ok(c.stats.averageCommute>10);const traffic=c.stats.peakTraffic,pollution=c.stats.averagePollution;assert.ok(build(c,'busStop',[{x:14,y:21}]).ok);assert.equal(c.stats.activeBusStops,1);assert.ok(c.stats.busRiders>0,'one boarding stop works without a destination stop');assert.ok(c.stats.peakTraffic<traffic,'buses reduce road traffic');assert.ok(c.stats.averagePollution<pollution,'fewer cars reduce pollution');assert.ok(c.stats.transitFare>0);assert.equal(c.stats.transitExpense,5);const bus=c.tiles[idx(14,21)];assert.equal(bus.busRiders,c.stats.busRiders);
assert.ok(build(c,'bulldoze',[{x:26,y:20}]).ok);assert.equal(c.stats.busRiders,0,'a stop cannot bypass a broken road');assert.equal(c.stats.unemployed,c.stats.commuters);build(c,'road',[{x:26,y:20}]);changeTransit(c,0);recompute(c);assert.equal(c.stats.busRiders,0);for(let i=0;i<6;i++){advanceTransit(c);recompute(c);}assert.equal(c.stats.transitStrike,true);changeTransit(c,100);recompute(c);assert.equal(c.stats.transitStrike,true);advanceTransit(c);recompute(c);assert.equal(c.stats.transitStrike,false);assert.ok(c.stats.busRiders>0);
const b=fixture();for(let y=0;y<48;y++)for(let x=24;x<=27;x++){const t=b.tiles[idx(x,y)];t.terrain='water';t.type=null;}recompute(b);assert.equal(b.stats.unemployed,b.stats.commuters);const crossing=selection('road',{x:23,y:20},{x:28,y:20});assert.equal(planBuild(b,'road',crossing).cost,400);assert.equal(build(b,'road',crossing).ok,true);assert.equal(b.stats.bridgeTiles,4);assert.equal(b.stats.unemployed,0,'bridge joins transport networks');assert.equal(b.tiles[idx(25,20)].bridgeAxis,'x');assert.equal(planBuild(b,'road',[{x:25,y:20}]).ok,false,'bridge endpoints must be dry');assert.equal(planBuild(b,'road',[{x:23,y:20},{x:25,y:20},{x:28,y:20}]).ok,false,'gaps are not a bridge');
const invalid=JSON.stringify(b);assert.equal(build(b,'road',selection('road',{x:23,y:21},{x:26,y:21})).ok,false);assert.equal(JSON.stringify(b),invalid,'invalid partial span is atomic');const poor=fixture();for(let x=24;x<=27;x++){poor.tiles[idx(x,20)].terrain='water';poor.tiles[idx(x,20)].type=null;}poor.funds=399;assert.equal(build(poor,'road',crossing).ok,false);
const save=validateSave(JSON.parse(JSON.stringify(b)));assert.deepEqual(save.stats,b.stats);assert.deepEqual(save.transport,b.transport);const bad=JSON.parse(JSON.stringify(b));bad.tiles[idx(25,20)].bridgeAxis='z';assert.throws(()=>validateSave(bad));const old=createCity();old.version=4;delete old.transport;assert.deepEqual(validateSave(old).transport,freshTransport());
const funds=c.funds,balance=c.stats.balance;tick(c);assert.equal(c.funds,funds+balance,'fares and transit expenses flow through ledger');const before=JSON.stringify(c);assert.equal(changeTransit(c,151).ok,false);assert.equal(JSON.stringify(c),before);
console.log('PASS: workplace routing/capacity, congestion, bus boarding without destination stop, disconnected roads, reduced traffic/pollution, transit funding/strikes/recovery, dry-bank bridge construction and costs, atomic rejection, save migration, ledger conservation.');
