import assert from 'node:assert/strict';
import {generateCity} from '../dist/terrain-generator.js';
import {build,planBuild,recompute,selection,idx,validateSave} from '../dist/engine.js';
import {streetGraph} from '../dist/highway.js';
import {routeLength} from '../dist/tunnels.js';
import {serializeCity} from '../dist/save.js';
const route=selection('road',{x:19,y:20},{x:28,y:20});function base(){const c=generateCity({water:0,trees:0,mountains:0});for(let x=20;x<=27;x++)c.tiles[idx(x,20)].elevation=Math.min(x-19,28-x,3);return c;}
for(const mode of ['road','rail','highway']){const c=base();c.tiles[idx(23,20)].type='park';const before=c.funds,plan=planBuild(c,mode,route);assert.equal(plan.tunnel.mode,mode);assert.ok(build(c,mode,route).ok);assert.equal(c.tunnels.length,1);assert.equal(c.tiles[idx(23,20)].type,'park','surface is preserved');assert.equal(c.funds,before-plan.cost);assert.equal(c.stats[mode==='road'?'roadTunnelTiles':mode==='rail'?'railTunnelTiles':'highwayTunnelTiles'],8);if(mode!=='rail'){const offset=mode==='highway'?c.tiles.length:0,g=streetGraph(c);assert.equal(g.groups[idx(19,20)+offset],g.groups[idx(28,20)+offset]);}assert.equal(routeLength(c,[idx(19,20),idx(28,20)]),10,'routing counts real length');assert.equal(build(c,'subway',[{x:23,y:20}]).ok,false);assert.equal(build(c,'lower',[{x:23,y:20}]).ok,false);const saved=validateSave(JSON.parse(serializeCity(c)));assert.deepEqual(saved.tunnels,c.tunnels);assert.deepEqual(saved.stats,c.stats);assert.ok(build(c,mode==='road'?'bulldoze':mode==='rail'?'removeRail':'removeHighway',[{x:19,y:20}]).ok);assert.equal(c.tunnels.length,0);assert.equal(c.tiles[idx(23,20)].type,'park');}
const invalid=base();invalid.tiles[idx(23,20)].subway=true;assert.equal(planBuild(invalid,'road',route).ok,false);invalid.tiles[idx(23,20)].subway=false;invalid.funds=10;assert.equal(planBuild(invalid,'road',route).ok,false);const snap=serializeCity(invalid);assert.equal(build(invalid,'road',route).ok,false);assert.equal(serializeCity(invalid),snap);
const rail=base();build(rail,'rail',route);build(rail,'trainStation',[{x:18,y:20}]);build(rail,'trainStation',[{x:29,y:20}]);build(rail,'residential',[{x:16,y:20}]);build(rail,'industrial',[{x:31,y:20}]);rail.tiles[idx(16,20)].level=1;rail.tiles[idx(31,20)].level=1;recompute(rail);assert.ok(rail.stats.trainRiders>0,'rail tunnel carries commuters');assert.ok(rail.stats.averageCommute>=10,'train journeys include underground distance');build(rail,'removeRail',[{x:19,y:20}]);assert.equal(rail.stats.trainRiders,0,'removing portal breaks commute');const malformed=JSON.parse(serializeCity(base()));malformed.tunnels=[{mode:'road',a:idx(19,20),b:idx(28,20),elevation:0}];assert.throws(()=>validateSave(malformed));
console.log('PASS: road/rail/highway tunnels, preserved surface, cost, real route distance, protected cover/subway conflicts, atomic affordability, portal removal, commuter integration and save validation.');
