import assert from 'node:assert/strict';
import {generateCity} from '../dist/terrain-generator.js';
import {advanceRewards,rewardCondition,REWARDS,validateRewards,freshRewards} from '../dist/rewards.js';
import {build,recompute,validateSave} from '../dist/engine.js';
import {serializeCity} from '../dist/save.js';
const c=generateCity({water:0,mountains:0,trees:0});
Object.assign(c.stats,{population:0,aura:0,balance:-100,education:69.999,activeServices:{college:0}});
c.month=1;assert.equal(advanceRewards(c).includes('university'),false);
c.stats.education=70;c.month=2;assert.equal(rewardCondition(c,'university'),true);
assert.equal(advanceRewards(c).includes('university'),true,'one qualifying evaluation grants the offer');
assert.deepEqual(advanceRewards(c),[],'same month does not offer again');
c.stats.education=0;c.month++;advanceRewards(c);assert.equal(c.rewards.earned.university,2);
c.funds=0;assert.equal(REWARDS.university.cost,0);assert.equal(build(c,'university',[{x:20,y:20}]).ok,true,'earned university needs no construction funds');assert.equal(c.funds,0);
assert.equal(build(c,'university',[{x:30,y:30}]).ok,false,'one university per city');
recompute(c);let saved=JSON.parse(serializeCity(c));assert.equal(saved.version,132);
const old=structuredClone(saved);old.version=130;for(let i=0;i<old.tiles.length;i++){const t=old.tiles[i];if(t.type==='university'&&(t.x>=24||t.y>=24))old.tiles[i]={...old.tiles[0],x:t.x,y:t.y};delete old.tiles[i].universitySize;}old.rewards.streaks.university=6;
const restored=validateSave(old);assert.equal(restored.rewards.earned.university,2);assert.equal(restored.rewards.streaks.university,1);assert.equal(restored.tiles.filter(t=>t.type==='university').length,16,'existing campus stays intact');assert.deepEqual(validateSave(JSON.parse(serializeCity(restored))).rewards,restored.rewards);
const pending=freshRewards();pending.lastMonth=5;pending.streaks.university=5;
assert.equal(validateRewards(pending,5,130).streaks.university,0,'obsolete unearned progress cannot grant a reward');
pending.streaks.university=7;assert.throws(()=>validateRewards(pending,5,130));
saved.rewards.streaks.university=2;assert.throws(()=>validateSave(saved),'new saves reject obsolete six-month streak values');
console.log('PASS: university education-only unlock, exact normalized threshold, next-month offer, free construction, unique placement and safe legacy reward migration.');
