import assert from 'node:assert/strict';
import {createCity,recompute,validateSave,tick} from '../dist/engine.js';
import {advanceUnrest,setRandomRiots,unrestRisk} from '../dist/riots.js';
import {serializeCity} from '../dist/save.js';
const c=createCity();assert.equal(c.emergency.randomRiots,false);c.stats.averageCrime=100;c.stats.aura=0;advanceUnrest(c);assert.equal(c.emergency.unrestMonths,0);setRandomRiots(c,true);for(let i=0;i<5;i++){c.month++;assert.equal(advanceUnrest(c),false);}assert.equal(unrestRisk(c),0);let triggered=false;for(let i=0;i<500&&!triggered;i++){c.month++;triggered=advanceUnrest(c);}assert.ok(triggered);assert.equal(c.emergency.unrestMonths,0);assert.equal(setRandomRiots(c,false).ok,false);assert.deepEqual(validateSave(JSON.parse(serializeCity(c))).emergency,c.emergency);
const good=createCity();setRandomRiots(good,true);good.emergency.unrestMonths=8;good.stats.averageCrime=20;good.stats.aura=60;assert.equal(advanceUnrest(good),false);assert.equal(good.emergency.unrestMonths,0);assert.equal(unrestRisk(good),0);good.stats.averageCrime=70;advanceUnrest(good);assert.equal(good.emergency.unrestMonths,1);setRandomRiots(good,false);assert.equal(good.emergency.unrestMonths,0);
const live=createCity();live.civic.education=0;live.finance.taxes.residential=20;recompute(live);assert.ok(live.stats.aura<40||live.stats.averageCrime>40);setRandomRiots(live,true);tick(live);assert.equal(live.emergency.unrestMonths,1);const loaded=validateSave(JSON.parse(serializeCity(live)));assert.equal(loaded.emergency.unrestMonths,1);tick(live);tick(loaded);assert.deepEqual(loaded.emergency,live.emergency);
const old=JSON.parse(serializeCity(good));old.version=33;delete old.emergency.randomRiots;delete old.emergency.unrestMonths;assert.equal(validateSave(old).emergency.randomRiots,false);old.version=34;assert.throws(()=>validateSave(old),/unrest/);
console.log('PASS: optional sustained unrest, grace period, seeded outbreaks, recovery reset, monthly integration, save continuity and migration.');
