import assert from 'node:assert/strict';
import {VERSION,createCity,build,recompute,tick,idx,selection,validateSave,planBuild} from '../dist/engine.js';
import {LANDFILL_CAPACITY,recomputeWater} from '../dist/utilities.js';
const at=(c,x,y)=>c.tiles[idx(x,y)];
function blank(){const c=createCity('Utilities',false);for(const t of c.tiles){t.terrain='land';t.nature=false;}at(c,10,20).terrain='water';return c;}
function lay(c,tool,x,y,x2=x,y2=y,density=1){const result=build(c,tool,selection(tool,{x,y},{x:x2,y:y2}),density);assert.ok(result.ok,`${tool}: ${result.error}`);}
const c=blank();lay(c,'pump',11,20);assert.equal(at(c,11,20).pumpCapacity,0,'a freshwater pump still needs power');lay(c,'coal',15,24);assert.ok(at(c,11,20).pumpCapacity>0&&at(c,11,20).pumpCapacity<=500,'powered pump operates, with pollution reducing output');lay(c,'pump',25,24);assert.equal(at(c,25,24).pumpCapacity,0,'powered inland pump has zero output');
lay(c,'road',17,20,29,20);lay(c,'residential',20,19);lay(c,'industrial',23,19);lay(c,'pipe',11,20,27,20);assert.equal(at(c,20,19).watered,true);assert.equal(at(c,20,20).type,'road','underground pipes preserve roads');assert.equal(at(c,20,20).pipe,true);assert.equal(at(c,27,27).watered,true,'radius seven inclusive');assert.equal(at(c,27,28).watered,false,'radius eight excluded');
lay(c,'removePipe',15,20);assert.equal(at(c,20,20).pipeWet,false,'severing the main dries downstream pipes');assert.equal(at(c,24,19).watered,false,'watered zones cannot relay supply');assert.equal(at(c,20,20).type,'road');lay(c,'pipe',15,20);assert.equal(at(c,24,19).watered,true);
lay(c,'removePipe',20,20);assert.equal(at(c,20,20).type,'road');assert.equal(at(c,20,20).pipe,false);lay(c,'pipe',20,20);
lay(c,'residential',20,19,20,19,3);assert.equal(at(c,20,19).density,3);assert.equal(planBuild(c,'residential',[{x:20,y:19}],0).ok,false);lay(c,'landfill',25,22,28,22);lay(c,'park',20,18);lay(c,'park',19,18); // Parks support medium-density land value while this test isolates water availability.
for(let m=0;m<30;m++)tick(c);assert.ok(at(c,20,19).level>1,'water enables growth above light density');const level=at(c,20,19).level;
lay(c,'bulldoze',11,20);assert.equal(at(c,11,20).pipe,true,'bulldozing a pump preserves underground pipes');for(let m=0;m<8;m++)tick(c);assert.ok(at(c,20,19).level<level,'water loss degrades denser buildings');assert.equal(at(c,20,19).level,0,'previously supplied buildings abandon after prolonged water loss');assert.equal(at(c,20,19).abandonedLevel,1);assert.equal(at(c,20,19).waterEstablished,true);
const dry=blank();lay(dry,'coal',20,24);lay(dry,'road',17,20,28,20);lay(dry,'residential',20,19,20,19,3);lay(dry,'industrial',23,19,23,19,3);lay(dry,'landfill',25,22,27,22);for(let m=0;m<50;m++)tick(dry);assert.equal(at(dry,20,19).level,1,'dense designation alone does not create tall buildings');
const waste=blank();lay(waste,'road',15,20,35,20);lay(waste,'residential',17,19);lay(waste,'industrial',20,19);lay(waste,'coal',20,24);at(waste,17,19).level=1;at(waste,20,19).level=1;tick(waste);assert.ok(waste.stats.uncollectedWaste>0);lay(waste,'landfill',33,21);tick(waste);assert.equal(waste.stats.uncollectedWaste,0);assert.ok(at(waste,33,21).garbage>0);assert.equal(build(waste,'bulldoze',[{x:33,y:21}]).ok,false,'landfill cannot be bulldozed');assert.equal(build(waste,'dezone',[{x:33,y:21}]).ok,false,'buried garbage blocks de-zoning');
at(waste,33,21).garbage=LANDFILL_CAPACITY;tick(waste);assert.ok(waste.stats.uncollectedWaste>0,'full landfill leaves excess garbage in town');
for(let x=25;x<=35;x++)at(waste,x,20).type=null;recompute(waste);at(waste,33,21).garbage=1;tick(waste);assert.equal(at(waste,33,21).garbage,.5);tick(waste);assert.equal(at(waste,33,21).garbage,0,'decommissioned landfill decomposes');lay(waste,'dezone',33,21);assert.equal(at(waste,33,21).type,null);
const isolated=blank();lay(isolated,'pump',11,20);lay(isolated,'coal',14,24);lay(isolated,'pipe',11,20,13,20);lay(isolated,'pipe',36,20,40,20);assert.equal(at(isolated,36,20).pipeWet,false);assert.equal(at(isolated,36,20).watered,false,'remote pump capacity cannot supply isolated pipes');
const scarce=blank();lay(scarce,'pump',11,20);lay(scarce,'pipe',11,20,35,20);at(scarce,11,20).powered=true;for(let y=13;y<=27;y++)for(let x=17;x<=35;x++){const t=at(scarce,x,y);t.type='residential';t.level=3;t.density=3;}const supply=recomputeWater(scarce);assert.ok(supply.waterUsed<=500);assert.ok(supply.watered<200,'finite capacity leaves some lots dry');
const round=validateSave(JSON.parse(JSON.stringify(c)));assert.deepEqual(round.stats,c.stats);assert.equal(at(round,20,19).density,3);assert.equal(at(round,20,20).pipe,true);
const legacy=createCity();legacy.version=1;for(const t of legacy.tiles){delete t.pipe;delete t.density;delete t.garbage;delete t.waste;}const migrated=validateSave(legacy);assert.equal(migrated.version,VERSION);assert.ok(migrated.tiles.every(t=>!t.pipe&&t.density===1&&t.garbage===0&&t.waste===0));const invalid=JSON.parse(JSON.stringify(c));invalid.tiles[0].garbage=-1;assert.throws(()=>validateSave(invalid));invalid.tiles[0].garbage=0;invalid.tiles[0].pipe='yes';assert.throws(()=>validateSave(invalid));
console.log('PASS: pump requirements, pipe continuity, seven-tile radius, no water relay, underground preservation, isolated/limited capacity, density growth and water loss, landfill transport/fullness/decomposition/removal, v1 migration and v2 utility saves.');
