import assert from 'node:assert/strict';
import {createCity,build} from '../dist/engine.js';
import {CityRenderer} from '../dist/renderer.js';
import {trafficPaths,trafficVehicles} from '../dist/traffic-visuals.js';
import {railVehicles} from '../dist/rail-visuals.js';
import {serializeCity} from '../dist/save.js';
const c=createCity('Far-side traffic',false,256);for(const t of c.tiles){t.terrain='land';t.elevation=0;t.nature=false;t.type=null;if(t.x<101&&t.y<101||t.x>=170&&t.x<=230&&t.y>=170&&t.y<=230){t.type='road';t.traffic=100;if(t.x>=190&&t.x<=210&&t.y>=190&&t.y<=210&&t.y%4===0||t.x<101&&t.y<101&&t.y%4===0){t.rail=true;t.railRiders=30;}if(t.x>=170&&t.x<=230&&t.y===200){t.highway=true;t.highwayTraffic=100;}}}
assert.ok(trafficVehicles(c,0).every(v=>v.y<101),'old whole-map budget is spent outside the far-side view');assert.ok(railVehicles(c,0).every(v=>v.y<101));
const noop=()=>{},ctx=new Proxy({createLinearGradient:()=>({addColorStop:noop}),createRadialGradient:()=>({addColorStop:noop}),measureText:()=>({width:0})},{get:(o,k)=>o[k]??noop,set:(o,k,v)=>(o[k]=v,true)});globalThis.document={hidden:false,querySelector:()=>null};let current=c,cars=[],trains=[];
const r=Object.assign(Object.create(CityRenderer.prototype),{getCity:()=>current,ctx,dpr:1,w:1000,h:700,rotation:0,zoom:1,pan:{x:0,y:0},sprites:[],reducedMotion:{matches:false},vehicleTime:0,preferences:{pedestriansVisible:false},hover:null,tool:'query',layer:'city',drawVehicle:v=>cars.push(v),drawTrain:v=>trains.push(v)});
const center=()=>{r.pan={x:0,y:0};const p=r.project(200,200);r.pan={x:r.w/2-p.x,y:r.h/2-p.y};};const draw=()=>{cars=[];trains=[];r.draw();};const before=serializeCity(c);
for(const rotation of [0,1,2,3]){r.rotation=rotation;center();draw();assert.ok(cars.length>100&&cars.length<=180);assert.ok(trains.length>0&&trains.length<=72);assert.ok(cars.every(v=>v.x>150&&v.y>150));assert.ok(cars.some(v=>v.elevated));assert.ok(trains.every(v=>v.x>150&&v.y>150));assert.ok(new Set(cars.map(v=>(v.x>=200?1:0)+','+(v.y>=200?1:0))).size>=3,'samples spread around the viewed district');const paths=r.trafficRoutes,rails=r.trainRoutes,still=structuredClone(cars);draw();assert.deepEqual(cars,still);assert.equal(r.trafficRoutes,paths);assert.equal(r.trainRoutes,rails);r.vehicleTime+=.5;draw();assert.notDeepEqual(cars,still);assert.equal(r.trafficRoutes,paths);r.pan.x+=30;draw();assert.notEqual(r.trafficRoutes,paths);assert.equal(r.trainRoutes,rails);}
assert.equal(serializeCity(c),before,'view sampling and caches never mutate the city');r.preferences.vehicleAnimations=false;draw();assert.equal(cars.length,0);assert.equal(trains.length,0);r.preferences.vehicleAnimations=true;r.zoom=.3;draw();assert.equal(cars.length,0);r.zoom=1;center();draw();const paths=r.trafficRoutes,rails=r.trainRoutes;
assert.ok(build(c,'bulldoze',[{x:200,y:200}]).ok);draw();assert.notEqual(r.trafficRoutes,paths);assert.notEqual(r.trainRoutes,rails);assert.equal(cars.length,0,'recomputed zero road loads clear cached cars');assert.equal(trains.length,0,'broken/unserved rails clear cached trains');current=createCity('Empty replacement city',false,96);r.preferences.vehicleAnimations=false;r.pan={x:0,y:0};draw();assert.equal(cars.length,0);assert.equal(trains.length,0);assert.equal(r.trafficCity,current);
console.log('PASS: actual renderer shows far-side road/highway traffic and trains after whole-map budgets would be exhausted, spreads bounded samples across four camera rotations, preserves pause and motion, refreshes on pan/build/city changes and honors visibility preferences without city mutation.');

const small=createCity('Bounded sample',false);for(const t of small.tiles)Object.assign(t,{terrain:'land',type:'road',traffic:100});const view={bounds:{x0:0,y0:0,x1:47,y1:47},contains:()=>true};assert.deepEqual(trafficPaths(small,180,view),trafficPaths(small,20000,view).slice(0,180),'bounded heap retains the same deterministic spatial sample as full sorting');
