import assert from 'node:assert/strict';
import {createCity,build,selection,idx,recompute,tick,validateSave} from '../dist/engine.js';
import {processGarbage,wasteCapacity} from '../dist/utilities.js';
function base(){const c=createCity('Waste test',false);for(const t of c.tiles){t.terrain='land';t.nature=false;}build(c,'road',selection('road',{x:12,y:20},{x:32,y:20}));build(c,'coal',[{x:20,y:22}]);build(c,'residential',[{x:15,y:19}]);build(c,'industrial',[{x:17,y:19}]);c.tiles[idx(15,19)].level=1;c.tiles[idx(17,19)].level=1;recompute(c);return c;}
const c=base();assert.equal(build(c,'recycling',[{x:19,y:21}]).ok,false);c.month=240;assert.ok(build(c,'recycling',[{x:19,y:21}]).ok);const r=c.tiles[idx(19,21)],h=c.tiles[idx(15,19)];processGarbage(c);assert.ok(Math.abs(r.recycledLastMonth-(8+.96+.72)*.3)<1e-8);assert.ok(Math.abs(h.waste-.24*.7)<1e-8);const standard=wasteCapacity(c,r);c.civic.ordinances.trashPresort=true;assert.equal(wasteCapacity(c,r),standard*1.5);processGarbage(c);assert.ok(Math.abs(r.recycledLastMonth-(8+.96+.72)*.45)<1e-8);r.powered=false;processGarbage(c);assert.equal(r.recycledLastMonth,0,'unpowered recycling stops');recompute(c);r.roadIds=[999];processGarbage(c);assert.equal(r.recycledLastMonth,.72*.45,'isolated recycler processes only its own production');
const burn=base();assert.ok(build(burn,'incinerator',[{x:19,y:21}]).ok);const inc=burn.tiles[idx(19,21)],home=burn.tiles[idx(15,19)];home.waste=150;processGarbage(burn);assert.equal(inc.burnedLastMonth,100);assert.ok(home.waste>=50,'monthly capacity limits disposal');const clearAir=inc.airPollution;recompute(burn);assert.ok(inc.airPollution>clearAir,'burning causes air pollution');inc.age=600;assert.equal(wasteCapacity(burn,inc),25);const age=inc.age;tick(burn);assert.equal(inc.age,age+1);build(burn,'bulldoze',[inc]);build(burn,'incinerator',[inc]);assert.equal(wasteCapacity(burn,inc),100);assert.equal(inc.burnedLastMonth,0);
const energy=base();assert.equal(build(energy,'wasteEnergy',[{x:19,y:21}]).ok,false);energy.month=600;build(energy,'wasteEnergy',[{x:19,y:21}]);const w=energy.tiles[idx(19,21)];energy.tiles[idx(15,19)].waste=80;processGarbage(energy);recompute(energy);assert.ok(energy.stats.wastePower>160);build(energy,'bulldoze',[{x:20,y:22}]);assert.equal(energy.tiles[idx(15,19)].powered,true,'actual waste combustion can power the grid without coal');for(const t of energy.tiles){t.waste=0;if(['residential','industrial'].includes(t.type))t.level=0;}processGarbage(energy);recompute(energy);assert.equal(energy.stats.wastePower,0,'no garbage means no generated electricity');assert.equal(energy.tiles[idx(15,19)].powered,false);assert.deepEqual(validateSave(JSON.parse(JSON.stringify(energy))).stats,energy.stats);
const priority=base();build(priority,'incinerator',[{x:19,y:21}]);build(priority,'landfill',[{x:30,y:21}]);priority.tiles[idx(15,19)].waste=120;processGarbage(priority);assert.equal(priority.tiles[idx(19,21)].burnedLastMonth,100);assert.ok(priority.tiles[idx(30,21)].garbage>28&&priority.tiles[idx(30,21)].garbage<30,'only residual waste is buried');
const legacy=JSON.parse(JSON.stringify(createCity()));legacy.version=12;delete legacy.civic.ordinances.trashPresort;for(const t of legacy.tiles){delete t.burnedLastMonth;delete t.recycledLastMonth;}const restored=validateSave(legacy);assert.equal(restored.civic.ordinances.trashPresort,false);assert.equal(restored.tiles[0].burnedLastMonth,0);
console.log('PASS: recycling availability, presort and limited share, power/road isolation, burn capacity/pollution/aging/replacement, waste-powered grid and fuel exhaustion, landfill priority and save migration.');
