import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import {createCity,build,recompute,validateSave} from '../dist/engine.js';
import {serializeCity} from '../dist/save.js';
import {advanceWaste,processGarbage} from '../dist/utilities.js';
import {wasteFacilityData,wasteFacilityReport,installWasteFacilityLinks} from '../dist/waste-facility-report.js';
const c=createCity('Maintenance',false);c.startYear=2050;c.funds=100000;for(const t of c.tiles){t.terrain='land';t.nature=false;t.elevation=0;}
const put=(type,x,y)=>assert.ok(build(c,type,[{x,y}]).ok,type);assert.match(wasteFacilityReport(c),/No recycling centers/);for(const x of [10,11,12])put('road',x,11);for(const [type,x]of [['incinerator',10],['recycling',11],['wasteEnergy',12]])put(type,x,10);
let rows=wasteFacilityData(c);assert.equal(rows.find(r=>r.name==='Recycling center').status,'No electricity');put('coal',14,14);assert.ok(wasteFacilityData(c).every(r=>r.ready));
const burner=c.tiles[10*48+10],recycler=c.tiles[10*48+11];burner.age=600;recycler.age=360;recompute(c);rows=wasteFacilityData(c);assert.equal(rows[0].tile,10*48+10);assert.equal(rows[0].capacity,25);assert.equal(rows[0].newCapacity,100);assert.equal(rows[0].nextYear,22);const forecast=new Map(rows.map(r=>[r.tile,r.nextYear]));for(let i=0;i<12;i++)advanceWaste(c);assert.ok(wasteFacilityData(c).every(r=>r.capacity===forecast.get(r.tile)));
c.civic.ordinances.trashPresort=true;const recycled=wasteFacilityData(c).find(r=>r.tile===10*48+11);assert.equal(recycled.newCapacity,90);assert.ok(recycled.capacity<90);assert.ok(recycled.nextYear<recycled.capacity);
put('industrial',8,10);c.tiles[10*48+8].level=1;c.tiles[10*48+8].waste=300;recompute(c);processGarbage(c);assert.ok(wasteFacilityData(c).some(r=>r.processed>0));assert.ok(wasteFacilityData(c).every(r=>r.processed<=r.capacity));const before=serializeCity(c);wasteFacilityReport(c);assert.equal(serializeCity(c),before);assert.deepEqual(wasteFacilityData(validateSave(JSON.parse(before))),wasteFacilityData(c));
const visits=[],buttons=[{getAttribute:()=>String(burner.y*48+burner.x)},{getAttribute:()=>'-1'},{getAttribute:()=>String(11*48+10)}];installWasteFacilityLinks(c,p=>visits.push(p),{querySelectorAll:()=>buttons});for(const b of buttons)b.onclick();assert.deepEqual(visits,[{x:10,y:10}]);
put('bulldoze',10,10);put('incinerator',10,10);assert.equal(wasteFacilityData(c).find(r=>r.tile===10*48+10).capacity,100,'normal replacement resets age');
const app=fs.readFileSync(new URL('../dist/app.js',import.meta.url),'utf8'),start=app.indexOf('function showUtilities()'),end=app.indexOf('function download(',start),calls=[],controls=new Map();let visit,html='';const context={city:c,dialog:(_,body)=>html=body,powerGridReport:()=>'',waterGridReport:()=>'',wasteFacilityReport,conservationReport:()=>'',installPowerGridLinks:()=>{},installWaterGridLinks:()=>{},installWasteFacilityLinks:(_,cb)=>visit=cb,$:key=>{if(!controls.has(key))controls.set(key,{});return controls.get(key);},closeDialog:()=>calls.push('close'),setLayer:v=>calls.push(v),setTool:v=>calls.push(v),pointer:{},renderer:{},focusEmergencyLocation:(_,p)=>calls.push(`${p.x},${p.y}`),update:()=>calls.push('update'),showQuery:p=>calls.push(`inspect ${p.x},${p.y}`),showReview(){}};vm.runInNewContext(app.slice(start,end)+'showUtilities();',context);assert.match(html,/Garbage facility maintenance/);visit({x:10,y:10});assert.deepEqual(calls,['close','city','query','10,10','update','inspect 10,10']);assert.equal(context.pointer,null);
console.log('PASS: facility maintenance order, current/next-year aging, presort capacity, power readiness, actual throughput, saved inspection data, ordinary replacement and Utilities-to-query navigation.');
