import {rewardWasteReport} from '../dist/reward-waste.js';
import fs from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
import {createCity,build,selection,recompute,validateSave} from '../dist/engine.js';
import {serializeCity} from '../dist/save.js';
import {waterGridData,waterGridReport,installWaterGridLinks} from '../dist/water-grid-report.js';
import {connectionCandidates,addConnection,signDeal} from '../dist/region.js';
const base=()=>{const c=createCity('Water diagnostics',false);c.funds=1000000;c.startYear=2050;for(const t of c.tiles){t.terrain='land';t.nature=false;t.elevation=0;}recompute(c);return c;};
const put=(c,type,x,y,xx=x,yy=y)=>assert.ok(build(c,type,selection(type,{x,y},{x:xx,y:yy},c.size),3).ok,type);
const c=base();put(c,'coal',8,8);put(c,'waterTower',12,12);put(c,'pipe',12,12);put(c,'coal',34,34);put(c,'waterTower',38,38);put(c,'pipe',38,38);put(c,'residential',39,38,40,38);for(let x=39;x<=40;x++)c.tiles[38*48+x].level=3;put(c,'residential',25,25);c.tiles[38*48+38].age=600;recompute(c);
let data=waterGridData(c),dry=data.networks.find(g=>g.unwatered);assert.ok(c.stats.waterCapacity>c.stats.waterDemand,'citywide surplus hides local shortage');assert.ok(dry);assert.equal(dry.status,'Supply shortage');assert.equal(c.tiles[dry.anchor].watered,false);assert.equal(data.uncovered.length,1);assert.equal(data.uncovered[0],25*48+25);assert.match(waterGridReport(c),/View shortage/);assert.ok(data.sources.find(p=>p.tile===38*48+38).efficiency<1);
const before=serializeCity(c);assert.deepEqual(waterGridData(validateSave(JSON.parse(before))),data);waterGridReport(c);assert.equal(serializeCity(c),before);
const visits=[],location={getAttribute:()=>String(dry.anchor)},inspection={getAttribute:()=>String(38*48+38)},invalid={getAttribute:()=>'-1'};installWaterGridLinks(c,(point,inspect)=>visits.push({point,inspect}),{querySelectorAll:s=>s==='[data-water-location]'?[location,invalid]:[inspection]});location.onclick();inspection.onclick();invalid.onclick();assert.equal(visits.length,2);assert.deepEqual(visits[1],{point:{x:38,y:38},inspect:true});assert.equal(visits[0].inspect,false);
put(c,'pipe',12,12,38,12);put(c,'pipe',38,12,38,38);recompute(c);data=waterGridData(c);assert.equal(data.networks.length,1);assert.equal(data.networks[0].unwatered,0);assert.equal(data.networks[0].status,'Supplied');assert.equal(data.uncovered.length,1,'joining supply does not water remote uncovered ground');
// Overlapping disconnected service areas can supply the same homes: don't report
// false outages on the empty network or add its reachable demand citywide.
const overlap=base();put(overlap,'coal',8,8);put(overlap,'waterTower',12,12);put(overlap,'pipe',12,12);put(overlap,'pipe',16,12);put(overlap,'residential',14,12);recompute(overlap);data=waterGridData(overlap);assert.equal(data.networks.length,2);assert.ok(data.networks.every(g=>g.demand===1&&g.unwatered===0));assert.equal(data.networks.reduce((s,g)=>s+g.used,0),1);assert.match(waterGridReport(overlap),/demand totals are not additive/);
const isolated=base();put(isolated,'waterTower',12,12);assert.equal(waterGridData(isolated).networks[0].status,'No connected pipes');put(isolated,'pipe',12,12);put(isolated,'residential',13,12);assert.equal(waterGridData(isolated).networks[0].status,'No supply');
const trade=base();put(trade,'pipe',42,20,47,20);put(trade,'residential',40,20);assert.ok(addConnection(trade,connectionCandidates(trade).find(p=>p.kind==='water')).ok);assert.ok(signDeal(trade,0,'water','import',50).ok);recompute(trade);data=waterGridData(trade);assert.equal(data.sources.length,0);assert.equal(data.networks[0].used,1);assert.equal(data.networks[0].unwatered,0);assert.match(waterGridReport(trade),/Connected neighbor imports/);
// Execute the actual utilities dialog and its water navigation callback.
const app=fs.readFileSync(new URL('../dist/app.js',import.meta.url),'utf8'),start=app.indexOf('function showUtilities()'),end=app.indexOf('function download(',start),buttons=new Map(),calls=[];let navigate,html='';
const context={rewardWasteReport,city:c,dialog:(_title,body)=>html=body,powerGridReport:()=>'',wasteFacilityReport:()=>'',installWasteFacilityLinks:()=>{},waterGridReport,conservationReport:()=>'',installPowerGridLinks:()=>{},installWaterGridLinks:(_city,visit)=>navigate=visit,$:key=>{if(!buttons.has(key))buttons.set(key,{});return buttons.get(key);},closeDialog:()=>calls.push('close'),setLayer:v=>calls.push(v),setTool:v=>calls.push(v),pointer:{},renderer:{},focusEmergencyLocation:(_renderer,point)=>calls.push(`${point.x},${point.y}`),update:()=>calls.push('update'),showQuery:point=>calls.push(`inspect ${point.x},${point.y}`),showReview:()=>{}};
vm.runInNewContext(app.slice(start,end)+'showUtilities();',context);assert.match(html,/<h3>Water networks/);navigate({x:38,y:38},true);assert.deepEqual(calls,['close','water','query','38,38','update','inspect 38,38']);assert.equal(context.pointer,null);
console.log('PASS: local water shortage despite global surplus, joining grids, uncovered homes, overlapping service, dry pipes, isolated sources, imported supply, maintenance data and navigation/save continuity.');
