import assert from 'node:assert/strict';
import {createCity,build,idx,selection,recompute,tick,validateSave} from '../dist/engine.js';
import {recomputeWater} from '../dist/utilities.js';
function base(){const c=createCity('Water works',false);for(const t of c.tiles){t.terrain='land';t.waterKind='fresh';t.nature=false;}return c;}
const c=base();build(c,'coal',[{x:25,y:20}]);assert.ok(build(c,'waterTower',[{x:23,y:20}]).ok);build(c,'pipe',selection('pipe',{x:23,y:20},{x:20,y:20}));build(c,'residential',[{x:20,y:21}]);recompute(c);const tower=c.tiles[idx(23,20)];const initialCapacity=tower.pumpCapacity;assert.ok(initialCapacity>0&&initialCapacity<=120);assert.equal(c.tiles[idx(20,21)].watered,true,'inland tower supplies connected neighborhood');assert.equal(c.stats.waterUpkeep,8);tower.age=600;recompute(c);assert.ok(Math.abs(tower.pumpCapacity-initialCapacity*.25)<=1);const age=tower.age;tick(c);assert.equal(tower.age,age+1);build(c,'bulldoze',[tower]);assert.equal(tower.pipe,true);build(c,'waterTower',[tower]);assert.equal(tower.age,0);assert.equal(tower.unpollutedCapacity,120,'replacement removes age-related capacity loss');assert.equal(tower.pumpCapacity,Math.round(120*(1-tower.waterPollution*.0095)),'replacement retains current pollution losses');
assert.equal(build(c,'desalination',[{x:23,y:23}]).ok,false,'1960 technology gate');c.month=120;assert.ok(build(c,'desalination',[{x:23,y:23}]).ok);const des=c.tiles[idx(23,23)];assert.equal(des.pumpCapacity,0,'inland desalination cannot work');c.tiles[idx(22,23)].terrain='water';recompute(c);assert.equal(des.pumpCapacity,0,'fresh water cannot supply desalination');c.tiles[idx(22,23)].waterKind='salt';recompute(c);assert.equal(des.pumpCapacity,Math.round(350*(1-des.waterPollution*.0075)));assert.ok(build(c,'pump',[{x:21,y:23}]).ok);assert.equal(c.tiles[idx(21,23)].pumpCapacity,0,'salt water cannot supply freshwater pump');c.tiles[idx(20,23)].terrain='water';recompute(c);assert.ok(c.tiles[idx(21,23)].pumpCapacity>0);
const clean=base();build(clean,'coal',[{x:25,y:20}]);build(clean,'waterTower',[{x:23,y:20}]);build(clean,'waterTreatment',[{x:23,y:22}]);const a=clean.tiles[idx(23,20)],t=clean.tiles[idx(23,22)];a.waterPollution=80;recomputeWater(clean);const polluted=a.pumpCapacity;assert.equal(a.unpollutedCapacity,120);assert.equal(a.pollutionCapacityLoss,120-polluted);assert.equal(a.treatmentBenefit,0);assert.equal(t.treatmentActive,false,'treatment needs pipes');build(clean,'pipe',selection('pipe',{x:23,y:20},{x:23,y:22}));a.waterPollution=80;recomputeWater(clean);assert.ok(a.pumpCapacity>polluted);assert.equal(t.treatmentActive,true);const treated=a.pumpCapacity;assert.equal(a.treatmentBenefit,treated-polluted);assert.equal(a.pollutionCapacityLoss,120-treated);build(clean,'removePipe',[{x:23,y:21}]);a.waterPollution=80;recomputeWater(clean);assert.equal(a.pumpCapacity,polluted,'disconnected treatment cannot improve source');build(clean,'pipe',[{x:23,y:21}]);t.powered=false;a.waterPollution=80;recomputeWater(clean);assert.equal(a.pumpCapacity,polluted,'unpowered treatment cannot clean');assert.equal(a.treatmentBenefit,0);t.powered=true;t.age=600;a.waterPollution=80;recomputeWater(clean);assert.ok(a.pumpCapacity<treated,'treatment efficiency declines with age');recompute(clean);assert.deepEqual(validateSave(JSON.parse(JSON.stringify(clean))).stats,clean.stats);
const fresh=createCity();assert.ok(fresh.tiles.some(t=>t.terrain==='water'&&t.waterKind==='salt'));assert.ok(fresh.tiles.some(t=>t.terrain==='water'&&t.waterKind==='fresh'));const legacy=JSON.parse(JSON.stringify(fresh));legacy.version=11;for(const tile of legacy.tiles)delete tile.waterKind;assert.ok(validateSave(legacy).tiles.filter(t=>t.terrain==='water').every(t=>t.waterKind==='fresh'),'legacy water retains freshwater behavior');const bad=JSON.parse(JSON.stringify(fresh));bad.tiles[0].waterKind='lava';assert.throws(()=>validateSave(bad),/water source/);
console.log('PASS: inland tower supply, capacity/maintenance, aging and replacement, technology gate, fresh/salt source separation, connected/powered treatment, disconnection, treatment aging and save migration.');
