import assert from 'node:assert/strict';
import {createCity,idx,recompute,validateSave,build} from '../dist/engine.js';
import {startWhirlpool} from '../dist/whirlpool.js';
import {stepFire} from '../dist/emergency.js';
import {serializeCity} from '../dist/save.js';
import {attachCustomScenario} from '../dist/custom-scenarios.js';
import {runScenarioEvents} from '../dist/scenario-events.js';
const c=createCity('Coast',false);for(const t of c.tiles)Object.assign(t,{terrain:'land',nature:false,elevation:0});for(let y=0;y<48;y++)for(let x=20;x<=22;x++)c.tiles[idx(x,y)].terrain='water';
assert.equal(startWhirlpool(c,19,20).ok,false);
for(let x=19;x<=23;x++)Object.assign(c.tiles[idx(x,20)],{type:'road',bridgeAxis:x>19&&x<23?'x':null,rail:true,railAxis:x>19&&x<23?'x':null,highway:true,highwayAxis:x>19&&x<23?'x':null,pipe:true,subway:true});
Object.assign(c.tiles[idx(19,21)],{type:'residential',level:1});Object.assign(c.tiles[idx(17,21)],{type:'residential',level:1});recompute(c);
assert.ok(startWhirlpool(c,21,20).ok);assert.equal(startWhirlpool(c,21,20).ok,false);
for(let k=0;k<6;k++)stepFire(c);recompute(c);assert.equal(c.tiles[idx(21,20)].type,null);assert.equal(c.tiles[idx(21,20)].rubble,false);assert.ok(c.tiles[idx(21,20)].pipe&&c.tiles[idx(21,20)].subway);assert.equal(c.month,0);
const resumed=validateSave(JSON.parse(serializeCity(c)));for(let k=0;k<18;k++){stepFire(c);stepFire(resumed);}recompute(c);recompute(resumed);assert.equal(serializeCity(c),serializeCity(resumed));assert.equal(c.emergency.active,false);assert.equal(c.tiles[idx(19,21)].level,0);assert.equal(c.tiles[idx(17,21)].level,1);assert.equal(c.emergency.displaced,8);assert.ok(c.emergency.infrastructureLost>=9);assert.equal(c.emergency.contained,1);
const span=Array.from({length:5},(_,i)=>({x:19+i,y:20}));assert.ok(build(c,'bulldoze',span).ok);assert.ok(build(c,'road',span).ok);assert.equal(c.tiles[idx(21,20)].type,'road');
const old=JSON.parse(serializeCity(createCity()));old.version=49;delete old.emergency.whirlpool;delete old.emergency.whirlpools;assert.equal(validateSave(old).emergency.whirlpool,null);
const bad=JSON.parse(serializeCity(resumed));bad.emergency.active=true;bad.emergency.whirlpool={x:19,y:20,age:0};assert.throws(()=>validateSave(bad));
const scenario=createCity();attachCustomScenario(scenario,{title:'Tidal recovery',months:12,objectives:[{metric:'population',target:400}],events:[{type:'whirlpool',month:1,x:20,y:20}]});scenario.month=1;assert.equal(runScenarioEvents(scenario).status,'triggered');assert.equal(scenario.tiles[idx(scenario.emergency.whirlpool.x,scenario.emergency.whirlpool.y)].terrain,'water');
console.log('PASS: water-only whirlpool, bridge and shoreline loss, inland and buried network preservation, paused calendar, save continuity, expiry, rebuilding, migration and scheduled water targeting.');
