import assert from 'node:assert/strict';
import {drawCityPower,windRotorGeometry,windSceneryTime,WIND_REVOLUTION_SECONDS} from '../dist/power-models.js';
import {projectMiniature} from '../dist/miniature-raster.js';
import {CityRenderer} from '../dist/renderer.js';
import {createCity} from '../dist/engine.js';
import {serializeCity} from '../dist/save.js';
const a=windRotorGeometry(0),b=windRotorGeometry(.5);assert.notDeepEqual(a,b);assert.deepEqual(windRotorGeometry(WIND_REVOLUTION_SECONDS),a);
for(let frame=0;frame<60;frame++){const geometry=windRotorGeometry(frame/60*WIND_REVOLUTION_SECONDS);for(let blade=0;blade<3;blade++)for(let vertex=0;vertex<5;vertex++){const p=geometry[blade][vertex],old=a[blade][vertex];assert.ok(Math.abs(Math.hypot(p[0],p[2]-.8)-Math.hypot(old[0],old[2]-.8))<1e-12,'rigid rotation preserves blade length');for(let rotation=0;rotation<4;rotation++){const [x,y]=projectMiniature(p,rotation);assert.ok(x>=0&&x<=512&&y>=0&&y<=512);}}}
const c=createCity(),saved=serializeCity(c),r={preferences:{sceneryAnimations:true},layer:'city',reducedMotion:{matches:false},vehicleTime:2};assert.equal(windSceneryTime(r,{}),2);for(const patch of [{layer:'power'},{preferences:{sceneryAnimations:false}},{reducedMotion:{matches:true}}])assert.equal(windSceneryTime({...r,...patch},{}),null);for(const key of ['fire','rubble','radiation'])assert.equal(windSceneryTime(r,{[key]:true}),null);
let created=0,rasters=0;const order=[],paths=[];let path;const ctx={createImageData:(w,h)=>({data:new Uint8ClampedArray(w*h*4)}),putImageData(){rasters++;},save(){},restore(){},drawImage(){order.push('base');},beginPath(){path=[];},moveTo(x,y){path.push([x,y]);},lineTo(x,y){path.push([x,y]);},closePath(){},fill(){order.push('rotor');paths.push(path);}};
globalThis.document={createElement(){created++;return{getContext:()=>ctx};},hidden:false,querySelector:()=>null};globalThis.requestAnimationFrame=()=>{};
for(let rotation=0;rotation<4;rotation++){order.length=0;drawCityPower(ctx,'wind',rotation,100,100,84,.4,0);assert.deepEqual(order,rotation===0||rotation===3?['rotor','rotor','rotor','base']:['base','rotor','rotor','rotor']);for(let frame=1;frame<=60;frame++)drawCityPower(ctx,'wind',rotation,100,100,84,.4,frame/30);}
assert.equal(created,4);assert.equal(rasters,4,'moving rotors reuse four base images, not a bitmap per animation frame');assert.equal(ctx.globalAlpha,.4);assert.notDeepEqual(paths[0],paths[3]);assert.equal(serializeCity(c),saved);
const scene=Object.assign(Object.create(CityRenderer.prototype),{getCity:()=>c,preferences:{vehicleAnimations:false,pedestriansVisible:false,sceneryAnimations:true},reducedMotion:{matches:false},running:true,previousFrame:null,vehicleTime:0,time:0,dirty:false,layer:'city',zoom:1,draw(){}});scene.frame(0);scene.frame(100);assert.equal(scene.vehicleTime,.1);scene.running=false;scene.frame(200);assert.equal(scene.vehicleTime,.1);scene.running=true;document.hidden=true;scene.frame(300);assert.equal(scene.vehicleTime,.1);document.hidden=false;document.querySelector=()=>({open:true});scene.frame(400);assert.equal(scene.vehicleTime,.1);document.querySelector=()=>null;scene.reducedMotion.matches=true;scene.frame(500);assert.equal(scene.vehicleTime,.1);scene.reducedMotion.matches=false;c.emergency.active=true;scene.frame(600);assert.equal(scene.vehicleTime,.1);c.emergency.active=false;scene.frame(700);assert.equal(scene.vehicleTime,.2);
console.log('PASS: continuous rigid rotor geometry, four-view occlusion order, four-image cache across animation frames, reduced-motion/preferences/damage guards, actual pause/dialog/hidden/emergency clock holds and unchanged city state.');
